In [1]:
import numpy as np 
import pandas as pd 
import math

In [2]:
data=pd.read_csv("cmc_data.csv")

In [3]:
data.columns=["id","age","wife_education","husband_education","children", "religion", "wife_work", "husband_work","living_standard","exposure","Class"]

In [4]:
data.set_index("id", inplace=True)

In [5]:
data_class=data.groupby("Class")

In [6]:
data_class.size()

Class
1    628
2    333
3    511
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1472 entries, 2 to 1473
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                1472 non-null   int64
 1   wife_education     1472 non-null   int64
 2   husband_education  1472 non-null   int64
 3   children           1472 non-null   int64
 4   religion           1472 non-null   int64
 5   wife_work          1472 non-null   int64
 6   husband_work       1472 non-null   int64
 7   living_standard    1472 non-null   int64
 8   exposure           1472 non-null   int64
 9   Class              1472 non-null   int64
dtypes: int64(10)
memory usage: 126.5 KB

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [10]:
train_file_x=X_train.to_csv("kkk.csv")

In [11]:
test_file_x=X_test.to_csv("kk_test.csv")

In [12]:
train_file_y=Y_train.to_csv("lll.csv")

In [13]:
test_file_y=Y_test.to_csv("lll_test.csv")

In [14]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(1030, 10) (442, 10) (1030,) (442,)

In [15]:
X_train

,age,wife_education,husband_education,children,religion,wife_work,husband_work,living_standard,exposure,Class
id,,,,,,,,,,
1298,35,4,4,5,1,1,1,4,0,2
1445,22,4,4,2,1,1,3,4,0,3
1409,36,4,4,3,1,1,2,4,0,3
1202,25,4,4,3,1,1,1,2,0,1
1093,28,3,3,5,1,1,3,3,0,1
...,...,...,...,...,...,...,...,...,...,...
1271,41,4,4,4,0,0,2,4,0,2
1226,30,2,2,7,1,1,3,4,0,2
954,39,1,2,2,1,0,2,4,0,3
575,41,4,4,4,0,0,2,4,0,2
218,34,3,2,8,1,0,2,3,1,1

In [16]:
Y_train

id
1298    2
1445    3
1409    3
1202    1
1093    1
       ..
1271    2
1226    2
954     3
575     2
218     1
Name: Class, Length: 1030, dtype: int64

In [17]:
gb=X_train.groupby("Class")

In [18]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
      age  wife_education  husband_education  children  religion  wife_work  \
id
1202   25               4                  4         3         1          1
1093   28               3                  3         5         1          1
40     28               2                  2         1         1          1
1186   31               3                  2         1         1          1
126    31               3                  4         2         1          1
...   ...             ...                ...       ...       ...        ...
1047   28               2                  3         1         1          1
297    49               3                  4         9         1          1
1030   43               3                  4        10         1          1
366    20               2                  3         3         1          1
218    34               3                  2         8         1          0

      husband_work  living_standard  exposure  Class
id
1202             1                2         0      1
1093             3                3         0      1
40               2                4         0      1
1186             3                4         0      1
126              1                2         1      1
...            ...              ...       ...    ...
1047             3                1         0      1
297              1                4         0      1
1030             3                3         0      1
366              3                4         0      1
218              2                3         1      1

[433 rows x 10 columns]
2
      age  wife_education  husband_education  children  religion  wife_work  \
id
1298   35               4                  4         5         1          1
1233   28               4                  4         2         0          1
630    39               4                  4         5         1          1
1272   35               1                  2         9         1          0
605    40               3                  4         2         0          1
...   ...             ...                ...       ...       ...        ...
1245   34               3                  4         3         0          1
1243   38               2                  3         4         1          1
1271   41               4                  4         4         0          0
1226   30               2                  2         7         1          1
575    41               4                  4         4         0          0

      husband_work  living_standard  exposure  Class
id
1298             1                4         0      2
1233             1                4         0      2
630              1                4         0      2
1272             3                1         0      2
605              3                4         0      2
...            ...              ...       ...    ...
1245             1                4         0      2
1243             1                2         0      2
1271             2                4         0      2
1226             3                4         0      2
575              2                4         0      2

[233 rows x 10 columns]
3
      age  wife_education  husband_education  children  religion  wife_work  \
id
1445   22               4                  4         2         1          1
1409   36               4                  4         3         1          1
938    28               4                  4         3         0          0
695    26               2                  4         3         1          1
1443   42               4                  4         3         0          1
...   ...             ...                ...       ...       ...        ...
1451   27               4                  4         4         1          1
752    24               4                  4         2         1          1
658    28               4                  4         1         1          1
946    23               2                  3         2         1          0
954    39               1                  2         2         1          0

      husband_work  living_standard  exposure  Class
id
1445             3                4         0      3
1409             2                4         0      3
938              3                4         0      3
695              3                4         0      3
1443             2                4         0      3
...            ...              ...       ...    ...
1451             3                3         0      3
752              1                4         0      3
658              3                2         0      3
946              3                2         0      3
954              2                4         0      3

[364 rows x 10 columns]

In [19]:
gb.get_group(1)

,age,wife_education,husband_education,children,religion,wife_work,husband_work,living_standard,exposure,Class
id,,,,,,,,,,
1202,25,4,4,3,1,1,1,2,0,1
1093,28,3,3,5,1,1,3,3,0,1
40,28,2,2,1,1,1,2,4,0,1
1186,31,3,2,1,1,1,3,4,0,1
126,31,3,4,2,1,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...
1047,28,2,3,1,1,1,3,1,0,1
297,49,3,4,9,1,1,1,4,0,1
1030,43,3,4,10,1,1,3,3,0,1
366,20,2,3,3,1,1,3,4,0,1
218,34,3,2,8,1,0,2,3,1,1

In [20]:
class_samples=gb.get_group(1).sample(n=20)
print(class_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id
1203   47               1                  1         4         1          1
281    43               2                  3         6         1          0
251    34               4                  4         3         0          1
127    45               4                  4         1         1          1
1180   23               3                  2         0         1          1
1134   28               3                  4         0         1          0
1087   27               4                  4         2         1          0
199    30               1                  1         5         1          1
1138   37               3                  4         4         1          0
1150   36               4                  3         3         1          0
1076   45               3                  4         0         1          1
1094   25               3                  3         1         1          1
1059   30               1                  1         7         1          1
392    33               4                  4         5         1          1
342    42               3                  3         8         1          1
1135   27               3                  4         0         1          1
85     30               4                  4         2         1          1
1178   41               1                  3         3         1          0
84     28               4                  4         0         0          0
54     34               4                  4         1         0          0

      husband_work  living_standard  exposure  Class
id
1203             2                2         0      1
281              3                3         0      1
251              1                2         0      1
127              1                3         0      1
1180             2                2         0      1
1134             3                4         0      1
1087             1                4         0      1
199              2                2         0      1
1138             2                4         0      1
1150             3                2         0      1
1076             1                3         0      1
1094             2                2         0      1
1059             2                3         0      1
392              3                4         0      1
342              4                3         0      1
1135             3                3         0      1
85               1                4         0      1
1178             2                4         0      1
84               1                4         0      1
54               2                3         0      1

In [21]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>

In [22]:
mean_sum=class_samples["age"].mean() + class_samples["wife_education"].mean() + class_samples["husband_education"].mean() + class_samples["children"].mean() + class_samples["religion"].mean() + class_samples["wife_work"].mean() + class_samples["husband_work"].mean() + class_samples["living_standard"].mean() + class_samples["exposure"].mean()

In [23]:
similar_val_1=mean_sum/5
print(similar_val_1)

9.940000000000001

In [24]:
class_2_samples=gb.get_group(2).sample(n=20)
print(class_2_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id
1285   24               4                  4         2         1          1
1272   35               1                  2         9         1          0
498    26               4                  4         1         0          1
479    42               4                  4         6         1          1
1230   27               3                  3         2         1          1
618    35               2                  2         6         1          1
1312   42               3                  3         4         0          1
507    22               4                  4         1         1          1
455    36               4                  4         2         1          1
1252   34               3                  4         4         1          1
460    42               4                  4         8         0          1
584    24               4                  4         1         1          1
454    31               4                  4         1         1          1
485    31               3                  3         2         1          0
444    32               4                  4         2         0          0
1275   22               3                  3         2         1          1
1289   28               3                  4         2         0          1
514    36               4                  4         3         1          0
1233   28               4                  4         2         0          1
560    29               4                  3         4         1          0

      husband_work  living_standard  exposure  Class
id
1285             2                4         0      2
1272             3                1         0      2
498              2                4         0      2
479              1                3         0      2
1230             3                4         0      2
618              3                4         0      2
1312             3                4         0      2
507              1                2         0      2
455              2                4         0      2
1252             3                3         0      2
460              1                4         0      2
584              1                4         0      2
454              1                4         0      2
485              3                3         0      2
444              1                4         0      2
1275             3                3         0      2
1289             2                3         0      2
514              2                4         0      2
1233             1                4         0      2
560              3                2         0      2

In [25]:
mean_sum_2=class_2_samples["age"].mean() + class_2_samples["wife_education"].mean() + class_2_samples["husband_education"].mean() + class_2_samples["children"].mean() + class_2_samples["religion"].mean() + class_2_samples["wife_work"].mean() + class_2_samples["husband_work"].mean() + class_2_samples["living_standard"].mean() + class_2_samples["exposure"].mean()

In [26]:
similar_val_2=mean_sum_2/5
print(similar_val_2)

9.68

In [27]:
class_3_samples=gb.get_group(3).sample(n=20)
print(class_3_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id
833    21               3                  4         2         1          1
1387   33               4                  4         5         1          1
692    29               2                  4         3         1          1
890    33               4                  4         4         1          1
698    27               3                  4         2         1          1
1404   26               4                  4         3         1          1
878    42               4                  4         5         1          1
1416   36               3                  4         9         1          1
697    42               4                  4         7         1          1
1364   22               4                  4         1         1          1
712    39               3                  4         2         1          1
1401   27               3                  4         4         1          1
1362   29               3                  3         2         1          1
1431   32               2                  4         5         1          1
1350   24               1                  2         3         1          1
940    34               4                  4         6         1          1
751    24               2                  4         2         1          1
1322   34               3                  3         6         1          1
1352   21               3                  2         1         1          1
719    32               4                  4         3         0          1

      husband_work  living_standard  exposure  Class
id
833              3                3         0      3
1387             3                3         0      3
692              3                3         0      3
890              2                3         0      3
698              3                2         0      3
1404             3                2         0      3
878              1                4         0      3
1416             3                4         0      3
697              2                4         0      3
1364             2                4         0      3
712              1                3         0      3
1401             3                4         0      3
1362             3                2         0      3
1431             3                4         0      3
1350             3                2         0      3
940              2                2         0      3
751              1                4         0      3
1322             1                4         0      3
1352             3                1         1      3
719              1                4         0      3

In [28]:
mean_sum_3=class_3_samples["age"].mean() + class_3_samples["wife_education"].mean() + class_3_samples["husband_education"].mean() + class_3_samples["children"].mean() + class_3_samples["religion"].mean() + class_3_samples["wife_work"].mean() + class_3_samples["husband_work"].mean() + class_3_samples["living_standard"].mean() + class_3_samples["exposure"].mean()

In [29]:
similar_val_3=mean_sum_3/5
print(similar_val_3)

9.67

In [78]:
sim_23=abs(similar_val_2 - similar_val_3)
sim_23=sim_23/10
sim_23=1 - sim_23
sim_21=abs(similar_val_2 - similar_val_1)
sim_21=sim_21/10
sim_21=1 - sim_21
sim_13=abs(similar_val_3 - similar_val_1)
sim_13=sim_13/10
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_21)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.999
Similarity between 2 and 1:  0.9739999999999999
Similarity between 1 and 3:  0.9729999999999999

In [31]:
gb.size()

Class
1    433
2    233
3    364
dtype: int64

In [32]:
m=math.ceil((103+24)/2)

In [33]:
print(m)

64

In [34]:
len(gb)

3

In [35]:
 from sklearn.neighbors import KNeighborsClassifier

In [36]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [37]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [38]:
result=neigh.kneighbors(X_train, return_distance=True)

In [39]:
print(type(result))

<class 'tuple'>

In [40]:
print(result)

(array([[0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081],
       [0.        , 1.        , 1.        , 1.41421356, 1.41421356],
       ...,
       [0.        , 2.64575131, 2.64575131, 2.82842712, 3.        ],
       [0.        , 0.        , 0.        , 1.        , 1.41421356],
       [0.        , 1.73205081, 2.23606798, 2.23606798, 2.64575131]]), array([[   0,  508,   51,  314,  770],
       [   1,  244,  863,  987,  827],
       [   2,  299,   67,  914,  114],
       ...,
       [1027,  550,  927,  681,  122],
       [1025, 1028,  860,  502,  923],
       [1029,  703,  994,  985,  856]], dtype=int64))

In [41]:
arr1=result[0]

In [42]:
print(type(arr1))

<class 'numpy.ndarray'>

In [43]:
print(arr1.ndim)

2

In [44]:
arr2=result[1]

In [45]:
print(type(arr2))

<class 'numpy.ndarray'>

In [46]:
print(arr1.ndim)

2

In [47]:
print(arr2)

[[   0  508   51  314  770]
 [   1  244  863  987  827]
 [   2  299   67  914  114]
 ...
 [1027  550  927  681  122]
 [1025 1028  860  502  923]
 [1029  703  994  985  856]]

In [48]:
print(arr1)

[[0.         1.         1.         1.         1.        ]
 [0.         1.41421356 1.41421356 1.73205081 1.73205081]
 [0.         1.         1.         1.41421356 1.41421356]
 ...
 [0.         2.64575131 2.64575131 2.82842712 3.        ]
 [0.         0.         0.         1.         1.41421356]
 [0.         1.73205081 2.23606798 2.23606798 2.64575131]]

In [49]:
#print(arr1)

In [50]:
print(arr1.size)

5150

In [51]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.23606798 2.23606798 2.44948974]   9
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         2.44948974 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.73205081 2.        ]   6
[0.         2.44948974 2.44948974 2.82842712 3.16227766]   10
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         2.23606798 2.23606798 2.23606798 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.44948974 2.64575131 2.64575131]   9
[0.         1.         1.73205081 2.         2.        ]   6
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.         2.         2.44948974 2.44948974]   8
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         2.         2.23606798 2.44948974 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         2.         2.64575131 2.64575131 2.64575131]   9
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         2.         2.23606798 2.23606798 2.44948974]   8
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 2.23606798 2.23606798 2.44948974]   8
[0.         1.41421356 2.44948974 2.64575131 2.64575131]   9
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         1.         1.41421356 1.73205081 2.23606798]   6
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         0.         1.41421356 1.73205081 1.73205081]   4
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.23606798 2.23606798]   7
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.44948974 2.44948974 2.64575131 2.82842712]   10
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 2.23606798]   7
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.         2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.23606798 2.23606798 2.44948974]   9
[0. 2. 2. 2. 2.]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0. 1. 2. 2. 2.]   7
[0.         2.23606798 2.64575131 2.82842712 2.82842712]   10
[0.         2.44948974 2.64575131 2.64575131 2.82842712]   10
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.44948974 3.         3.         3.        ]   11
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.44948974 2.64575131 2.82842712]   10
[0.         1.41421356 1.41421356 2.         2.23606798]   7
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.23606798 2.44948974 2.64575131]   9
[0.         2.23606798 2.23606798 2.44948974 2.82842712]   9
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         2.23606798 2.64575131 2.64575131 2.64575131]   10
[0.         2.23606798 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         0.         1.73205081 2.         2.        ]   5
[0.         1.         1.         1.41421356 1.73205081]   5
[0. 1. 1. 2. 2.]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.23606798 2.23606798 2.64575131 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.41421356 2.82842712 2.82842712 3.16227766]   10
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         2.         2.44948974 2.44948974 2.64575131]   9
[0.         2.23606798 2.44948974 2.82842712 2.82842712]   10
[0.         2.82842712 2.82842712 3.16227766 3.16227766]   11
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         2.64575131 3.46410162 3.46410162 3.60555128]   13
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.73205081 1.73205081 2.        ]   6
[0.         2.         2.         2.         2.23606798]   8
[0.         1.41421356 1.41421356 1.41421356 2.        ]   6
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.23606798 2.44948974 2.64575131 2.64575131]   9
[0.         2.44948974 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 2.         2.         2.        ]   7
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         2.44948974 2.44948974 2.44948974 2.64575131]   9
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.44948974 2.82842712 2.82842712 3.        ]   11
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         2.         2.23606798 2.44948974]   7
[0.         2.         2.64575131 2.64575131 3.        ]   10
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 0. 0. 1. 1.]   2
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.44948974 2.64575131]   8
[0.         2.44948974 2.82842712 3.         3.16227766]   11
[0.         1.         1.73205081 1.73205081 2.23606798]   6
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 2.23606798 2.44948974 2.44948974]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         2.23606798 2.44948974 2.44948974 2.82842712]   9
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 2.         2.         2.        ]   7
[0.         2.23606798 2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 2.23606798 2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.44948974 2.64575131]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.23606798 2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 2.23606798 2.44948974 2.64575131]   8
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7

[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 2.23606798 2.44948974 2.82842712]   9
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.41421356 2.         2.        ]   6
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.         1.41421356 1.73205081 2.        ]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.23606798 2.44948974 2.44948974]   8
[0.         2.23606798 2.44948974 2.82842712 2.82842712]   10
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         2.64575131 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 2.        ]   5
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.23606798 2.44948974 2.44948974 2.44948974]   9
[0.         1.73205081 2.44948974 2.82842712 3.        ]   10
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 2.         2.         2.        ]   7
[0. 2. 2. 2. 2.]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         2.23606798 2.44948974 2.44948974 2.82842712]   9
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         0.         1.         1.73205081 1.73205081]   4
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.73205081 1.73205081 2.         2.82842712]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0. 1. 1. 1. 1.]   4
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         0.         1.         1.         1.41421356]   3
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.44948974]   7
[0.         2.         2.44948974 2.44948974 3.        ]   9
[0.         1.         1.         1.         1.41421356]   4
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.         2.44948974 2.44948974 2.82842712]   9
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         0.         1.         1.         1.41421356]   3
[0.         1.73205081 2.         2.23606798 2.64575131]   8
[0.         1.         1.73205081 2.         2.        ]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.44948974 2.44948974 2.82842712 3.        ]   10
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0. 2. 2. 2. 2.]   8
[0. 2. 2. 2. 2.]   8
[0.         1.         1.         1.73205081 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0. 1. 1. 1. 1.]   4
[0. 0. 0. 1. 1.]   2
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.23606798 2.44948974 3.        ]   9
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         2.64575131 2.64575131 2.64575131 3.16227766]   11
[0.         2.         2.44948974 2.44948974 2.64575131]   9
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.44948974 2.82842712 3.16227766 3.16227766]   11
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.82842712 3.         3.16227766 3.31662479]   12
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         2.         2.         2.         2.44948974]   8
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         2.         2.23606798 2.64575131 2.82842712]   9
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.64575131 2.64575131 2.64575131]   9
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.64575131 2.82842712 3.         3.31662479]   11
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.         2.         2.        ]   7
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         2.         2.         2.         2.23606798]   8
[0.         1.         1.73205081 2.         2.23606798]   6
[0.         1.         1.         1.         1.41421356]   4
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.82842712 3.16227766 3.16227766 3.74165739]   12
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.23606798 2.23606798 2.23606798]   8
[0.         1.         1.41421356 1.73205081 2.        ]   6
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.44948974 2.82842712 2.82842712]   9
[0.         1.73205081 2.         2.64575131 3.        ]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         1.41421356 2.64575131 2.82842712 3.        ]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 2.23606798 2.23606798]   7
[0.         1.41421356 2.23606798 2.23606798 2.23606798]   8
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         2.23606798 2.64575131 2.64575131 3.31662479]   10
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 2.23606798 2.23606798 2.44948974]   8
[0.         1.73205081 2.23606798 2.23606798 2.44948974]   8
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.         2.23606798]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.73205081 2.         2.44948974]   7
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.         2.         2.         2.23606798]   8
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.23606798 2.44948974 2.64575131 2.64575131]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.         2.         2.         2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         0.         1.         1.         1.41421356]   3
[0.         2.         2.         2.         2.23606798]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         0.         1.         1.         1.41421356]   3
[0.         2.23606798 2.64575131 2.82842712 3.        ]   10
[0.         2.         2.         2.         2.23606798]   8
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6

[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.44948974 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 2.        ]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 2.        ]   6
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.73205081 1.73205081 2.23606798 2.23606798]   7
[0.         1.73205081 1.73205081 2.44948974 2.64575131]   8
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         0.         2.         2.44948974 2.44948974]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 2.44948974 2.44948974 2.64575131]   8
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         0.         1.41421356 1.41421356 1.73205081]   4
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         2.         2.44948974 2.64575131 2.82842712]   9
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         2.23606798 2.23606798 2.44948974 2.82842712]   9
[0.         2.         2.         2.         2.23606798]   8
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         2.23606798 2.23606798 2.64575131 2.82842712]   9
[0.         1.         2.         2.23606798 2.44948974]   7
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 2.         2.44948974 2.64575131]   8
[0.         0.         1.         1.73205081 1.73205081]   4
[0.         1.73205081 2.23606798 2.23606798 2.23606798]   8
[0.         0.         1.41421356 2.23606798 2.64575131]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.73205081 2.23606798 2.44948974 2.44948974]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         2.23606798 2.23606798 2.82842712 3.        ]   10
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.         1.         1.73205081]   4
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.73205081 2.44948974 2.64575131 3.        ]   9
[0.         1.73205081 1.73205081 2.23606798 2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 2.23606798]   7
[0.         2.82842712 2.82842712 2.82842712 2.82842712]   11
[0.         0.         1.         1.         1.41421356]   3
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         0.         1.         1.         1.41421356]   3
[0.         1.73205081 2.23606798 2.64575131 2.82842712]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.         1.         1.         1.41421356]   4
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.23606798 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 2.         2.23606798 2.44948974]   8
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 2.23606798 2.23606798 2.23606798]   8
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.64575131 2.82842712 2.82842712]   10
[0.         2.44948974 2.82842712 2.82842712 3.16227766]   11
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         3.         3.         3.31662479 3.60555128]   12
[0.         2.23606798 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.44948974 2.64575131 2.64575131 2.82842712]   10
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.82842712 2.82842712 2.82842712 3.31662479]   11
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.82842712 2.82842712 2.82842712]   10
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.73205081 2.23606798 2.44948974 2.44948974]   8
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.64575131 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.44948974 2.64575131 2.64575131]   9
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         2.         2.23606798 2.44948974 2.44948974]   9
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 2.         2.23606798 2.44948974]   8
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         5.38516481 5.47722558 5.56776436 6.164414  ]   22
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5

[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 2.         2.         2.44948974]   7
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.         1.         1.41421356]   4
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         0.         1.         1.         1.41421356]   3
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 2.         2.        ]   6
[0.         2.23606798 2.82842712 2.82842712 2.82842712]   10
[0.         1.73205081 2.         2.44948974 2.64575131]   8
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         2.82842712 3.         3.16227766 3.31662479]   12
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.         1.         1.41421356 1.73205081]   5
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.64575131 3.         3.16227766 3.16227766]   11
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         0.         1.41421356 2.23606798 2.64575131]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 2.         2.23606798]   7
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.        ]   7
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         1.41421356 1.73205081 2.         2.23606798]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.23606798 2.44948974 2.82842712 2.82842712]   10
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.44948974 2.64575131]   8
[0.         0.         1.41421356 1.41421356 1.41421356]   4
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.44948974 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         2.23606798 2.23606798 2.82842712 2.82842712]   10
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.44948974 2.44948974]   8
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.73205081 2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.82842712 2.82842712 2.82842712 3.16227766]   11
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 2.         2.         2.44948974]   7
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 2.23606798]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         2.         2.23606798 2.64575131 3.        ]   9
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 2.         2.44948974 2.44948974]   8
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         1.73205081 1.73205081 2.         2.44948974]   7
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.23606798 2.44948974 2.44948974]   8
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         2.23606798 2.44948974 2.64575131 2.64575131]   9
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.23606798 2.64575131 2.64575131 2.82842712]   10
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.         2.44948974 2.82842712 2.82842712]   10
[0.         1.41421356 1.73205081 2.64575131 2.64575131]   8
[0.         1.41421356 2.         2.         2.23606798]   7
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.44948974 2.64575131 2.64575131]   10
[0.         1.73205081 2.         3.         3.        ]   9
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         2.23606798 2.44948974 2.64575131 2.64575131]   9
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 2.23606798 2.44948974]   8
[0.         1.         1.73205081 2.         2.23606798]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         2.44948974 2.64575131 2.64575131 2.82842712]   10
[0.         2.         2.23606798 2.64575131 2.64575131]   9
[0.         0.         1.         1.         1.41421356]   3
[0.         1.41421356 1.73205081 1.73205081 2.44948974]   7
[0.         1.73205081 1.73205081 2.44948974 2.82842712]   8

[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         2.23606798 2.23606798 2.23606798 2.44948974]   9
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         1.         1.41421356 2.         2.        ]   6
[0. 0. 0. 1. 1.]   2
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.23606798]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         2.44948974 2.44948974 2.64575131]   8
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 2.23606798]   7
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         0.         1.73205081 2.         2.        ]   5
[0.         1.73205081 1.73205081 2.23606798 2.23606798]   7
[0.         2.         2.23606798 2.23606798 2.44948974]   8
[0.         2.23606798 2.44948974 2.44948974 2.44948974]   9
[0. 0. 0. 1. 1.]   2
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.41421356 1.41421356 2.         2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         0.         1.41421356 1.41421356 1.73205081]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         2.         2.         2.         2.23606798]   8
[0.         2.         2.         2.         2.23606798]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.23606798 2.23606798 2.44948974]   8
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         1.73205081 1.73205081 1.73205081 2.23606798]   7
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0. 0. 0. 1. 1.]   2
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         2.23606798 2.23606798 2.23606798 2.23606798]   8
[0.         2.23606798 2.23606798 2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.23606798 2.23606798 2.23606798 2.23606798]   8
[0. 2. 2. 2. 2.]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         2.23606798 2.44948974 2.64575131]   8
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.73205081 2.         2.44948974 2.44948974]   8
[0.         1.41421356 1.73205081 2.44948974 2.44948974]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.         2.23606798]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.         1.73205081 2.         2.23606798]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.73205081 2.         2.        ]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         0.         0.         1.         1.41421356]   2
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 2. 2. 2. 2.]   8
[0.         1.41421356 2.         2.         2.        ]   7
[0.         2.64575131 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 2.         2.44948974]   7
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.23606798 2.44948974 2.44948974 2.64575131]   9
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         3.16227766 3.16227766 3.46410162 3.46410162]   13
[0.         0.         1.         1.41421356 1.73205081]   4
[0.         1.41421356 1.41421356 2.         2.23606798]   7
[0.         2.23606798 2.23606798 2.64575131 2.64575131]   9
[0.         1.73205081 2.         2.44948974 2.44948974]   8
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.41421356 2.        ]   6
[0.         2.         2.23606798 2.23606798 2.23606798]   8
[0.         2.23606798 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.         2.23606798 2.64575131 2.64575131]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         0.         1.         1.41421356 1.41421356]   3
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.         2.         2.        ]   7
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         3.74165739 3.87298335 3.87298335 3.87298335]   15
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.64575131 2.64575131 2.82842712]   10
[0.         1.73205081 2.         2.         2.44948974]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 1.73205081 1.73205081 2.44948974]   7
[0.         2.64575131 2.64575131 2.82842712 3.        ]   11
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         0.         1.41421356 1.73205081 1.73205081]   4

[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.         1.73205081 1.73205081]   5
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 2.23606798 2.44948974]   7
[0.         2.23606798 2.23606798 2.23606798 2.23606798]   8
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.73205081 2.23606798 2.23606798 2.44948974]   8
[0.         2.         2.23606798 2.23606798 2.44948974]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9
[0.         2.23606798 2.44948974 2.82842712 2.82842712]   10
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         1.         1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.         2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         1.73205081 2.         2.23606798 2.64575131]   8
[0.         1.         1.         1.         1.41421356]   4
[0.         3.16227766 3.74165739 3.74165739 3.87298335]   14
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         2.         2.         2.64575131 2.82842712]   9
[0.         3.         3.         3.         3.16227766]   12
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.         1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 2.         2.         2.        ]   7
[0.         1.         1.41421356 1.73205081 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 2.23606798 2.44948974 2.44948974]   8
[0.         1.41421356 1.73205081 2.23606798 2.23606798]   7
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6
[0.         1.73205081 2.         2.         2.23606798]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0. 0. 0. 1. 1.]   2
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.41421356 2.         2.        ]   6
[0.         1.41421356 2.23606798 2.44948974 2.64575131]   8
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         2.         2.         2.23606798 2.44948974]   8
[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10
[0.         2.64575131 2.64575131 2.82842712 2.82842712]   10
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         2.23606798 2.44948974 2.44948974 2.44948974]   9
[0.         1.41421356 2.23606798 2.23606798 2.64575131]   8
[0.         1.73205081 1.73205081 2.         2.23606798]   7
[0.         1.41421356 1.41421356 2.         2.        ]   6
[0.         2.         2.         2.23606798 2.23606798]   8
[0.         1.73205081 2.         2.23606798 2.23606798]   8
[0. 1. 1. 1. 2.]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.73205081 2.23606798]   6
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.73205081 2.23606798 2.44948974 2.64575131]   9
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.73205081 2.         2.         2.        ]   7
[0.         1.41421356 2.         2.23606798 2.23606798]   7
[0.         1.41421356 2.44948974 2.64575131 2.82842712]   9
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         1.73205081 2.         2.23606798 2.44948974]   8
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6
[0.         2.         2.         2.         2.23606798]   8
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.73205081 2.         2.        ]   7
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         0.         2.         2.44948974 2.44948974]   6
[0.         0.         0.         1.         1.41421356]   2
[0.         1.73205081 1.73205081 2.         2.        ]   7
[0.         2.64575131 2.64575131 2.82842712 3.        ]   11
[0.         0.         0.         1.         1.41421356]   2
[0.         1.73205081 2.23606798 2.23606798 2.64575131]   8

In [52]:
print(len(addVal))

1030

In [53]:
print(addVal)

[4, 6, 4, 7, 9, 5, 6, 5, 8, 7, 7, 5, 9, 5, 6, 6, 6, 5, 7, 10, 5, 5, 6, 10, 5, 7, 9, 6, 9, 6, 8, 6, 8, 8, 9, 7, 9, 8, 8, 5, 7, 4, 5, 8, 9, 6, 4, 5, 3, 7, 6, 4, 5, 7, 4, 5, 5, 7, 5, 10, 6, 5, 8, 6, 8, 7, 8, 5, 7, 8, 4, 9, 7, 5, 9, 8, 6, 7, 10, 10, 5, 9, 10, 4, 5, 6, 10, 7, 11, 5, 6, 5, 5, 6, 10, 7, 7, 5, 6, 6, 5, 9, 9, 6, 10, 9, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 6, 9, 6, 5, 8, 7, 10, 6, 4, 9, 10, 11, 4, 6, 7, 13, 6, 9, 6, 5, 6, 6, 8, 6, 7, 9, 9, 7, 4, 5, 4, 9, 5, 8, 5, 7, 7, 11, 6, 7, 10, 4, 4, 7, 5, 5, 7, 5, 2, 5, 8, 11, 6, 7, 8, 8, 5, 9, 5, 7, 9, 6, 7, 5, 6, 8, 6, 5, 9, 6, 5, 6, 8, 7, 6, 8, 7, 4, 9, 4, 6, 7, 6, 3, 6, 5, 8, 10, 7, 7, 10, 5, 6, 8, 8, 6, 5, 8, 4, 6, 9, 10, 6, 6, 6, 5, 5, 5, 7, 9, 5, 6, 3, 5, 6, 7, 4, 7, 8, 5, 4, 9, 7, 5, 4, 8, 8, 5, 5, 7, 4, 7, 6, 8, 6, 7, 3, 5, 4, 3, 5, 7, 9, 4, 9, 8, 4, 5, 6, 5, 7, 9, 5, 5, 3, 8, 6, 4, 6, 7, 6, 5, 10, 5, 9, 4, 7, 4, 6, 4, 7, 8, 8, 5, 7, 5, 6, 5, 4, 2, 7, 5, 5, 3, 5, 9, 4, 4, 11, 9, 4, 11, 5, 5, 12, 5, 9, 6, 8, 8, 6, 4, 6, 6, 5, 6, 9, 7, 5, 9, 4, 5, 11, 5, 7, 8, 8, 6, 4, 7, 5, 5, 4, 5, 8, 5, 12, 6, 8, 6, 6, 5, 9, 9, 6, 8, 9, 6, 5, 7, 8, 4, 6, 10, 7, 6, 8, 8, 6, 8, 4, 5, 5, 5, 7, 5, 4, 5, 8, 7, 5, 4, 9, 7, 6, 5, 7, 5, 7, 7, 5, 8, 7, 9, 6, 8, 6, 5, 5, 7, 3, 8, 5, 6, 6, 3, 10, 8, 7, 6, 5, 7, 8, 9, 7, 7, 7, 9, 8, 6, 7, 9, 6, 5, 5, 5, 6, 6, 7, 7, 8, 7, 6, 5, 6, 6, 4, 5, 6, 8, 4, 6, 5, 4, 6, 5, 6, 6, 9, 7, 5, 5, 8, 9, 8, 8, 6, 6, 6, 6, 3, 6, 5, 5, 7, 6, 5, 9, 6, 6, 6, 5, 7, 5, 9, 7, 7, 9, 5, 4, 9, 7, 10, 7, 8, 4, 8, 6, 6, 6, 5, 7, 7, 8, 6, 6, 6, 6, 8, 10, 7, 4, 6, 3, 9, 7, 5, 5, 7, 11, 3, 6, 6, 4, 5, 5, 6, 6, 10, 5, 5, 3, 9, 6, 10, 4, 5, 3, 5, 7, 7, 6, 4, 7, 9, 8, 8, 7, 8, 5, 5, 6, 10, 11, 6, 7, 12, 9, 6, 10, 6, 6, 11, 6, 6, 6, 5, 6, 10, 5, 8, 5, 5, 4, 10, 6, 7, 6, 5, 7, 5, 6, 5, 6, 9, 4, 6, 6, 6, 7, 8, 7, 9, 7, 8, 7, 5, 5, 6, 7, 5, 4, 7, 22, 6, 5, 5, 6, 7, 6, 4, 6, 5, 7, 3, 5, 7, 7, 8, 7, 3, 7, 6, 10, 8, 7, 7, 8, 5, 7, 5, 5, 7, 5, 6, 5, 7, 12, 7, 5, 4, 6, 5, 10, 5, 8, 4, 10, 5, 11, 4, 6, 6, 6, 5, 6, 7, 4, 6, 7, 4, 7, 5, 6, 10, 6, 4, 6, 5, 6, 6, 8, 4, 5, 4, 5, 6, 6, 5, 6, 5, 10, 5, 6, 7, 5, 6, 7, 5, 4, 10, 5, 4, 5, 8, 7, 8, 6, 8, 7, 11, 7, 7, 7, 7, 6, 6, 5, 8, 9, 7, 4, 8, 7, 7, 7, 5, 8, 8, 3, 9, 5, 7, 6, 10, 9, 7, 5, 5, 7, 5, 6, 10, 4, 10, 8, 7, 6, 5, 6, 10, 9, 4, 7, 5, 7, 5, 6, 9, 5, 8, 6, 6, 5, 8, 7, 10, 9, 3, 7, 8, 10, 5, 6, 8, 5, 9, 7, 5, 5, 7, 3, 6, 2, 5, 6, 7, 6, 8, 4, 5, 7, 8, 5, 5, 5, 6, 5, 7, 8, 9, 2, 6, 7, 9, 6, 5, 4, 6, 6, 8, 4, 8, 8, 8, 5, 7, 6, 8, 6, 8, 7, 6, 6, 10, 5, 5, 5, 7, 5, 5, 7, 6, 7, 7, 6, 7, 5, 6, 5, 2, 8, 6, 8, 8, 6, 5, 5, 5, 8, 8, 6, 5, 8, 7, 5, 4, 8, 8, 6, 6, 8, 5, 9, 6, 8, 6, 6, 5, 6, 4, 8, 5, 6, 7, 9, 4, 6, 7, 2, 6, 6, 5, 8, 7, 10, 7, 5, 6, 5, 5, 7, 4, 7, 6, 7, 7, 6, 7, 5, 5, 9, 6, 7, 6, 13, 4, 7, 9, 8, 7, 6, 8, 8, 6, 6, 5, 6, 7, 7, 6, 8, 10, 6, 7, 6, 5, 7, 8, 5, 4, 3, 9, 4, 5, 7, 8, 15, 5, 6, 10, 8, 5, 9, 6, 7, 11, 7, 8, 5, 10, 5, 5, 5, 5, 4, 8, 7, 5, 6, 6, 6, 7, 8, 8, 6, 5, 5, 8, 8, 5, 7, 9, 10, 7, 5, 8, 5, 10, 5, 10, 5, 6, 5, 9, 5, 7, 6, 8, 4, 14, 5, 9, 12, 7, 6, 7, 5, 5, 8, 7, 7, 6, 6, 7, 6, 5, 2, 7, 6, 6, 8, 5, 8, 10, 10, 6, 5, 4, 9, 8, 7, 6, 8, 8, 5, 5, 6, 6, 9, 6, 4, 7, 7, 9, 6, 8, 6, 8, 5, 5, 7, 6, 6, 2, 7, 11, 2, 8]

In [54]:
arr3=np.array(addVal)

In [55]:
print(type(arr3))

<class 'numpy.ndarray'>

In [56]:
print(arr3.size)

1030

In [57]:
print(arr3)

[ 4  6  4 ... 11  2  8]

In [58]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   4
2   6
3   4
4   7
5   9
6   5
7   6
8   5
9   8
10   7
11   7
12   5
13   9
14   5
15   6
16   6
17   6
18   5
19   7
20   10
21   5
22   5
23   6
24   10
25   5
26   7
27   9
28   6
29   9
30   6
31   8
32   6
33   8
34   8
35   9
36   7
37   9
38   8
39   8
40   5
41   7
42   4
43   5
44   8
45   9
46   6
47   4
48   5
49   3
50   7
51   6
52   4
53   5
54   7
55   4
56   5
57   5
58   7
59   5
60   10
61   6
62   5
63   8
64   6
65   8
66   7
67   8
68   5
69   7
70   8
71   4
72   9
73   7
74   5
75   9
76   8
77   6
78   7
79   10
80   10
81   5
82   9
83   10
84   4
85   5
86   6
87   10
88   7
89   11
90   5
91   6
92   5
93   5
94   6
95   10
96   7
97   7
98   5
99   6
100   6
101   5
102   9
103   9
104   6
105   10
106   9
107   6
108   5
109   5
110   6
111   5
112   5
113   5
114   6
115   5
116   5
117   5
118   5
119   6
120   5
121   6
122   6
123   9
124   6
125   5
126   8
127   7
128   10
129   6
130   4
131   9
132   10
133   11
134   4
135   6
136   7
137   13
138   6
139   9
140   6
141   5
142   6
143   6
144   8
145   6
146   7
147   9
148   9
149   7
150   4
151   5
152   4
153   9
154   5
155   8
156   5
157   7
158   7
159   11
160   6
161   7
162   10
163   4
164   4
165   7
166   5
167   5
168   7
169   5
170   2
171   5
172   8
173   11
174   6
175   7
176   8
177   8
178   5
179   9
180   5
181   7
182   9
183   6
184   7
185   5
186   6
187   8
188   6
189   5
190   9
191   6
192   5
193   6
194   8
195   7
196   6
197   8
198   7
199   4
200   9
201   4
202   6
203   7
204   6
205   3
206   6
207   5
208   8
209   10
210   7
211   7
212   10
213   5
214   6
215   8
216   8
217   6
218   5
219   8
220   4
221   6
222   9
223   10
224   6
225   6
226   6
227   5
228   5
229   5
230   7
231   9
232   5
233   6
234   3
235   5
236   6
237   7
238   4
239   7
240   8
241   5
242   4
243   9
244   7
245   5
246   4
247   8
248   8
249   5
250   5
251   7
252   4
253   7
254   6
255   8
256   6
257   7
258   3
259   5
260   4
261   3
262   5
263   7
264   9
265   4
266   9
267   8
268   4
269   5
270   6
271   5
272   7
273   9
274   5
275   5
276   3
277   8
278   6
279   4
280   6
281   7
282   6
283   5
284   10
285   5
286   9
287   4
288   7
289   4
290   6
291   4
292   7
293   8
294   8
295   5
296   7
297   5
298   6
299   5
300   4
301   2
302   7
303   5
304   5
305   3
306   5
307   9
308   4
309   4
310   11
311   9
312   4
313   11
314   5
315   5
316   12
317   5
318   9
319   6
320   8
321   8
322   6
323   4
324   6
325   6
326   5
327   6
328   9
329   7
330   5
331   9
332   4
333   5
334   11
335   5
336   7
337   8
338   8
339   6
340   4
341   7
342   5
343   5
344   4
345   5
346   8
347   5
348   12
349   6
350   8
351   6
352   6
353   5
354   9
355   9
356   6
357   8
358   9
359   6
360   5
361   7
362   8
363   4
364   6
365   10
366   7
367   6
368   8
369   8
370   6
371   8
372   4
373   5
374   5
375   5
376   7
377   5
378   4
379   5
380   8
381   7
382   5
383   4
384   9
385   7
386   6
387   5
388   7
389   5
390   7
391   7
392   5
393   8
394   7
395   9
396   6
397   8
398   6
399   5
400   5
401   7
402   3
403   8
404   5
405   6
406   6
407   3
408   10
409   8
410   7
411   6
412   5
413   7
414   8
415   9
416   7
417   7
418   7
419   9
420   8
421   6
422   7
423   9
424   6
425   5
426   5
427   5
428   6
429   6
430   7
431   7
432   8
433   7
434   6
435   5
436   6
437   6
438   4
439   5
440   6
441   8
442   4
443   6
444   5
445   4
446   6
447   5
448   6
449   6
450   9
451   7
452   5
453   5
454   8
455   9
456   8
457   8
458   6
459   6
460   6
461   6
462   3
463   6
464   5
465   5
466   7
467   6
468   5
469   9
470   6
471   6
472   6
473   5
474   7
475   5
476   9
477   7
478   7
479   9
480   5
481   4
482   9
483   7
484   10
485   7
486   8
487   4
488   8
489   6
490   6
491   6
492   5
493   7
494   7
495   8
496   6
497   6
498   6
499   6
500   8
501   10
502   7
503   4
504   6
505   3
506   9
507   7
508   5
509   5
510   7
511   11
512   3
513   6
514   6
515   4
516   5
517   5
518   6
519   6
520   10
521   5
522   5
523   3
524   9
525   6
526   10
527   4
528   5
529   3
530   5
531   7
532   7
533   6
534   4
535   7
536   9
537   8
538   8
539   7
540   8
541   5
542   5
543   6
544   10
545   11
546   6
547   7
548   12
549   9
550   6
551   10
552   6
553   6
554   11
555   6
556   6
557   6
558   5
559   6
560   10
561   5
562   8
563   5
564   5
565   4
566   10
567   6
568   7
569   6
570   5
571   7
572   5
573   6
574   5
575   6
576   9
577   4
578   6
579   6
580   6
581   7
582   8
583   7
584   9
585   7
586   8
587   7
588   5
589   5
590   6
591   7
592   5
593   4
594   7
595   22
596   6
597   5
598   5
599   6
600   7
601   6
602   4
603   6
604   5
605   7
606   3
607   5
608   7
609   7
610   8
611   7
612   3
613   7
614   6
615   10
616   8
617   7
618   7
619   8
620   5
621   7
622   5
623   5
624   7
625   5
626   6
627   5
628   7
629   12
630   7
631   5
632   4
633   6
634   5
635   10
636   5
637   8
638   4
639   10
640   5
641   11
642   4
643   6
644   6
645   6
646   5
647   6
648   7
649   4
650   6
651   7
652   4
653   7
654   5
655   6
656   10
657   6
658   4
659   6
660   5
661   6
662   6
663   8
664   4
665   5
666   4
667   5
668   6
669   6
670   5
671   6
672   5
673   10
674   5
675   6
676   7
677   5
678   6
679   7
680   5
681   4
682   10
683   5
684   4
685   5
686   8
687   7
688   8
689   6
690   8
691   7
692   11
693   7
694   7
695   7
696   7
697   6
698   6
699   5
700   8
701   9
702   7
703   4
704   8
705   7
706   7
707   7
708   5
709   8
710   8
711   3
712   9
713   5
714   7
715   6
716   10
717   9
718   7
719   5
720   5
721   7
722   5
723   6
724   10
725   4
726   10
727   8
728   7
729   6
730   5
731   6
732   10
733   9
734   4
735   7
736   5
737   7
738   5
739   6
740   9
741   5
742   8
743   6
744   6
745   5
746   8
747   7
748   10
749   9
750   3
751   7
752   8
753   10
754   5
755   6
756   8
757   5
758   9
759   7
760   5
761   5
762   7
763   3
764   6
765   2
766   5
767   6
768   7
769   6
770   8
771   4
772   5
773   7
774   8
775   5
776   5
777   5
778   6
779   5
780   7
781   8
782   9
783   2
784   6
785   7
786   9
787   6
788   5
789   4
790   6
791   6
792   8
793   4
794   8
795   8
796   8
797   5
798   7
799   6
800   8
801   6
802   8
803   7
804   6
805   6
806   10
807   5
808   5
809   5
810   7
811   5
812   5
813   7
814   6
815   7
816   7
817   6
818   7
819   5
820   6
821   5
822   2
823   8
824   6
825   8
826   8
827   6
828   5
829   5
830   5
831   8
832   8
833   6
834   5
835   8
836   7
837   5
838   4
839   8
840   8
841   6
842   6
843   8
844   5
845   9
846   6
847   8
848   6
849   6
850   5
851   6
852   4
853   8
854   5
855   6
856   7
857   9
858   4
859   6
860   7
861   2
862   6
863   6
864   5
865   8
866   7
867   10
868   7
869   5
870   6
871   5
872   5
873   7
874   4
875   7
876   6
877   7
878   7
879   6
880   7
881   5
882   5
883   9
884   6
885   7
886   6
887   13
888   4
889   7
890   9
891   8
892   7
893   6
894   8
895   8
896   6
897   6
898   5
899   6
900   7
901   7
902   6
903   8
904   10
905   6
906   7
907   6
908   5
909   7
910   8
911   5
912   4
913   3
914   9
915   4
916   5
917   7
918   8
919   15
920   5
921   6
922   10
923   8
924   5
925   9
926   6
927   7
928   11
929   7
930   8
931   5
932   10
933   5
934   5
935   5
936   5
937   4
938   8
939   7
940   5
941   6
942   6
943   6
944   7
945   8
946   8
947   6
948   5
949   5
950   8
951   8
952   5
953   7
954   9
955   10
956   7
957   5
958   8
959   5
960   10
961   5
962   10
963   5
964   6
965   5
966   9
967   5
968   7
969   6
970   8
971   4
972   14
973   5
974   9
975   12
976   7
977   6
978   7
979   5
980   5
981   8
982   7
983   7
984   6
985   6
986   7
987   6
988   5
989   2
990   7
991   6
992   6
993   8
994   5
995   8
996   10
997   10
998   6
999   5
1000   4
1001   9
1002   8
1003   7
1004   6
1005   8
1006   8
1007   5
1008   5
1009   6
1010   6
1011   9
1012   6
1013   4
1014   7
1015   7
1016   9
1017   6
1018   8
1019   6
1020   8
1021   5
1022   5
1023   7
1024   6
1025   6
1026   2
1027   7
1028   11
1029   2
1030   8

In [59]:
newarr = arr3.reshape(1030, 1)

In [60]:
print(newarr.ndim)

2

In [61]:
new_arr2=np.append(arr2, newarr, axis=1)

In [62]:
print(type(new_arr2))

<class 'numpy.ndarray'>

In [63]:
print(new_arr2)

[[   0  508   51  314  770    4]
 [   1  244  863  987  827    6]
 [   2  299   67  914  114    4]
 ...
 [1027  550  927  681  122   11]
 [1025 1028  860  502  923    2]
 [1029  703  994  985  856    8]]

In [64]:
print(new_arr2[0])

[  0 508  51 314 770   4]

In [65]:
print(type(Y_train))

<class 'pandas.core.series.Series'>

In [66]:
arr2

array([[   0,  508,   51,  314,  770],
       [   1,  244,  863,  987,  827],
       [   2,  299,   67,  914,  114],
       ...,
       [1027,  550,  927,  681,  122],
       [1025, 1028,  860,  502,  923],
       [1029,  703,  994,  985,  856]], dtype=int64)

In [67]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

508 51 314 770 4

In [68]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [69]:
print(new_dist)

{1298: 2, 1445: 3, 1409: 3, 1202: 1, 1093: 1, 1233: 2, 938: 3, 695: 3, 40: 1, 1443: 3, 1186: 1, 689: 3, 126: 1, 321: 1, 64: 1, 887: 3, 824: 3, 165: 1, 912: 3, 1100: 1, 1073: 1, 630: 2, 1381: 3, 1272: 2, 1151: 1, 22: 1, 1086: 1, 605: 2, 1224: 2, 1369: 3, 1033: 1, 9: 1, 1120: 1, 460: 2, 1000: 3, 560: 2, 516: 2, 527: 2, 128: 1, 903: 3, 1074: 1, 791: 3, 115: 1, 535: 2, 106: 1, 132: 1, 982: 3, 1400: 3, 586: 2, 1454: 3, 334: 1, 418: 2, 935: 3, 189: 1, 1107: 1, 1375: 3, 861: 3, 610: 2, 857: 3, 315: 1, 1350: 3, 1307: 2, 391: 1, 1214: 1, 56: 1, 1452: 3, 289: 1, 782: 3, 3: 1, 1158: 1, 1247: 2, 18: 1, 207: 1, 1152: 1, 1276: 2, 705: 3, 1013: 1, 885: 3, 1046: 1, 229: 1, 1349: 3, 60: 1, 1418: 3, 1216: 2, 976: 3, 252: 1, 950: 3, 1138: 1, 700: 3, 306: 1, 1005: 1, 25: 1, 1275: 2, 845: 3, 53: 1, 913: 3, 1431: 3, 793: 3, 671: 3, 924: 3, 406: 1, 19: 1, 1212: 1, 831: 3, 1167: 1, 530: 2, 858: 3, 753: 3, 783: 3, 1426: 3, 1260: 2, 787: 3, 1472: 3, 636: 2, 455: 2, 309: 1, 1082: 1, 495: 2, 294: 1, 485: 2, 854: 3, 1297: 2, 11: 1, 1145: 1, 823: 3, 1346: 3, 471: 2, 1143: 1, 622: 2, 80: 1, 205: 1, 231: 1, 215: 1, 540: 2, 555: 2, 276: 1, 359: 1, 384: 1, 196: 1, 1085: 1, 542: 2, 296: 1, 597: 2, 446: 2, 389: 1, 1266: 2, 43: 1, 1302: 2, 1321: 3, 1373: 3, 1106: 1, 502: 2, 1248: 2, 1102: 1, 408: 1, 414: 1, 142: 1, 492: 2, 501: 2, 518: 2, 260: 1, 41: 1, 972: 3, 537: 2, 442: 2, 818: 3, 238: 1, 364: 1, 595: 2, 463: 2, 75: 1, 1170: 1, 801: 3, 1397: 3, 1180: 1, 1313: 2, 1190: 1, 449: 2, 99: 1, 838: 3, 176: 1, 1317: 2, 47: 1, 1156: 1, 879: 3, 166: 1, 258: 1, 664: 3, 392: 1, 327: 1, 417: 2, 1189: 1, 303: 1, 1172: 1, 744: 3, 1231: 2, 317: 1, 440: 2, 507: 2, 139: 1, 900: 3, 249: 1, 723: 3, 1450: 3, 1264: 2, 167: 1, 710: 3, 398: 1, 486: 2, 1051: 1, 1312: 2, 1203: 1, 771: 3, 798: 3, 685: 3, 21: 1, 450: 2, 122: 1, 959: 3, 27: 1, 454: 2, 278: 1, 172: 1, 59: 1, 951: 3, 614: 2, 875: 3, 1235: 2, 1331: 3, 1352: 3, 67: 1, 914: 3, 1396: 3, 623: 2, 890: 3, 911: 3, 593: 2, 1401: 3, 926: 3, 1291: 2, 955: 3, 770: 3, 484: 2, 847: 3, 979: 3, 1135: 1, 1066: 1, 445: 2, 1252: 2, 934: 3, 768: 3, 785: 3, 114: 1, 945: 3, 1380: 3, 659: 3, 680: 3, 995: 3, 253: 1, 981: 3, 985: 3, 513: 2, 1465: 3, 1416: 3, 254: 1, 469: 2, 259: 1, 1225: 2, 746: 3, 1165: 1, 1413: 3, 794: 3, 1420: 3, 621: 2, 1410: 3, 1222: 2, 352: 1, 1116: 1, 146: 1, 8: 1, 1394: 3, 1191: 1, 1305: 2, 1009: 1, 906: 3, 358: 1, 1110: 1, 372: 1, 749: 3, 346: 1, 699: 3, 1322: 3, 1177: 1, 712: 3, 1365: 3, 653: 3, 160: 1, 1149: 1, 113: 1, 1385: 3, 49: 1, 731: 3, 604: 2, 1289: 2, 459: 2, 1285: 2, 354: 1, 585: 2, 458: 2, 1249: 2, 505: 2, 1282: 2, 201: 1, 1389: 3, 1084: 1, 1209: 1, 594: 2, 188: 1, 997: 3, 90: 1, 1339: 3, 726: 3, 1208: 1, 248: 1, 839: 3, 1324: 3, 6: 1, 1128: 1, 1428: 3, 1461: 3, 1029: 1, 856: 3, 1341: 3, 1044: 1, 174: 1, 686: 3, 1440: 3, 1361: 3, 747: 3, 1412: 3, 349: 1, 1144: 1, 452: 2, 476: 2, 1265: 2, 342: 1, 701: 3, 1140: 1, 494: 2, 1088: 1, 314: 1, 405: 1, 1070: 1, 183: 1, 235: 1, 607: 2, 1131: 1, 943: 3, 1387: 3, 984: 3, 379: 1, 242: 1, 1359: 3, 1304: 2, 1006: 1, 1182: 1, 1025: 1, 1035: 1, 163: 1, 226: 1, 239: 1, 462: 2, 266: 1, 804: 3, 1130: 1, 329: 1, 1024: 1, 1403: 3, 141: 1, 1139: 1, 504: 2, 819: 3, 932: 3, 100: 1, 543: 2, 553: 2, 88: 1, 1016: 1, 1280: 2, 1142: 1, 993: 3, 1228: 2, 1467: 3, 251: 1, 925: 3, 764: 3, 1031: 1, 46: 1, 775: 3, 1263: 2, 795: 3, 962: 3, 104: 1, 754: 3, 345: 1, 698: 3, 1194: 1, 424: 2, 1462: 3, 124: 1, 662: 3, 1112: 1, 902: 3, 1246: 2, 990: 3, 1251: 2, 910: 3, 591: 2, 428: 2, 1171: 1, 443: 2, 526: 2, 937: 3, 280: 1, 1037: 1, 510: 2, 1278: 2, 151: 1, 1255: 2, 1061: 1, 83: 1, 337: 1, 1187: 1, 415: 1, 629: 2, 687: 3, 466: 2, 720: 3, 538: 2, 789: 3, 468: 2, 1220: 2, 202: 1, 1358: 3, 77: 1, 580: 2, 1342: 3, 1096: 1, 541: 2, 1343: 3, 751: 3, 1372: 3, 584: 2, 564: 2, 639: 2, 1256: 2, 665: 3, 1377: 3, 797: 3, 707: 3, 820: 3, 721: 3, 1200: 1, 1281: 2, 1114: 1, 436: 2, 548: 2, 137: 1, 759: 3, 227: 1, 1466: 3, 456: 2, 692: 3, 704: 3, 1424: 3, 681: 3, 208: 1, 863: 3, 1290: 2, 663: 3, 975: 3, 1049: 1, 74: 1, 404: 1, 192: 1, 1022: 1, 222: 1, 1099: 1, 293: 1, 512: 2, 498: 2, 930: 3, 1415: 3, 919: 3, 716: 3, 1244: 2, 1141: 1, 1332: 3, 855: 3, 1126: 1, 125: 1, 657: 3, 1308: 2, 1019: 1, 1435: 3, 1204: 1, 891: 3, 116: 1, 1268: 2, 1210: 1, 641: 2, 566: 2, 572: 2, 886: 3, 652: 3, 1087: 1, 292: 1, 84: 1, 1463: 3, 958: 3, 980: 3, 1348: 3, 1148: 1, 1090: 1, 964: 3, 960: 3, 86: 1, 1232: 2, 719: 3, 1134: 1, 777: 3, 33: 1, 790: 3, 722: 3, 216: 1, 1178: 1, 348: 1, 341: 1, 57: 1, 921: 3, 120: 1, 497: 2, 805: 3, 1064: 1, 250: 1, 667: 3, 1329: 3, 180: 1, 214: 1, 1357: 3, 1457: 3, 1238: 2, 1091: 1, 674: 3, 247: 1, 1277: 2, 755: 3, 781: 3, 1181: 1, 393: 1, 194: 1, 842: 3, 909: 3, 1362: 3, 816: 3, 1471: 3, 1414: 3, 732: 3, 536: 2, 291: 1, 357: 1, 474: 2, 1458: 3, 69: 1, 221: 1, 961: 3, 834: 3, 483: 2, 684: 3, 331: 1, 1330: 3, 373: 1, 618: 2, 691: 3, 381: 1, 638: 2, 1296: 2, 246: 1, 1432: 3, 717: 3, 592: 2, 1441: 3, 127: 1, 44: 1, 654: 3, 29: 1, 350: 1, 154: 1, 1353: 3, 355: 1, 1294: 2, 968: 3, 1012: 1, 1404: 3, 390: 1, 929: 3, 673: 3, 147: 1, 1393: 3, 974: 3, 312: 1, 447: 2, 286: 1, 957: 3, 1419: 3, 1052: 1, 533: 2, 1320: 2, 103: 1, 433: 2, 1183: 1, 13: 1, 844: 3, 61: 1, 461: 2, 500: 2, 612: 2, 434: 2, 1121: 1, 1164: 1, 1115: 1, 725: 3, 1104: 1, 264: 1, 290: 1, 656: 3, 285: 1, 1053: 1, 565: 2, 419: 2, 1159: 1, 473: 2, 1065: 1, 1207: 1, 1425: 3, 880: 3, 66: 1, 388: 1, 225: 1, 884: 3, 233: 1, 529: 2, 402: 1, 162: 1, 170: 1, 1132: 1, 444: 2, 756: 3, 895: 3, 515: 2, 1338: 3, 1179: 1, 134: 1, 171: 1, 874: 3, 1356: 3, 1469: 3, 79: 1, 936: 3, 514: 2, 130: 1, 1166: 1, 956: 3, 742: 3, 48: 1, 145: 1, 613: 2, 240: 1, 1018: 1, 1340: 3, 135: 1, 121: 1, 305: 1, 1146: 1, 1036: 1, 1407: 3, 472: 2, 475: 2, 439: 2, 1175: 1, 65: 1, 1021: 1, 479: 2, 54: 1, 1213: 1, 200: 1, 784: 3, 55: 1, 1007: 1, 190: 1, 101: 1, 1464: 3, 1026: 1, 1111: 1, 1219: 2, 528: 2, 894: 3, 581: 2, 1027: 1, 1270: 2, 1229: 2, 270: 1, 711: 3, 1011: 1, 177: 1, 815: 3, 1383: 3, 32: 1, 953: 3, 386: 1, 569: 2, 105: 1, 615: 2, 1174: 1, 488: 2, 1002: 1, 34: 1, 45: 1, 1015: 1, 1449: 3, 544: 2, 523: 2, 301: 1, 1055: 1, 362: 1, 525: 2, 489: 2, 1097: 1, 1273: 2, 217: 1, 1386: 3, 324: 1, 487: 2, 1230: 2, 1328: 3, 743: 3, 1117: 1, 1153: 1, 996: 3, 1446: 3, 1284: 2, 562: 2, 733: 3, 1236: 2, 643: 3, 1003: 1, 1354: 3, 1108: 1, 916: 3, 573: 2, 169: 1, 1283: 2, 727: 3, 967: 3, 168: 1, 204: 1, 1101: 1, 58: 1, 1287: 2, 678: 3, 1227: 2, 1337: 3, 848: 3, 1059: 1, 714: 3, 1315: 2, 883: 3, 326: 1, 82: 1, 852: 3, 363: 1, 762: 3, 457: 2, 256: 1, 651: 3, 1057: 1, 353: 1, 506: 2, 395: 1, 241: 1, 588: 2, 940: 3, 920: 3, 1316: 2, 320: 1, 882: 3, 1267: 2, 432: 2, 558: 2, 1423: 3, 117: 1, 38: 1, 905: 3, 606: 2, 897: 3, 98: 1, 206: 1, 24: 1, 51: 1, 1405: 3, 1221: 2, 634: 2, 1032: 1, 1417: 3, 281: 1, 107: 1, 496: 2, 333: 1, 1334: 3, 826: 3, 893: 3, 300: 1, 1028: 1, 374: 1, 1160: 1, 482: 2, 715: 3, 833: 3, 441: 2, 907: 3, 1429: 3, 611: 2, 757: 3, 808: 3, 73: 1, 1442: 3, 1438: 3, 822: 3, 228: 1, 4: 1, 182: 1, 524: 2, 316: 1, 846: 3, 199: 1, 245: 1, 851: 3, 330: 1, 426: 2, 1094: 1, 545: 2, 287: 1, 1206: 1, 236: 1, 275: 1, 1198: 1, 112: 1, 774: 3, 1460: 3, 328: 1, 577: 2, 335: 1, 991: 3, 1364: 3, 617: 2, 1147: 1, 1199: 1, 508: 2, 1374: 3, 1274: 2, 1017: 1, 1433: 3, 387: 1, 602: 2, 758: 3, 931: 3, 378: 1, 203: 1, 298: 1, 1473: 3, 709: 3, 810: 3, 1071: 1, 1258: 2, 5: 1, 788: 3, 748: 3, 1286: 2, 868: 3, 10: 1, 269: 1, 351: 1, 864: 3, 344: 1, 862: 3, 272: 1, 91: 1, 209: 1, 1023: 1, 892: 3, 836: 3, 1436: 3, 1371: 3, 94: 1, 669: 3, 158: 1, 1311: 2, 908: 3, 186: 1, 666: 3, 1295: 2, 583: 2, 987: 3, 821: 3, 829: 3, 696: 3, 877: 3, 867: 3, 193: 1, 220: 1, 1378: 3, 1406: 3, 574: 2, 1318: 2, 262: 1, 521: 2, 178: 1, 322: 1, 15: 1, 274: 1, 70: 1, 922: 3, 917: 3, 827: 3, 670: 3, 1279: 2, 1076: 1, 1242: 2, 1241: 2, 682: 3, 421: 2, 78: 1, 1391: 3, 1072: 1, 39: 1, 978: 3, 396: 1, 609: 2, 1347: 3, 133: 1, 1041: 1, 881: 3, 1020: 1, 1162: 1, 243: 1, 308: 1, 941: 3, 1150: 1, 448: 2, 688: 3, 828: 3, 1382: 3, 813: 3, 871: 3, 952: 3, 1399: 3, 915: 3, 1137: 1, 546: 2, 212: 1, 878: 3, 1345: 3, 807: 3, 1163: 1, 131: 1, 532: 2, 339: 1, 904: 3, 619: 2, 590: 2, 97: 1, 741: 3, 640: 2, 988: 3, 1390: 3, 369: 1, 866: 3, 869: 3, 1319: 2, 143: 1, 85: 1, 1004: 1, 649: 3, 901: 3, 637: 2, 1336: 3, 1089: 1, 1176: 1, 778: 3, 87: 1, 411: 1, 403: 1, 360: 1, 282: 1, 1363: 3, 1427: 3, 1129: 1, 760: 3, 1047: 1, 635: 2, 297: 1, 949: 3, 1470: 3, 697: 3, 425: 2, 1030: 1, 779: 3, 1309: 2, 1245: 2, 1243: 2, 1451: 3, 752: 3, 658: 3, 946: 3, 366: 1, 1271: 2, 1226: 2, 954: 3, 575: 2, 218: 1}

In [70]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [71]:
print(new_dist2)

{0: 2, 1: 3, 2: 3, 3: 1, 4: 1, 5: 2, 6: 3, 7: 3, 8: 1, 9: 3, 10: 1, 11: 3, 12: 1, 13: 1, 14: 1, 15: 3, 16: 3, 17: 1, 18: 3, 19: 1, 20: 1, 21: 2, 22: 3, 23: 2, 24: 1, 25: 1, 26: 1, 27: 2, 28: 2, 29: 3, 30: 1, 31: 1, 32: 1, 33: 2, 34: 3, 35: 2, 36: 2, 37: 2, 38: 1, 39: 3, 40: 1, 41: 3, 42: 1, 43: 2, 44: 1, 45: 1, 46: 3, 47: 3, 48: 2, 49: 3, 50: 1, 51: 2, 52: 3, 53: 1, 54: 1, 55: 3, 56: 3, 57: 2, 58: 3, 59: 1, 60: 3, 61: 2, 62: 1, 63: 1, 64: 1, 65: 3, 66: 1, 67: 3, 68: 1, 69: 1, 70: 2, 71: 1, 72: 1, 73: 1, 74: 2, 75: 3, 76: 1, 77: 3, 78: 1, 79: 1, 80: 3, 81: 1, 82: 3, 83: 2, 84: 3, 85: 1, 86: 3, 87: 1, 88: 3, 89: 1, 90: 1, 91: 1, 92: 2, 93: 3, 94: 1, 95: 3, 96: 3, 97: 3, 98: 3, 99: 3, 100: 1, 101: 1, 102: 1, 103: 3, 104: 1, 105: 2, 106: 3, 107: 3, 108: 3, 109: 3, 110: 2, 111: 3, 112: 3, 113: 2, 114: 2, 115: 1, 116: 1, 117: 2, 118: 1, 119: 2, 120: 3, 121: 2, 122: 1, 123: 1, 124: 3, 125: 3, 126: 2, 127: 1, 128: 2, 129: 1, 130: 1, 131: 1, 132: 1, 133: 2, 134: 2, 135: 1, 136: 1, 137: 1, 138: 1, 139: 1, 140: 2, 141: 1, 142: 2, 143: 2, 144: 1, 145: 2, 146: 1, 147: 2, 148: 3, 149: 3, 150: 1, 151: 2, 152: 2, 153: 1, 154: 1, 155: 1, 156: 1, 157: 2, 158: 2, 159: 2, 160: 1, 161: 1, 162: 3, 163: 2, 164: 2, 165: 3, 166: 1, 167: 1, 168: 2, 169: 2, 170: 1, 171: 1, 172: 3, 173: 3, 174: 1, 175: 2, 176: 1, 177: 2, 178: 1, 179: 3, 180: 1, 181: 2, 182: 1, 183: 1, 184: 3, 185: 1, 186: 1, 187: 3, 188: 1, 189: 1, 190: 2, 191: 1, 192: 1, 193: 1, 194: 3, 195: 2, 196: 1, 197: 2, 198: 2, 199: 1, 200: 3, 201: 1, 202: 3, 203: 3, 204: 2, 205: 1, 206: 3, 207: 1, 208: 2, 209: 1, 210: 2, 211: 1, 212: 3, 213: 3, 214: 3, 215: 1, 216: 2, 217: 1, 218: 3, 219: 1, 220: 2, 221: 1, 222: 1, 223: 1, 224: 3, 225: 2, 226: 3, 227: 2, 228: 3, 229: 3, 230: 1, 231: 3, 232: 3, 233: 2, 234: 3, 235: 3, 236: 2, 237: 3, 238: 3, 239: 2, 240: 3, 241: 3, 242: 2, 243: 3, 244: 3, 245: 1, 246: 1, 247: 2, 248: 2, 249: 3, 250: 3, 251: 3, 252: 1, 253: 3, 254: 3, 255: 3, 256: 3, 257: 3, 258: 1, 259: 3, 260: 3, 261: 2, 262: 3, 263: 3, 264: 1, 265: 2, 266: 1, 267: 2, 268: 3, 269: 1, 270: 3, 271: 3, 272: 3, 273: 2, 274: 3, 275: 2, 276: 1, 277: 1, 278: 1, 279: 1, 280: 3, 281: 1, 282: 2, 283: 1, 284: 3, 285: 1, 286: 1, 287: 1, 288: 3, 289: 1, 290: 3, 291: 3, 292: 1, 293: 3, 294: 3, 295: 3, 296: 1, 297: 1, 298: 1, 299: 3, 300: 1, 301: 3, 302: 2, 303: 2, 304: 2, 305: 2, 306: 1, 307: 2, 308: 2, 309: 2, 310: 2, 311: 2, 312: 1, 313: 3, 314: 1, 315: 1, 316: 2, 317: 1, 318: 3, 319: 1, 320: 3, 321: 3, 322: 1, 323: 1, 324: 3, 325: 3, 326: 1, 327: 1, 328: 3, 329: 3, 330: 1, 331: 3, 332: 3, 333: 1, 334: 1, 335: 3, 336: 3, 337: 3, 338: 3, 339: 3, 340: 1, 341: 1, 342: 2, 343: 2, 344: 2, 345: 1, 346: 3, 347: 1, 348: 2, 349: 1, 350: 1, 351: 1, 352: 1, 353: 1, 354: 1, 355: 2, 356: 1, 357: 3, 358: 3, 359: 3, 360: 1, 361: 1, 362: 3, 363: 2, 364: 1, 365: 1, 366: 1, 367: 1, 368: 1, 369: 1, 370: 1, 371: 2, 372: 1, 373: 3, 374: 1, 375: 1, 376: 1, 377: 3, 378: 1, 379: 1, 380: 2, 381: 3, 382: 3, 383: 1, 384: 2, 385: 2, 386: 1, 387: 1, 388: 2, 389: 1, 390: 3, 391: 2, 392: 3, 393: 1, 394: 3, 395: 3, 396: 1, 397: 1, 398: 3, 399: 2, 400: 3, 401: 3, 402: 1, 403: 3, 404: 1, 405: 3, 406: 1, 407: 2, 408: 3, 409: 1, 410: 3, 411: 1, 412: 3, 413: 2, 414: 3, 415: 2, 416: 3, 417: 2, 418: 2, 419: 1, 420: 2, 421: 2, 422: 3, 423: 1, 424: 1, 425: 2, 426: 2, 427: 1, 428: 2, 429: 1, 430: 1, 431: 1, 432: 1, 433: 1, 434: 2, 435: 3, 436: 2, 437: 3, 438: 2, 439: 3, 440: 2, 441: 2, 442: 1, 443: 3, 444: 1, 445: 2, 446: 3, 447: 1, 448: 2, 449: 3, 450: 3, 451: 3, 452: 2, 453: 2, 454: 2, 455: 2, 456: 3, 457: 3, 458: 3, 459: 3, 460: 3, 461: 3, 462: 1, 463: 2, 464: 1, 465: 2, 466: 2, 467: 1, 468: 3, 469: 1, 470: 3, 471: 2, 472: 3, 473: 3, 474: 3, 475: 3, 476: 1, 477: 3, 478: 2, 479: 3, 480: 3, 481: 1, 482: 1, 483: 1, 484: 1, 485: 1, 486: 1, 487: 1, 488: 1, 489: 2, 490: 2, 491: 3, 492: 3, 493: 3, 494: 3, 495: 2, 496: 1, 497: 3, 498: 3, 499: 1, 500: 1, 501: 3, 502: 2, 503: 1, 504: 3, 505: 1, 506: 3, 507: 1, 508: 2, 509: 1, 510: 2, 511: 2, 512: 2, 513: 3, 514: 3, 515: 1, 516: 1, 517: 1, 518: 3, 519: 3, 520: 3, 521: 3, 522: 1, 523: 1, 524: 3, 525: 3, 526: 1, 527: 2, 528: 3, 529: 1, 530: 3, 531: 1, 532: 3, 533: 3, 534: 1, 535: 1, 536: 1, 537: 1, 538: 1, 539: 3, 540: 1, 541: 2, 542: 3, 543: 1, 544: 1, 545: 3, 546: 3, 547: 1, 548: 1, 549: 3, 550: 3, 551: 2, 552: 1, 553: 3, 554: 1, 555: 2, 556: 3, 557: 3, 558: 1, 559: 1, 560: 1, 561: 3, 562: 3, 563: 3, 564: 3, 565: 3, 566: 3, 567: 3, 568: 2, 569: 1, 570: 1, 571: 2, 572: 3, 573: 1, 574: 1, 575: 3, 576: 3, 577: 2, 578: 3, 579: 1, 580: 3, 581: 1, 582: 2, 583: 3, 584: 1, 585: 2, 586: 2, 587: 1, 588: 3, 589: 3, 590: 2, 591: 3, 592: 1, 593: 1, 594: 3, 595: 1, 596: 1, 597: 1, 598: 3, 599: 1, 600: 2, 601: 3, 602: 1, 603: 3, 604: 1, 605: 3, 606: 3, 607: 1, 608: 3, 609: 3, 610: 1, 611: 2, 612: 1, 613: 3, 614: 3, 615: 1, 616: 2, 617: 2, 618: 1, 619: 2, 620: 1, 621: 1, 622: 3, 623: 1, 624: 2, 625: 2, 626: 2, 627: 2, 628: 1, 629: 1, 630: 1, 631: 3, 632: 1, 633: 1, 634: 1, 635: 3, 636: 1, 637: 1, 638: 2, 639: 2, 640: 1, 641: 2, 642: 1, 643: 1, 644: 3, 645: 3, 646: 1, 647: 1, 648: 1, 649: 3, 650: 1, 651: 2, 652: 1, 653: 1, 654: 1, 655: 1, 656: 2, 657: 3, 658: 3, 659: 2, 660: 3, 661: 1, 662: 1, 663: 1, 664: 3, 665: 3, 666: 3, 667: 1, 668: 3, 669: 2, 670: 1, 671: 1, 672: 3, 673: 3, 674: 1, 675: 1, 676: 2, 677: 1, 678: 1, 679: 3, 680: 1, 681: 1, 682: 1, 683: 1, 684: 1, 685: 3, 686: 2, 687: 2, 688: 2, 689: 1, 690: 1, 691: 1, 692: 2, 693: 1, 694: 1, 695: 1, 696: 3, 697: 1, 698: 1, 699: 1, 700: 1, 701: 3, 702: 1, 703: 1, 704: 2, 705: 2, 706: 3, 707: 2, 708: 1, 709: 2, 710: 2, 711: 1, 712: 3, 713: 1, 714: 1, 715: 3, 716: 3, 717: 1, 718: 3, 719: 1, 720: 2, 721: 1, 722: 2, 723: 1, 724: 2, 725: 1, 726: 1, 727: 1, 728: 1, 729: 3, 730: 2, 731: 2, 732: 1, 733: 1, 734: 1, 735: 2, 736: 2, 737: 1, 738: 2, 739: 1, 740: 3, 741: 1, 742: 2, 743: 2, 744: 3, 745: 3, 746: 1, 747: 1, 748: 3, 749: 3, 750: 2, 751: 2, 752: 3, 753: 2, 754: 3, 755: 1, 756: 3, 757: 1, 758: 3, 759: 2, 760: 1, 761: 2, 762: 3, 763: 3, 764: 1, 765: 1, 766: 1, 767: 1, 768: 2, 769: 3, 770: 2, 771: 3, 772: 3, 773: 1, 774: 3, 775: 2, 776: 3, 777: 1, 778: 1, 779: 3, 780: 1, 781: 3, 782: 2, 783: 1, 784: 3, 785: 1, 786: 1, 787: 2, 788: 1, 789: 1, 790: 2, 791: 3, 792: 3, 793: 2, 794: 1, 795: 3, 796: 2, 797: 2, 798: 2, 799: 3, 800: 1, 801: 1, 802: 3, 803: 2, 804: 3, 805: 1, 806: 1, 807: 1, 808: 1, 809: 3, 810: 2, 811: 2, 812: 1, 813: 3, 814: 1, 815: 1, 816: 2, 817: 1, 818: 3, 819: 3, 820: 3, 821: 1, 822: 1, 823: 1, 824: 1, 825: 2, 826: 3, 827: 3, 828: 2, 829: 3, 830: 3, 831: 2, 832: 3, 833: 3, 834: 1, 835: 3, 836: 3, 837: 3, 838: 1, 839: 1, 840: 1, 841: 2, 842: 1, 843: 3, 844: 1, 845: 1, 846: 3, 847: 1, 848: 2, 849: 1, 850: 2, 851: 1, 852: 1, 853: 1, 854: 1, 855: 1, 856: 1, 857: 3, 858: 3, 859: 1, 860: 2, 861: 1, 862: 3, 863: 3, 864: 2, 865: 1, 866: 1, 867: 2, 868: 3, 869: 2, 870: 1, 871: 3, 872: 1, 873: 2, 874: 3, 875: 3, 876: 1, 877: 1, 878: 1, 879: 3, 880: 3, 881: 3, 882: 1, 883: 2, 884: 1, 885: 3, 886: 3, 887: 2, 888: 3, 889: 1, 890: 1, 891: 1, 892: 3, 893: 1, 894: 3, 895: 1, 896: 1, 897: 1, 898: 1, 899: 3, 900: 3, 901: 3, 902: 3, 903: 1, 904: 3, 905: 1, 906: 2, 907: 3, 908: 1, 909: 3, 910: 2, 911: 2, 912: 3, 913: 3, 914: 3, 915: 3, 916: 3, 917: 3, 918: 1, 919: 1, 920: 3, 921: 3, 922: 2, 923: 2, 924: 1, 925: 2, 926: 1, 927: 1, 928: 1, 929: 1, 930: 1, 931: 3, 932: 3, 933: 3, 934: 3, 935: 2, 936: 1, 937: 2, 938: 2, 939: 3, 940: 2, 941: 1, 942: 3, 943: 1, 944: 1, 945: 3, 946: 1, 947: 2, 948: 3, 949: 1, 950: 1, 951: 3, 952: 1, 953: 1, 954: 1, 955: 1, 956: 3, 957: 1, 958: 2, 959: 3, 960: 3, 961: 3, 962: 3, 963: 3, 964: 3, 965: 3, 966: 3, 967: 1, 968: 2, 969: 1, 970: 3, 971: 3, 972: 3, 973: 1, 974: 1, 975: 2, 976: 1, 977: 3, 978: 2, 979: 2, 980: 1, 981: 3, 982: 2, 983: 3, 984: 3, 985: 1, 986: 3, 987: 3, 988: 2, 989: 1, 990: 1, 991: 1, 992: 3, 993: 3, 994: 2, 995: 3, 996: 1, 997: 1, 998: 3, 999: 1, 1000: 1, 1001: 1, 1002: 1, 1003: 1, 1004: 3, 1005: 3, 1006: 1, 1007: 3, 1008: 1, 1009: 2, 1010: 1, 1011: 3, 1012: 3, 1013: 3, 1014: 2, 1015: 1, 1016: 3, 1017: 2, 1018: 2, 1019: 2, 1020: 3, 1021: 3, 1022: 3, 1023: 3, 1024: 1, 1025: 2, 1026: 2, 1027: 3, 1028: 2, 1029: 1}

In [72]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [73]:
print(new_dist3)

{0: 1298, 1: 1445, 2: 1409, 3: 1202, 4: 1093, 5: 1233, 6: 938, 7: 695, 8: 40, 9: 1443, 10: 1186, 11: 689, 12: 126, 13: 321, 14: 64, 15: 887, 16: 824, 17: 165, 18: 912, 19: 1100, 20: 1073, 21: 630, 22: 1381, 23: 1272, 24: 1151, 25: 22, 26: 1086, 27: 605, 28: 1224, 29: 1369, 30: 1033, 31: 9, 32: 1120, 33: 460, 34: 1000, 35: 560, 36: 516, 37: 527, 38: 128, 39: 903, 40: 1074, 41: 791, 42: 115, 43: 535, 44: 106, 45: 132, 46: 982, 47: 1400, 48: 586, 49: 1454, 50: 334, 51: 418, 52: 935, 53: 189, 54: 1107, 55: 1375, 56: 861, 57: 610, 58: 857, 59: 315, 60: 1350, 61: 1307, 62: 391, 63: 1214, 64: 56, 65: 1452, 66: 289, 67: 782, 68: 3, 69: 1158, 70: 1247, 71: 18, 72: 207, 73: 1152, 74: 1276, 75: 705, 76: 1013, 77: 885, 78: 1046, 79: 229, 80: 1349, 81: 60, 82: 1418, 83: 1216, 84: 976, 85: 252, 86: 950, 87: 1138, 88: 700, 89: 306, 90: 1005, 91: 25, 92: 1275, 93: 845, 94: 53, 95: 913, 96: 1431, 97: 793, 98: 671, 99: 924, 100: 406, 101: 19, 102: 1212, 103: 831, 104: 1167, 105: 530, 106: 858, 107: 753, 108: 783, 109: 1426, 110: 1260, 111: 787, 112: 1472, 113: 636, 114: 455, 115: 309, 116: 1082, 117: 495, 118: 294, 119: 485, 120: 854, 121: 1297, 122: 11, 123: 1145, 124: 823, 125: 1346, 126: 471, 127: 1143, 128: 622, 129: 80, 130: 205, 131: 231, 132: 215, 133: 540, 134: 555, 135: 276, 136: 359, 137: 384, 138: 196, 139: 1085, 140: 542, 141: 296, 142: 597, 143: 446, 144: 389, 145: 1266, 146: 43, 147: 1302, 148: 1321, 149: 1373, 150: 1106, 151: 502, 152: 1248, 153: 1102, 154: 408, 155: 414, 156: 142, 157: 492, 158: 501, 159: 518, 160: 260, 161: 41, 162: 972, 163: 537, 164: 442, 165: 818, 166: 238, 167: 364, 168: 595, 169: 463, 170: 75, 171: 1170, 172: 801, 173: 1397, 174: 1180, 175: 1313, 176: 1190, 177: 449, 178: 99, 179: 838, 180: 176, 181: 1317, 182: 47, 183: 1156, 184: 879, 185: 166, 186: 258, 187: 664, 188: 392, 189: 327, 190: 417, 191: 1189, 192: 303, 193: 1172, 194: 744, 195: 1231, 196: 317, 197: 440, 198: 507, 199: 139, 200: 900, 201: 249, 202: 723, 203: 1450, 204: 1264, 205: 167, 206: 710, 207: 398, 208: 486, 209: 1051, 210: 1312, 211: 1203, 212: 771, 213: 798, 214: 685, 215: 21, 216: 450, 217: 122, 218: 959, 219: 27, 220: 454, 221: 278, 222: 172, 223: 59, 224: 951, 225: 614, 226: 875, 227: 1235, 228: 1331, 229: 1352, 230: 67, 231: 914, 232: 1396, 233: 623, 234: 890, 235: 911, 236: 593, 237: 1401, 238: 926, 239: 1291, 240: 955, 241: 770, 242: 484, 243: 847, 244: 979, 245: 1135, 246: 1066, 247: 445, 248: 1252, 249: 934, 250: 768, 251: 785, 252: 114, 253: 945, 254: 1380, 255: 659, 256: 680, 257: 995, 258: 253, 259: 981, 260: 985, 261: 513, 262: 1465, 263: 1416, 264: 254, 265: 469, 266: 259, 267: 1225, 268: 746, 269: 1165, 270: 1413, 271: 794, 272: 1420, 273: 621, 274: 1410, 275: 1222, 276: 352, 277: 1116, 278: 146, 279: 8, 280: 1394, 281: 1191, 282: 1305, 283: 1009, 284: 906, 285: 358, 286: 1110, 287: 372, 288: 749, 289: 346, 290: 699, 291: 1322, 292: 1177, 293: 712, 294: 1365, 295: 653, 296: 160, 297: 1149, 298: 113, 299: 1385, 300: 49, 301: 731, 302: 604, 303: 1289, 304: 459, 305: 1285, 306: 354, 307: 585, 308: 458, 309: 1249, 310: 505, 311: 1282, 312: 201, 313: 1389, 314: 1084, 315: 1209, 316: 594, 317: 188, 318: 997, 319: 90, 320: 1339, 321: 726, 322: 1208, 323: 248, 324: 839, 325: 1324, 326: 6, 327: 1128, 328: 1428, 329: 1461, 330: 1029, 331: 856, 332: 1341, 333: 1044, 334: 174, 335: 686, 336: 1440, 337: 1361, 338: 747, 339: 1412, 340: 349, 341: 1144, 342: 452, 343: 476, 344: 1265, 345: 342, 346: 701, 347: 1140, 348: 494, 349: 1088, 350: 314, 351: 405, 352: 1070, 353: 183, 354: 235, 355: 607, 356: 1131, 357: 943, 358: 1387, 359: 984, 360: 379, 361: 242, 362: 1359, 363: 1304, 364: 1006, 365: 1182, 366: 1025, 367: 1035, 368: 163, 369: 226, 370: 239, 371: 462, 372: 266, 373: 804, 374: 1130, 375: 329, 376: 1024, 377: 1403, 378: 141, 379: 1139, 380: 504, 381: 819, 382: 932, 383: 100, 384: 543, 385: 553, 386: 88, 387: 1016, 388: 1280, 389: 1142, 390: 993, 391: 1228, 392: 1467, 393: 251, 394: 925, 395: 764, 396: 1031, 397: 46, 398: 775, 399: 1263, 400: 795, 401: 962, 402: 104, 403: 754, 404: 345, 405: 698, 406: 1194, 407: 424, 408: 1462, 409: 124, 410: 662, 411: 1112, 412: 902, 413: 1246, 414: 990, 415: 1251, 416: 910, 417: 591, 418: 428, 419: 1171, 420: 443, 421: 526, 422: 937, 423: 280, 424: 1037, 425: 510, 426: 1278, 427: 151, 428: 1255, 429: 1061, 430: 83, 431: 337, 432: 1187, 433: 415, 434: 629, 435: 687, 436: 466, 437: 720, 438: 538, 439: 789, 440: 468, 441: 1220, 442: 202, 443: 1358, 444: 77, 445: 580, 446: 1342, 447: 1096, 448: 541, 449: 1343, 450: 751, 451: 1372, 452: 584, 453: 564, 454: 639, 455: 1256, 456: 665, 457: 1377, 458: 797, 459: 707, 460: 820, 461: 721, 462: 1200, 463: 1281, 464: 1114, 465: 436, 466: 548, 467: 137, 468: 759, 469: 227, 470: 1466, 471: 456, 472: 692, 473: 704, 474: 1424, 475: 681, 476: 208, 477: 863, 478: 1290, 479: 663, 480: 975, 481: 1049, 482: 74, 483: 404, 484: 192, 485: 1022, 486: 222, 487: 1099, 488: 293, 489: 512, 490: 498, 491: 930, 492: 1415, 493: 919, 494: 716, 495: 1244, 496: 1141, 497: 1332, 498: 855, 499: 1126, 500: 125, 501: 657, 502: 1308, 503: 1019, 504: 1435, 505: 1204, 506: 891, 507: 116, 508: 1268, 509: 1210, 510: 641, 511: 566, 512: 572, 513: 886, 514: 652, 515: 1087, 516: 292, 517: 84, 518: 1463, 519: 958, 520: 980, 521: 1348, 522: 1148, 523: 1090, 524: 964, 525: 960, 526: 86, 527: 1232, 528: 719, 529: 1134, 530: 777, 531: 33, 532: 790, 533: 722, 534: 216, 535: 1178, 536: 348, 537: 341, 538: 57, 539: 921, 540: 120, 541: 497, 542: 805, 543: 1064, 544: 250, 545: 667, 546: 1329, 547: 180, 548: 214, 549: 1357, 550: 1457, 551: 1238, 552: 1091, 553: 674, 554: 247, 555: 1277, 556: 755, 557: 781, 558: 1181, 559: 393, 560: 194, 561: 842, 562: 909, 563: 1362, 564: 816, 565: 1471, 566: 1414, 567: 732, 568: 536, 569: 291, 570: 357, 571: 474, 572: 1458, 573: 69, 574: 221, 575: 961, 576: 834, 577: 483, 578: 684, 579: 331, 580: 1330, 581: 373, 582: 618, 583: 691, 584: 381, 585: 638, 586: 1296, 587: 246, 588: 1432, 589: 717, 590: 592, 591: 1441, 592: 127, 593: 44, 594: 654, 595: 29, 596: 350, 597: 154, 598: 1353, 599: 355, 600: 1294, 601: 968, 602: 1012, 603: 1404, 604: 390, 605: 929, 606: 673, 607: 147, 608: 1393, 609: 974, 610: 312, 611: 447, 612: 286, 613: 957, 614: 1419, 615: 1052, 616: 533, 617: 1320, 618: 103, 619: 433, 620: 1183, 621: 13, 622: 844, 623: 61, 624: 461, 625: 500, 626: 612, 627: 434, 628: 1121, 629: 1164, 630: 1115, 631: 725, 632: 1104, 633: 264, 634: 290, 635: 656, 636: 285, 637: 1053, 638: 565, 639: 419, 640: 1159, 641: 473, 642: 1065, 643: 1207, 644: 1425, 645: 880, 646: 66, 647: 388, 648: 225, 649: 884, 650: 233, 651: 529, 652: 402, 653: 162, 654: 170, 655: 1132, 656: 444, 657: 756, 658: 895, 659: 515, 660: 1338, 661: 1179, 662: 134, 663: 171, 664: 874, 665: 1356, 666: 1469, 667: 79, 668: 936, 669: 514, 670: 130, 671: 1166, 672: 956, 673: 742, 674: 48, 675: 145, 676: 613, 677: 240, 678: 1018, 679: 1340, 680: 135, 681: 121, 682: 305, 683: 1146, 684: 1036, 685: 1407, 686: 472, 687: 475, 688: 439, 689: 1175, 690: 65, 691: 1021, 692: 479, 693: 54, 694: 1213, 695: 200, 696: 784, 697: 55, 698: 1007, 699: 190, 700: 101, 701: 1464, 702: 1026, 703: 1111, 704: 1219, 705: 528, 706: 894, 707: 581, 708: 1027, 709: 1270, 710: 1229, 711: 270, 712: 711, 713: 1011, 714: 177, 715: 815, 716: 1383, 717: 32, 718: 953, 719: 386, 720: 569, 721: 105, 722: 615, 723: 1174, 724: 488, 725: 1002, 726: 34, 727: 45, 728: 1015, 729: 1449, 730: 544, 731: 523, 732: 301, 733: 1055, 734: 362, 735: 525, 736: 489, 737: 1097, 738: 1273, 739: 217, 740: 1386, 741: 324, 742: 487, 743: 1230, 744: 1328, 745: 743, 746: 1117, 747: 1153, 748: 996, 749: 1446, 750: 1284, 751: 562, 752: 733, 753: 1236, 754: 643, 755: 1003, 756: 1354, 757: 1108, 758: 916, 759: 573, 760: 169, 761: 1283, 762: 727, 763: 967, 764: 168, 765: 204, 766: 1101, 767: 58, 768: 1287, 769: 678, 770: 1227, 771: 1337, 772: 848, 773: 1059, 774: 714, 775: 1315, 776: 883, 777: 326, 778: 82, 779: 852, 780: 363, 781: 762, 782: 457, 783: 256, 784: 651, 785: 1057, 786: 353, 787: 506, 788: 395, 789: 241, 790: 588, 791: 940, 792: 920, 793: 1316, 794: 320, 795: 882, 796: 1267, 797: 432, 798: 558, 799: 1423, 800: 117, 801: 38, 802: 905, 803: 606, 804: 897, 805: 98, 806: 206, 807: 24, 808: 51, 809: 1405, 810: 1221, 811: 634, 812: 1032, 813: 1417, 814: 281, 815: 107, 816: 496, 817: 333, 818: 1334, 819: 826, 820: 893, 821: 300, 822: 1028, 823: 374, 824: 1160, 825: 482, 826: 715, 827: 833, 828: 441, 829: 907, 830: 1429, 831: 611, 832: 757, 833: 808, 834: 73, 835: 1442, 836: 1438, 837: 822, 838: 228, 839: 4, 840: 182, 841: 524, 842: 316, 843: 846, 844: 199, 845: 245, 846: 851, 847: 330, 848: 426, 849: 1094, 850: 545, 851: 287, 852: 1206, 853: 236, 854: 275, 855: 1198, 856: 112, 857: 774, 858: 1460, 859: 328, 860: 577, 861: 335, 862: 991, 863: 1364, 864: 617, 865: 1147, 866: 1199, 867: 508, 868: 1374, 869: 1274, 870: 1017, 871: 1433, 872: 387, 873: 602, 874: 758, 875: 931, 876: 378, 877: 203, 878: 298, 879: 1473, 880: 709, 881: 810, 882: 1071, 883: 1258, 884: 5, 885: 788, 886: 748, 887: 1286, 888: 868, 889: 10, 890: 269, 891: 351, 892: 864, 893: 344, 894: 862, 895: 272, 896: 91, 897: 209, 898: 1023, 899: 892, 900: 836, 901: 1436, 902: 1371, 903: 94, 904: 669, 905: 158, 906: 1311, 907: 908, 908: 186, 909: 666, 910: 1295, 911: 583, 912: 987, 913: 821, 914: 829, 915: 696, 916: 877, 917: 867, 918: 193, 919: 220, 920: 1378, 921: 1406, 922: 574, 923: 1318, 924: 262, 925: 521, 926: 178, 927: 322, 928: 15, 929: 274, 930: 70, 931: 922, 932: 917, 933: 827, 934: 670, 935: 1279, 936: 1076, 937: 1242, 938: 1241, 939: 682, 940: 421, 941: 78, 942: 1391, 943: 1072, 944: 39, 945: 978, 946: 396, 947: 609, 948: 1347, 949: 133, 950: 1041, 951: 881, 952: 1020, 953: 1162, 954: 243, 955: 308, 956: 941, 957: 1150, 958: 448, 959: 688, 960: 828, 961: 1382, 962: 813, 963: 871, 964: 952, 965: 1399, 966: 915, 967: 1137, 968: 546, 969: 212, 970: 878, 971: 1345, 972: 807, 973: 1163, 974: 131, 975: 532, 976: 339, 977: 904, 978: 619, 979: 590, 980: 97, 981: 741, 982: 640, 983: 988, 984: 1390, 985: 369, 986: 866, 987: 869, 988: 1319, 989: 143, 990: 85, 991: 1004, 992: 649, 993: 901, 994: 637, 995: 1336, 996: 1089, 997: 1176, 998: 778, 999: 87, 1000: 411, 1001: 403, 1002: 360, 1003: 282, 1004: 1363, 1005: 1427, 1006: 1129, 1007: 760, 1008: 1047, 1009: 635, 1010: 297, 1011: 949, 1012: 1470, 1013: 697, 1014: 425, 1015: 1030, 1016: 779, 1017: 1309, 1018: 1245, 1019: 1243, 1020: 1451, 1021: 752, 1022: 658, 1023: 946, 1024: 366, 1025: 1271, 1026: 1226, 1027: 954, 1028: 575, 1029: 218}

In [74]:
#print(new_dist[204])

In [75]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
        print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

0   1298   1   4   0   4
1   1445   0   0   5   6
2   1409   0   1   4   4
3   1202   3   2   0   7
4   1093   1   2   2   9
5   1233   0   2   3   5
6   938   0   0   5   6
7   695   0   0   5   5
8   40   4   1   0   8
9   1443   0   3   2   7
10   1186   5   0   0   7
11   689   0   0   5   5
12   126   5   0   0   9
13   321   3   2   0   5
14   64   5   0   0   6
15   887   0   2   3   6
16   824   0   0   5   6
17   165   2   3   0   5
18   912   0   1   4   7
19   1100   4   0   1   10
20   1073   5   0   0   5
21   630   0   5   0   5
22   1381   0   1   4   6
23   1272   2   2   1   10
24   1151   3   2   0   5
25   22   5   0   0   7
26   1086   5   0   0   9
27   605   2   1   2   6
28   1224   2   2   1   9
29   1369   0   1   4   6
30   1033   4   1   0   8
31   9   4   1   0   6
32   1120   4   1   0   8
33   460   0   2   3   8
34   1000   0   3   2   9
35   560   0   3   2   7
36   516   1   2   2   9
37   527   0   1   4   8
38   128   5   0   0   8
39   903   0   1   4   5
40   1074   5   0   0   7
41   791   0   1   4   4
42   115   5   0   0   5
43   535   0   5   0   8
44   106   5   0   0   9
45   132   5   0   0   6
46   982   0   1   4   4
47   1400   0   0   5   5
48   586   1   4   0   3
49   1454   0   0   5   7
50   334   4   1   0   6
51   418   0   3   2   4
52   935   0   3   2   5
53   189   5   0   0   7
54   1107   5   0   0   4
55   1375   0   1   4   5
56   861   0   1   4   5
57   610   1   4   0   7
58   857   0   0   5   5
59   315   5   0   0   10
60   1350   0   0   5   6
61   1307   1   4   0   5
62   391   5   0   0   8
63   1214   5   0   0   6
64   56   5   0   0   8
65   1452   0   0   5   7
66   289   5   0   0   8
67   782   0   1   4   5
68   3   4   1   0   7
69   1158   3   2   0   8
70   1247   1   4   0   4
71   18   5   0   0   9
72   207   5   0   0   7
73   1152   4   1   0   5
74   1276   1   1   3   9
75   705   0   0   5   8
76   1013   3   2   0   6
77   885   0   0   5   7
78   1046   4   1   0   10
79   229   4   0   1   10
80   1349   0   0   5   5
81   60   5   0   0   9
82   1418   0   4   1   10
83   1216   1   3   1   4
84   976   0   1   4   5
85   252   3   2   0   6
86   950   0   0   5   10
87   1138   2   3   0   7
88   700   0   0   5   11
89   306   5   0   0   5
90   1005   4   1   0   6
91   25   5   0   0   5
92   1275   3   1   1   5
93   845   0   1   4   6
94   53   5   0   0   10
95   913   0   1   4   7
96   1431   0   0   5   7
97   793   0   0   5   5
98   671   0   1   4   6
99   924   0   0   5   6
100   406   4   1   0   5
101   19   4   1   0   9
102   1212   5   0   0   9
103   831   0   1   4   6
104   1167   5   0   0   10
105   530   2   2   1   9
106   858   0   1   4   6
107   753   0   3   2   5
108   783   0   3   2   5
109   1426   0   0   5   6
110   1260   1   2   2   5
111   787   0   0   5   5
112   1472   0   0   5   5
113   636   1   4   0   6
114   455   0   4   1   5
115   309   5   0   0   5
116   1082   4   1   0   5
117   495   0   3   2   5
118   294   3   2   0   6
119   485   2   3   0   5
120   854   0   1   4   6
121   1297   0   2   3   6
122   11   5   0   0   9
123   1145   5   0   0   6
124   823   0   1   4   5
125   1346   0   1   4   8
126   471   0   2   3   7
127   1143   5   0   0   10
128   622   1   3   1   6
129   80   5   0   0   4
130   205   5   0   0   9
131   231   5   0   0   10
132   215   5   0   0   11
133   540   2   3   0   4
134   555   0   4   1   6
135   276   5   0   0   7
136   359   5   0   0   13
137   384   5   0   0   6
138   196   5   0   0   9
139   1085   5   0   0   6
140   542   2   3   0   5
141   296   5   0   0   6
142   597   0   5   0   6
143   446   1   4   0   8
144   389   5   0   0   6
145   1266   0   4   1   7
146   43   4   0   1   9
147   1302   2   3   0   9
148   1321   0   1   4   7
149   1373   0   0   5   4
150   1106   4   1   0   5
151   502   1   4   0   4
152   1248   2   3   0   9
153   1102   3   2   0   5
154   408   5   0   0   8
155   414   5   0   0   5
156   142   5   0   0   7
157   492   0   5   0   7
158   501   2   1   2   11
159   518   0   4   1   6
160   260   4   1   0   7
161   41   5   0   0   10
162   972   0   1   4   4
163   537   0   5   0   4
164   442   0   5   0   7
165   818   0   0   5   5
166   238   3   2   0   5
167   364   3   2   0   7
168   595   0   5   0   5
169   463   0   4   1   2
170   75   5   0   0   5
171   1170   4   1   0   8
172   801   0   1   4   11
173   1397   0   0   5   6
174   1180   5   0   0   7
175   1313   1   3   1   8
176   1190   5   0   0   8
177   449   0   4   1   5
178   99   5   0   0   9
179   838   0   1   4   5
180   176   5   0   0   7
181   1317   3   1   1   9
182   47   5   0   0   6
183   1156   4   1   0   7
184   879   0   0   5   5
185   166   5   0   0   6
186   258   4   1   0   8
187   664   0   3   2   6
188   392   2   3   0   5
189   327   5   0   0   9
190   417   1   3   1   6
191   1189   5   0   0   5
192   303   5   0   0   6
193   1172   5   0   0   8
194   744   0   0   5   7
195   1231   1   3   1   6
196   317   4   1   0   8
197   440   3   1   1   7
198   507   0   5   0   4
199   139   3   1   1   9
200   900   0   2   3   4
201   249   5   0   0   6
202   723   0   1   4   7
203   1450   0   1   4   6
204   1264   0   4   1   3
205   167   5   0   0   6
206   710   0   0   5   5
207   398   5   0   0   8
208   486   3   2   0   10
209   1051   4   1   0   7
210   1312   1   4   0   7
211   1203   5   0   0   10
212   771   0   0   5   5
213   798   0   1   4   6
214   685   0   2   3   8
215   21   5   0   0   8
216   450   1   1   3   6
217   122   5   0   0   5
218   959   0   1   4   8
219   27   5   0   0   4
220   454   2   2   1   6
221   278   5   0   0   9
222   172   5   0   0   10
223   59   5   0   0   6
224   951   0   1   4   6
225   614   0   5   0   6
226   875   0   0   5   5
227   1235   1   4   0   5
228   1331   0   2   3   5
229   1352   0   0   5   7
230   67   2   3   0   9
231   914   0   1   4   5
232   1396   0   0   5   6
233   623   0   4   1   3
234   890   0   1   4   5
235   911   0   0   5   6
236   593   2   3   0   7
237   1401   0   0   5   4
238   926   0   0   5   7
239   1291   2   2   1   8
240   955   0   0   5   5
241   770   0   1   4   4
242   484   1   2   2   9
243   847   0   0   5   7
244   979   0   0   5   5
245   1135   5   0   0   4
246   1066   5   0   0   8
247   445   2   3   0   8
248   1252   0   3   2   5
249   934   0   1   4   5
250   768   0   2   3   7
251   785   0   0   5   4
252   114   3   1   1   7
253   945   0   0   5   6
254   1380   2   1   2   8
255   659   0   0   5   6
256   680   0   0   5   7
257   995   0   1   4   3
258   253   5   0   0   5
259   981   0   0   5   4
260   985   0   0   5   3
261   513   0   3   2   5
262   1465   0   0   5   7
263   1416   0   1   4   9
264   254   5   0   0   4
265   469   3   2   0   9
266   259   5   0   0   8
267   1225   0   4   1   4
268   746   0   1   4   5
269   1165   4   1   0   6
270   1413   0   0   5   5
271   794   0   2   3   7
272   1420   0   1   4   9
273   621   0   3   2   5
274   1410   0   0   5   5
275   1222   1   4   0   3
276   352   5   0   0   8
277   1116   5   0   0   6
278   146   4   1   0   4
279   8   5   0   0   6
280   1394   0   0   5   7
281   1191   5   0   0   6
282   1305   0   5   0   5
283   1009   5   0   0   10
284   906   0   0   5   5
285   358   5   0   0   9
286   1110   2   3   0   4
287   372   5   0   0   7
288   749   0   0   5   4
289   346   4   1   0   6
290   699   0   0   5   4
291   1322   0   1   4   7
292   1177   5   0   0   8
293   712   0   2   3   8
294   1365   0   0   5   5
295   653   0   0   5   7
296   160   5   0   0   5
297   1149   5   0   0   6
298   113   3   2   0   5
299   1385   0   1   4   4
300   49   5   0   0   2
301   731   0   2   3   7
302   604   0   4   1   5
303   1289   0   2   3   5
304   459   0   4   1   3
305   1285   1   4   0   5
306   354   5   0   0   9
307   585   2   3   0   4
308   458   0   5   0   4
309   1249   2   2   1   11
310   505   2   3   0   9
311   1282   0   5   0   4
312   201   5   0   0   11
313   1389   0   1   4   5
314   1084   1   4   0   5
315   1209   5   0   0   12
316   594   1   4   0   5
317   188   2   2   1   9
318   997   0   0   5   6
319   90   5   0   0   8
320   1339   0   0   5   8
321   726   0   0   5   6
322   1208   3   2   0   4
323   248   4   1   0   6
324   839   0   1   4   6
325   1324   0   0   5   5
326   6   5   0   0   6
327   1128   4   0   1   9
328   1428   0   1   4   7
329   1461   0   0   5   5
330   1029   4   1   0   9
331   856   0   0   5   4
332   1341   0   1   4   5
333   1044   5   0   0   11
334   174   4   1   0   5
335   686   0   1   4   7
336   1440   0   2   3   8
337   1361   0   0   5   8
338   747   0   1   4   6
339   1412   0   1   4   4
340   349   4   1   0   7
341   1144   4   1   0   5
342   452   0   3   2   5
343   476   0   4   1   4
344   1265   0   4   1   5
345   342   4   1   0   8
346   701   0   1   4   5
347   1140   3   2   0   12
348   494   0   5   0   6
349   1088   4   1   0   8
350   314   4   1   0   6
351   405   3   2   0   6
352   1070   5   0   0   5
353   183   5   0   0   9
354   235   5   0   0   9
355   607   0   4   1   6
356   1131   3   2   0   8
357   943   2   0   3   9
358   1387   0   2   3   6
359   984   0   0   5   5
360   379   4   1   0   7
361   242   4   1   0   8
362   1359   0   0   5   4
363   1304   1   4   0   6
364   1006   5   0   0   10
365   1182   4   1   0   7
366   1025   4   1   0   6
367   1035   5   0   0   8
368   163   4   1   0   8
369   226   4   1   0   6
370   239   3   2   0   8
371   462   1   3   1   4
372   266   4   1   0   5
373   804   0   0   5   5
374   1130   3   2   0   5
375   329   4   1   0   7
376   1024   4   1   0   5
377   1403   0   0   5   4
378   141   5   0   0   5
379   1139   2   3   0   8
380   504   0   5   0   7
381   819   0   0   5   5
382   932   0   1   4   4
383   100   4   0   1   9
384   543   4   1   0   7
385   553   0   3   2   6
386   88   3   2   0   5
387   1016   4   1   0   7

388   1280   0   4   1   5
389   1142   5   0   0   7
390   993   0   2   3   7
391   1228   0   4   1   5
392   1467   0   2   3   8
393   251   5   0   0   7
394   925   0   0   5   9
395   764   0   0   5   6
396   1031   2   3   0   8
397   46   5   0   0   6
398   775   0   2   3   5
399   1263   1   3   1   5
400   795   0   0   5   7
401   962   0   0   5   3
402   104   3   2   0   8
403   754   0   0   5   5
404   345   5   0   0   6
405   698   0   1   4   6
406   1194   5   0   0   3
407   424   0   1   4   10
408   1462   0   2   3   8
409   124   5   0   0   7
410   662   0   3   2   6
411   1112   3   2   0   5
412   902   0   2   3   7
413   1246   0   4   1   8
414   990   0   1   4   9
415   1251   2   2   1   7
416   910   0   0   5   7
417   591   0   2   3   7
418   428   1   3   1   9
419   1171   5   0   0   8
420   443   1   4   0   6
421   526   2   1   2   7
422   937   1   2   2   9
423   280   5   0   0   6
424   1037   3   2   0   5
425   510   0   5   0   5
426   1278   1   4   0   5
427   151   3   2   0   6
428   1255   0   3   2   6
429   1061   5   0   0   7
430   83   4   1   0   7
431   337   4   1   0   8
432   1187   3   2   0   7
433   415   5   0   0   6
434   629   0   5   0   5
435   687   0   1   4   6
436   466   2   3   0   6
437   720   0   1   4   4
438   538   1   4   0   5
439   789   0   0   5   6
440   468   0   3   2   8
441   1220   1   4   0   4
442   202   5   0   0   6
443   1358   0   0   5   5
444   77   4   1   0   4
445   580   1   2   2   6
446   1342   0   0   5   5
447   1096   5   0   0   6
448   541   2   3   0   6
449   1343   1   1   3   9
450   751   0   0   5   7
451   1372   0   1   4   5
452   584   0   1   4   5
453   564   1   3   1   8
454   639   1   3   1   9
455   1256   0   1   4   8
456   665   0   0   5   8
457   1377   0   0   5   6
458   797   0   1   4   6
459   707   0   0   5   6
460   820   0   0   5   6
461   721   0   0   5   3
462   1200   3   2   0   6
463   1281   1   4   0   5
464   1114   5   0   0   5
465   436   1   3   1   7
466   548   1   3   1   6
467   137   5   0   0   5
468   759   2   2   1   9
469   227   5   0   0   6
470   1466   0   0   5   6
471   456   2   3   0   6
472   692   0   0   5   5
473   704   0   0   5   7
474   1424   0   1   4   5
475   681   0   0   5   9
476   208   5   0   0   7
477   863   0   0   5   7
478   1290   1   1   3   9
479   663   0   1   4   5
480   975   0   1   4   4
481   1049   5   0   0   9
482   74   5   0   0   7
483   404   4   1   0   10
484   192   5   0   0   7
485   1022   5   0   0   8
486   222   5   0   0   4
487   1099   4   1   0   8
488   293   5   0   0   6
489   512   2   3   0   6
490   498   1   2   2   6
491   930   0   1   4   5
492   1415   0   0   5   7
493   919   0   0   5   7
494   716   0   3   2   8
495   1244   0   4   1   6
496   1141   4   1   0   6
497   1332   0   0   5   6
498   855   0   0   5   6
499   1126   3   2   0   8
500   125   5   0   0   10
501   657   0   0   5   7
502   1308   0   5   0   4
503   1019   5   0   0   6
504   1435   0   1   4   3
505   1204   5   0   0   9
506   891   0   0   5   7
507   116   5   0   0   5
508   1268   1   4   0   5
509   1210   1   4   0   7
510   641   2   2   1   11
511   566   1   4   0   3
512   572   0   3   2   6
513   886   0   1   4   6
514   652   0   0   5   4
515   1087   3   2   0   5
516   292   2   3   0   5
517   84   5   0   0   6
518   1463   0   1   4   6
519   958   0   0   5   10
520   980   0   3   2   5
521   1348   0   0   5   5
522   1148   5   0   0   3
523   1090   5   0   0   9
524   964   0   1   4   6
525   960   0   2   3   10
526   86   4   1   0   4
527   1232   1   4   0   5
528   719   0   0   5   3
529   1134   5   0   0   5
530   777   0   3   2   7
531   33   5   0   0   7
532   790   0   0   5   6
533   722   0   2   3   4
534   216   5   0   0   7
535   1178   5   0   0   9
536   348   4   1   0   8
537   341   3   1   1   8
538   57   1   4   0   7
539   921   0   0   5   8
540   120   4   1   0   5
541   497   1   1   3   5
542   805   0   0   5   6
543   1064   4   1   0   10
544   250   4   1   0   11
545   667   0   0   5   6
546   1329   0   2   3   7
547   180   2   3   0   12
548   214   5   0   0   9
549   1357   0   0   5   6
550   1457   0   0   5   10
551   1238   0   5   0   6
552   1091   5   0   0   6
553   674   3   0   2   11
554   247   5   0   0   6
555   1277   1   4   0   6
556   755   0   0   5   6
557   781   0   0   5   5
558   1181   5   0   0   6
559   393   5   0   0   10
560   194   5   0   0   5
561   842   0   0   5   8
562   909   0   0   5   5
563   1362   0   0   5   5
564   816   0   0   5   4
565   1471   0   2   3   10
566   1414   0   1   4   6
567   732   0   0   5   7
568   536   2   1   2   6
569   291   4   1   0   5
570   357   5   0   0   7
571   474   0   4   1   5
572   1458   0   1   4   6
573   69   5   0   0   5
574   221   5   0   0   6
575   961   0   2   3   9
576   834   0   0   5   4
577   483   3   1   1   6
578   684   0   0   5   6
579   331   5   0   0   6
580   1330   0   0   5   7
581   373   4   0   1   8
582   618   0   3   2   7
583   691   0   1   4   9
584   381   4   1   0   7
585   638   1   2   2   8
586   1296   1   1   3   7
587   246   4   1   0   5
588   1432   0   0   5   5
589   717   0   1   4   6
590   592   0   5   0   7
591   1441   0   0   5   5
592   127   5   0   0   4
593   44   4   1   0   7
594   654   1   3   1   22
595   29   5   0   0   6
596   350   5   0   0   5
597   154   5   0   0   5
598   1353   0   1   4   6
599   355   4   1   0   7
600   1294   0   3   2   6
601   968   0   1   4   4
602   1012   5   0   0   6
603   1404   0   0   5   5
604   390   4   1   0   7
605   929   0   0   5   3
606   673   0   0   5   5
607   147   3   2   0   7
608   1393   0   0   5   7
609   974   0   0   5   8
610   312   4   1   0   7
611   447   1   4   0   3
612   286   2   3   0   7
613   957   0   0   5   6
614   1419   1   0   4   10
615   1052   5   0   0   8
616   533   1   3   1   7
617   1320   0   3   2   7
618   103   5   0   0   8
619   433   0   2   3   5
620   1183   4   1   0   7
621   13   5   0   0   5
622   844   0   0   5   5
623   61   5   0   0   7
624   461   0   5   0   5
625   500   2   2   1   6
626   612   1   3   1   5
627   434   1   4   0   7
628   1121   4   0   1   12
629   1164   2   3   0   7
630   1115   4   1   0   5
631   725   0   0   5   4
632   1104   4   1   0   6
633   264   5   0   0   5
634   290   5   0   0   10
635   656   0   0   5   5
636   285   4   1   0   8
637   1053   5   0   0   4
638   565   0   3   2   10
639   419   1   3   1   5
640   1159   4   0   1   11
641   473   1   4   0   4
642   1065   3   2   0   6
643   1207   5   0   0   6
644   1425   0   0   5   6
645   880   0   1   4   5
646   66   5   0   0   6
647   388   4   1   0   7
648   225   3   2   0   4
649   884   0   0   5   6
650   233   5   0   0   7
651   529   1   4   0   4
652   402   5   0   0   7
653   162   5   0   0   5
654   170   4   1   0   6
655   1132   5   0   0   10
656   444   1   2   2   6
657   756   0   1   4   4
658   895   0   0   5   6
659   515   0   2   3   5
660   1338   0   0   5   6
661   1179   4   1   0   6
662   134   5   0   0   8
663   171   3   2   0   4
664   874   0   0   5   5
665   1356   0   1   4   4
666   1469   0   1   4   5
667   79   4   1   0   6
668   936   0   1   4   6
669   514   0   4   1   5
670   130   5   0   0   6
671   1166   4   1   0   5
672   956   1   0   4   10
673   742   0   0   5   5
674   48   5   0   0   6
675   145   3   2   0   7
676   613   0   4   1   5
677   240   4   1   0   6
678   1018   4   1   0   7
679   1340   0   0   5   5
680   135   5   0   0   4
681   121   4   0   1   10
682   305   4   1   0   5
683   1146   5   0   0   4
684   1036   4   1   0   5
685   1407   0   1   4   8
686   472   2   1   2   7
687   475   0   5   0   8
688   439   1   3   1   6
689   1175   5   0   0   8
690   65   4   1   0   7
691   1021   2   2   1   11
692   479   0   3   2   7
693   54   5   0   0   7
694   1213   4   0   1   7
695   200   5   0   0   7
696   784   0   2   3   6
697   55   5   0   0   6
698   1007   5   0   0   5
699   190   4   1   0   8
700   101   4   0   1   9
701   1464   0   0   5   7
702   1026   5   0   0   4
703   1111   4   1   0   8
704   1219   3   1   1   7
705   528   1   4   0   7
706   894   0   1   4   7
707   581   0   4   1   5
708   1027   5   0   0   8
709   1270   3   1   1   8
710   1229   0   4   1   3
711   270   5   0   0   9
712   711   0   0   5   5
713   1011   3   1   1   7
714   177   5   0   0   6
715   815   1   0   4   10
716   1383   0   2   3   9
717   32   5   0   0   7
718   953   0   0   5   5
719   386   5   0   0   5
720   569   1   4   0   7
721   105   4   1   0   5
722   615   0   4   1   6
723   1174   3   2   0   10
724   488   0   4   1   4
725   1002   5   0   0   10
726   34   4   1   0   8
727   45   4   1   0   7
728   1015   5   0   0   6
729   1449   0   0   5   5
730   544   0   4   1   6
731   523   2   1   2   10
732   301   2   1   2   9
733   1055   5   0   0   4
734   362   3   2   0   7
735   525   1   3   1   5
736   489   0   5   0   7
737   1097   4   1   0   5
738   1273   0   3   2   6
739   217   5   0   0   9
740   1386   0   0   5   5
741   324   5   0   0   8
742   487   0   3   2   6
743   1230   1   3   1   6
744   1328   0   1   4   5
745   743   0   0   5   8
746   1117   4   0   1   7
747   1153   3   2   0   10
748   996   0   0   5   9
749   1446   0   0   5   3
750   1284   1   4   0   7

751   562   2   3   0   8
752   733   0   1   4   10
753   1236   0   3   2   5
754   643   0   0   5   6
755   1003   5   0   0   8
756   1354   0   0   5   5
757   1108   4   1   0   9
758   916   0   2   3   7
759   573   0   4   1   5
760   169   5   0   0   5
761   1283   1   3   1   7
762   727   0   1   4   3
763   967   0   0   5   6
764   168   5   0   0   2
765   204   3   2   0   5
766   1101   3   2   0   6
767   58   4   1   0   7
768   1287   1   2   2   6
769   678   0   1   4   8
770   1227   0   5   0   4
771   1337   0   0   5   5
772   848   1   0   4   7
773   1059   4   1   0   8
774   714   0   0   5   5
775   1315   0   3   2   5
776   883   0   0   5   5
777   326   5   0   0   6
778   82   4   1   0   5
779   852   0   2   3   7
780   363   5   0   0   8
781   762   0   2   3   9
782   457   0   4   1   2
783   256   2   3   0   6
784   651   0   2   3   7
785   1057   5   0   0   9
786   353   5   0   0   6
787   506   1   3   1   5
788   395   4   1   0   4
789   241   5   0   0   6
790   588   0   5   0   6
791   940   0   2   3   8
792   920   0   1   4   4
793   1316   2   2   1   8
794   320   5   0   0   8
795   882   0   0   5   8
796   1267   0   3   2   5
797   432   1   2   2   7
798   558   3   1   1   6
799   1423   0   0   5   8
800   117   1   4   0   6
801   38   3   1   1   8
802   905   0   0   5   7
803   606   0   4   1   6
804   897   0   2   3   6
805   98   3   2   0   10
806   206   5   0   0   5
807   24   5   0   0   5
808   51   4   1   0   5
809   1405   0   0   5   7
810   1221   1   4   0   5
811   634   1   4   0   5
812   1032   5   0   0   7
813   1417   0   0   5   6
814   281   3   2   0   7
815   107   3   2   0   7
816   496   4   1   0   6
817   333   5   0   0   7
818   1334   0   2   3   5
819   826   0   0   5   6
820   893   0   0   5   5
821   300   5   0   0   2
822   1028   4   1   0   8
823   374   2   3   0   6
824   1160   5   0   0   8
825   482   1   1   3   8
826   715   0   1   4   6
827   833   0   0   5   5
828   441   2   3   0   5
829   907   0   1   4   5
830   1429   0   4   1   8
831   611   2   3   0   8
832   757   0   2   3   6
833   808   0   0   5   5
834   73   5   0   0   8
835   1442   0   1   4   7
836   1438   0   0   5   5
837   822   0   0   5   4
838   228   4   1   0   8
839   4   5   0   0   8
840   182   5   0   0   6
841   524   3   1   1   6
842   316   4   1   0   8
843   846   0   0   5   5
844   199   4   1   0   9
845   245   4   1   0   6
846   851   1   2   2   8
847   330   4   1   0   6
848   426   1   4   0   6
849   1094   5   0   0   5
850   545   0   3   2   6
851   287   5   0   0   4
852   1206   5   0   0   8
853   236   4   1   0   5
854   275   5   0   0   6
855   1198   3   2   0   7
856   112   3   2   0   9
857   774   0   0   5   4
858   1460   0   1   4   6
859   328   4   1   0   7
860   577   0   5   0   2
861   335   4   1   0   6
862   991   0   0   5   6
863   1364   0   0   5   5
864   617   0   4   1   8
865   1147   4   1   0   7
866   1199   5   0   0   10
867   508   0   5   0   7
868   1374   0   0   5   5
869   1274   0   3   2   6
870   1017   5   0   0   5
871   1433   0   1   4   5
872   387   3   2   0   7
873   602   0   2   3   4
874   758   0   0   5   7
875   931   0   0   5   6
876   378   4   1   0   7
877   203   5   0   0   7
878   298   4   1   0   6
879   1473   0   2   3   7
880   709   0   0   5   5
881   810   0   0   5   5
882   1071   4   1   0   9
883   1258   0   5   0   6
884   5   4   1   0   7
885   788   0   0   5   6
886   748   3   0   2   13
887   1286   2   3   0   4
888   868   0   0   5   7
889   10   4   1   0   9
890   269   4   1   0   8
891   351   5   0   0   7
892   864   0   0   5   6
893   344   5   0   0   8
894   862   0   4   1   8
895   272   5   0   0   6
896   91   5   0   0   6
897   209   4   1   0   5
898   1023   5   0   0   6
899   892   0   0   5   7
900   836   0   1   4   7
901   1436   0   2   3   6
902   1371   0   1   4   8
903   94   5   0   0   10
904   669   0   0   5   6
905   158   5   0   0   7
906   1311   0   5   0   6
907   908   0   0   5   5
908   186   4   1   0   7
909   666   0   2   3   8
910   1295   2   2   1   5
911   583   1   3   1   4
912   987   0   1   4   3
913   821   0   1   4   9
914   829   0   1   4   4
915   696   0   2   3   5
916   877   1   2   2   7
917   867   0   0   5   8
918   193   4   1   0   15
919   220   3   2   0   5
920   1378   0   0   5   6
921   1406   1   2   2   10
922   574   3   1   1   8
923   1318   0   5   0   5
924   262   4   1   0   9
925   521   2   2   1   6
926   178   5   0   0   7
927   322   4   0   1   11
928   15   4   1   0   7
929   274   5   0   0   8
930   70   5   0   0   5
931   922   1   1   3   10
932   917   0   1   4   5
933   827   0   2   3   5
934   670   0   0   5   5
935   1279   0   3   2   5
936   1076   5   0   0   4
937   1242   2   1   2   8
938   1241   0   1   4   7
939   682   0   0   5   5
940   421   1   3   1   6
941   78   2   3   0   6
942   1391   0   1   4   6
943   1072   5   0   0   7
944   39   3   2   0   8
945   978   0   3   2   8
946   396   4   1   0   6
947   609   0   5   0   5
948   1347   0   1   4   5
949   133   5   0   0   8
950   1041   4   1   0   8
951   881   0   0   5   5
952   1020   3   2   0   7
953   1162   4   1   0   9
954   243   4   1   0   10
955   308   1   4   0   7
956   941   0   0   5   5
957   1150   3   2   0   8
958   448   0   5   0   5
959   688   0   2   3   10
960   828   0   0   5   5
961   1382   1   0   4   10
962   813   0   0   5   5
963   871   0   0   5   6
964   952   0   0   5   5
965   1399   0   0   5   9
966   915   0   1   4   5
967   1137   5   0   0   7
968   546   0   4   1   6
969   212   5   0   0   8
970   878   0   0   5   4
971   1345   0   2   3   14
972   807   0   1   4   5
973   1163   4   1   0   9
974   131   4   0   1   12
975   532   2   3   0   7
976   339   4   1   0   6
977   904   0   0   5   7
978   619   1   4   0   5
979   590   0   4   1   5
980   97   5   0   0   8
981   741   0   0   5   7
982   640   0   3   2   7
983   988   0   1   4   6
984   1390   0   3   2   6
985   369   4   1   0   7
986   866   0   0   5   6
987   869   0   0   5   5
988   1319   0   4   1   2
989   143   4   1   0   7
990   85   3   2   0   6
991   1004   5   0   0   6
992   649   2   0   3   8
993   901   0   0   5   5
994   637   4   1   0   8
995   1336   0   2   3   10
996   1089   5   0   0   10
997   1176   5   0   0   6
998   778   0   0   5   5
999   87   5   0   0   4
1000   411   5   0   0   9
1001   403   4   1   0   8
1002   360   5   0   0   7
1003   282   5   0   0   6
1004   1363   0   1   4   8
1005   1427   0   0   5   8
1006   1129   2   3   0   5
1007   760   0   1   4   5
1008   1047   5   0   0   6
1009   635   1   4   0   6
1010   297   2   3   0   9
1011   949   0   0   5   6
1012   1470   0   0   5   4
1013   697   0   2   3   7
1014   425   2   1   2   7
1015   1030   5   0   0   9
1016   779   0   1   4   6
1017   1309   0   5   0   8
1018   1245   1   3   1   6
1019   1243   3   2   0   8
1020   1451   0   0   5   5
1021   752   0   1   4   5
1022   658   0   1   4   7
1023   946   0   0   5   6
1024   366   5   0   0   6
1025   1271   0   5   0   2
1026   1226   1   1   3   7
1027   954   3   0   2   11
1028   575   0   5   0   2
1029   218   4   1   0   8

In [76]:
#neigh_count=[]
#s=0
#for i, v in new_dist.items():
#    c1=0
#    c2=0
 #   c3=0
  #  if int(v) == 1:
   #     c1=c1+1
    #elif int(v) == 2:
     #   c2=c2+1
    #else:
     #   c3=c3+1
    #for x in range(1,5):
        #print(x)
     #   y=new_dist[new_arr2[s][x]]
      #  print(y)
    #s=s+1
        
            
    
#print(i," ",c1," ",c2," ",c3)