In [1]:
import numpy as np 
import pandas as pd
import math

In [2]:
data=pd.read_csv("standard_scale.csv")

In [3]:
data.columns=["id","Class","Left-Weight","Left-Distance","Right-Weight","Right-Distance"]

In [4]:
data["Class"]=pd.factorize(data["Class"])[0] + 1

In [5]:
data.set_index("id", inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 624 entries, 2 to 625
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Class           624 non-null    int64
 1   Left-Weight     624 non-null    int64
 2   Left-Distance   624 non-null    int64
 3   Right-Weight    624 non-null    int64
 4   Right-Distance  624 non-null    int64
dtypes: int64(5)
memory usage: 29.2 KB

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [9]:
train_file_x=X_train.to_csv("aaa.csv")

In [10]:
test_file_x=X_test.to_csv("aaa_test.csv")

In [11]:
train_file_y=Y_train.to_csv("bbb.csv")

In [12]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(436, 5) (188, 5) (436,) (188,)

In [14]:
X_train

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
574      1            5              3             5               4
557      2            5              3             2               2
56       2            1              3             2               1
42       1            1              2             4               2
296      2            3              2             5               1
..     ...          ...            ...           ...             ...
587      2            5              4             3               2
370      1            3              5             4               5
544      1            5              2             4               4
314      1            3              3             3               4
93       1            1              4             4               3

[436 rows x 5 columns]

In [15]:
Y_train

id
574    1
557    2
56     2
42     1
296    2
      ..
587    2
370    1
544    1
314    1
93     1
Name: Class, Length: 436, dtype: int64

In [16]:
gb=X_train.groupby("Class")

In [17]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
574      1            5              3             5               4
42       1            1              2             4               2
263      1            3              1             3               3
269      1            3              1             4               4
41       1            1              2             4               1
..     ...          ...            ...           ...             ...
395      1            4              1             4               5
370      1            3              5             4               5
544      1            5              2             4               4
314      1            3              3             3               4
93       1            1              4             4               3

[200 rows x 5 columns]
2
     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
557      2            5              3             2               2
56       2            1              3             2               1
296      2            3              2             5               1
342      2            3              4             4               2
611      2            5              5             3               1
..     ...          ...            ...           ...             ...
558      2            5              3             2               3
619      2            5              5             4               4
377      2            4              1             1               2
490      2            4              5             3               5
587      2            5              4             3               2

[197 rows x 5 columns]
3
     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
131      3            2              1             2               1
217      3            2              4             4               2
521      3            5              1             5               1
261      3            3              1             3               1
443      3            4              3             4               3
253      3            3              1             1               3
283      3            3              2             2               3
343      3            3              4             4               3
499      3            4              5             5               4
53       3            1              3             1               3
625      3            5              5             5               5
247      3            2              5             5               2
373      3            3              5             5               3
599      3            5              4             5               4
166      3            2              2             4               1
61       3            1              3             3               1
382      3            4              1             2               2
209      3            2              4             2               4
235      3            2              5             2               5
409      3            4              2             2               4
82       3            1              4             2               2
187      3            2              3             3               2
391      3            4              1             4               1
183      3            2              3             2               3
535      3            5              2             2               5
79       3            1              4             1               4
417      3            4              2             4               2
313      3            3              3             3               3
287      3            3              2             3               2
565      3            5              3             3               5
157      3            2              2             2               2
379      3            4              1             1               4
439      3            4              3             3               4
31       3            1              2             2               1
105      3            1              5             1               5
91       3            1              4             4               1
365      3            3              5             3               5
127      3            2              1             1               2
339      3            3              4             3               4

In [18]:
gb.get_group(1)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
574      1            5              3             5               4
42       1            1              2             4               2
263      1            3              1             3               3
269      1            3              1             4               4
41       1            1              2             4               1
..     ...          ...            ...           ...             ...
395      1            4              1             4               5
370      1            3              5             4               5
544      1            5              2             4               4
314      1            3              3             3               4
93       1            1              4             4               3

[200 rows x 5 columns]

In [19]:
class_samples=gb.get_group(1).sample(n=20)
print(class_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
163      1            2              2             3               3
199      1            2              3             5               4
475      1            4              4             5               5
123      1            1              5             5               3
93       1            1              4             4               3
264      1            3              1             3               4
393      1            4              1             4               3
168      1            2              2             4               3
500      1            4              5             5               5
515      1            5              1             3               5
298      1            3              2             5               3
155      1            2              2             1               5
225      1            2              4             5               5
16       1            1              1             4               1
32       1            1              2             2               2
13       1            1              1             3               3
518      1            5              1             4               3
175      1            2              2             5               5
397      1            4              1             5               2
310      1            3              3             2               5

In [20]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>

In [21]:
mean_sum=class_samples["Left-Weight"].mean() + class_samples["Left-Distance"].mean() + class_samples["Right-Weight"].mean() + class_samples["Right-Distance"].mean()

In [22]:
similar_val_1=mean_sum/5
print(similar_val_1)

2.48

In [23]:
class_2_samples=gb.get_group(2).sample(n=20)
print(class_2_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
296      2            3              2             5               1
401      2            4              2             1               1
242      2            2              5             4               2
286      2            3              2             3               1
498      2            4              5             5               3
359      2            3              5             2               4
461      2            4              4             3               1
411      2            4              2             3               1
231      2            2              5             2               1
453      2            4              4             1               3
463      2            4              4             3               3
305      2            3              3             1               5
403      2            4              2             1               3
276      2            3              2             1               1
232      2            2              5             2               2
412      2            4              2             3               2
86       2            1              4             3               1
307      2            3              3             2               2
616      2            5              5             4               1
605      2            5              5             1               5

In [24]:
mean_sum_2=class_2_samples["Left-Weight"].mean() + class_2_samples["Left-Distance"].mean() + class_2_samples["Right-Weight"].mean() + class_2_samples["Right-Distance"].mean()

In [25]:
similar_val_2=mean_sum_2/5
print(similar_val_2)

2.31

In [26]:
class_3_samples=gb.get_group(3).sample(n=20)
print(class_3_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id
127      3            2              1             1               2
82       3            1              4             2               2
157      3            2              2             2               2
61       3            1              3             3               1
382      3            4              1             2               2
409      3            4              2             2               4
261      3            3              1             3               1
131      3            2              1             2               1
391      3            4              1             4               1
373      3            3              5             5               3
166      3            2              2             4               1
313      3            3              3             3               3
183      3            2              3             2               3
625      3            5              5             5               5
253      3            3              1             1               3
599      3            5              4             5               4
365      3            3              5             3               5
521      3            5              1             5               1
287      3            3              2             3               2
443      3            4              3             4               3

In [27]:
mean_sum_3=class_3_samples["Left-Weight"].mean() + class_3_samples["Left-Distance"].mean() + class_3_samples["Right-Weight"].mean() + class_3_samples["Right-Distance"].mean()

In [28]:
similar_val_3=mean_sum_3/5
print(similar_val_3)

2.21

In [29]:
sim_23=abs(similar_val_3 - similar_val_2)
sim_23=sim_23/100
sim_23=1 - sim_23
sim_21=abs(similar_val_1 - similar_val_2)
sim_21=sim_21/100
sim_21=1 - sim_21
sim_13=abs(similar_val_3 - similar_val_1)
sim_13=sim_13/100
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_21)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.999
Similarity between 2 and 1:  0.9983
Similarity between 1 and 3:  0.9973

In [30]:
gb.size()

Class
1    200
2    197
3     39
dtype: int64

In [31]:
m=math.ceil((206+31)/2)

In [32]:
print(m)

119

In [33]:
len(gb)

3

In [34]:
 from sklearn.neighbors import KNeighborsClassifier

In [35]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [36]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [37]:
result=neigh.kneighbors(X_train, return_distance=True)

In [38]:
print(type(result))

<class 'tuple'>

In [39]:
print(result)

(array([[0.        , 1.        , 1.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 1.        , 1.        , 1.41421356],
       ...,
       [0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 1.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        , 1.        , 1.        ]]), array([[  0, 385, 171, 318, 409],
       [  1, 379, 421, 410, 353],
       [  2, 162, 380,  13, 394],
       ...,
       [433,  73,  38, 427, 265],
       [434, 202, 236,  36, 213],
       [435,  39, 239, 329,  95]], dtype=int64))

In [40]:
arr1=result[0]

In [41]:
print(type(arr1))

<class 'numpy.ndarray'>

In [42]:
print(arr1.ndim)

2

In [43]:
arr2=result[1]

In [44]:
print(type(arr2))

<class 'numpy.ndarray'>

In [45]:
print(arr1.ndim)

2

In [46]:
print(arr2)

[[  0 385 171 318 409]
 [  1 379 421 410 353]
 [  2 162 380  13 394]
 ...
 [433  73  38 427 265]
 [434 202 236  36 213]
 [435  39 239 329  95]]

In [47]:
print(arr1)

[[0.         1.         1.         1.         1.41421356]
 [0.         1.         1.         1.         1.        ]
 [0.         1.         1.         1.         1.41421356]
 ...
 [0.         1.         1.         1.         1.        ]
 [0.         1.         1.         1.         1.41421356]
 [0.         1.         1.         1.         1.        ]]

In [48]:
#print(arr1)

In [49]:
print(arr1.size)

2180

In [50]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4

[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.41421356 1.41421356]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4
[0.         1.         1.41421356 1.41421356 1.41421356]   5
[0. 1. 1. 1. 1.]   4
[0.         1.         1.         1.         1.41421356]   4
[0. 1. 1. 1. 1.]   4

In [51]:
print(len(addVal))

436

In [52]:
print(addVal)

[4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 6, 4, 5, 5, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4]

In [53]:
arr3=np.array(addVal)

In [54]:
print(type(arr3))

<class 'numpy.ndarray'>

In [55]:
print(arr3.size)

436

In [56]:
print(arr3)

[4 4 4 4 5 4 4 4 4 4 5 4 4 4 4 5 4 4 4 4 4 6 4 4 4 4 4 5 4 4 4 4 4 5 5 4 4
 4 4 4 4 4 4 4 4 5 4 4 4 4 5 5 4 4 4 4 5 4 5 4 4 4 4 4 4 4 4 4 5 4 4 5 4 4
 4 4 4 5 4 4 4 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 5 4 4 4 4 4 4 4 5 4
 4 4 4 4 4 4 5 4 5 5 5 4 4 4 4 5 4 4 4 4 5 5 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 6 4 4 4 4 5 4 4 4 5 4 4 4 4 4 4 4 4 4 5 5 4 4 4 4
 4 4 6 4 5 5 5 4 4 4 4 4 5 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 5 4 4 4 4
 4 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4
 4 4 5 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 4 5 4 4 4 4 5 4 4 5 5
 4 4 4 4 5 4 5 4 4 5 4 4 5 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4
 4 4 4 4 5 5 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 4 4 4 5 4 4 4 5
 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 5 4 4 4 4 4 5 4 4 4 4 4 4 4 4 5 5 4 4
 4 4 4 4 4 4 5 4 5 4 4 4 4 4 4 5 4 5 4 5 4 4 4 4 4 5 4 4 4]

In [57]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   4
2   4
3   4
4   4
5   5
6   4
7   4
8   4
9   4
10   4
11   5
12   4
13   4
14   4
15   4
16   5
17   4
18   4
19   4
20   4
21   4
22   6
23   4
24   4
25   4
26   4
27   4
28   5
29   4
30   4
31   4
32   4
33   4
34   5
35   5
36   4
37   4
38   4
39   4
40   4
41   4
42   4
43   4
44   4
45   4
46   5
47   4
48   4
49   4
50   4
51   5
52   5
53   4
54   4
55   4
56   4
57   5
58   4
59   5
60   4
61   4
62   4
63   4
64   4
65   4
66   4
67   4
68   4
69   5
70   4
71   4
72   5
73   4
74   4
75   4
76   4
77   4
78   5
79   4
80   4
81   4
82   4
83   4
84   5
85   4
86   4
87   4
88   4
89   4
90   4
91   4
92   4
93   4
94   4
95   4
96   4
97   4
98   5
99   4
100   4
101   4
102   5
103   4
104   4
105   4
106   4
107   4
108   4
109   4
110   5
111   4
112   4
113   4
114   4
115   4
116   4
117   4
118   5
119   4
120   5
121   5
122   5
123   4
124   4
125   4
126   4
127   5
128   4
129   4
130   4
131   4
132   5
133   5
134   4
135   4
136   4
137   4
138   4
139   4
140   4
141   4
142   4
143   5
144   4
145   4
146   4
147   4
148   4
149   4
150   4
151   4
152   4
153   4
154   4
155   4
156   4
157   4
158   4
159   4
160   4
161   6
162   4
163   4
164   4
165   4
166   5
167   4
168   4
169   4
170   5
171   4
172   4
173   4
174   4
175   4
176   4
177   4
178   4
179   4
180   5
181   5
182   4
183   4
184   4
185   4
186   4
187   4
188   6
189   4
190   5
191   5
192   5
193   4
194   4
195   4
196   4
197   4
198   5
199   4
200   5
201   4
202   4
203   4
204   4
205   4
206   4
207   4
208   4
209   4
210   4
211   4
212   4
213   4
214   4
215   4
216   5
217   4
218   5
219   4
220   4
221   4
222   4
223   4
224   4
225   4
226   4
227   4
228   4
229   4
230   6
231   4
232   4
233   4
234   4
235   4
236   4
237   4
238   4
239   4
240   4
241   4
242   4
243   4
244   4
245   4
246   4
247   4
248   4
249   4
250   4
251   4
252   4
253   4
254   4
255   4
256   5
257   4
258   4
259   4
260   4
261   4
262   5
263   4
264   5
265   4
266   4
267   4
268   4
269   4
270   4
271   4
272   4
273   4
274   4
275   4
276   4
277   4
278   4
279   5
280   4
281   4
282   4
283   4
284   4
285   4
286   4
287   5
288   4
289   4
290   4
291   4
292   5
293   4
294   4
295   5
296   5
297   4
298   4
299   4
300   4
301   5
302   4
303   5
304   4
305   4
306   5
307   4
308   4
309   5
310   4
311   4
312   5
313   4
314   4
315   4
316   4
317   4
318   4
319   4
320   4
321   4
322   4
323   4
324   4
325   4
326   4
327   4
328   4
329   4
330   4
331   5
332   4
333   4
334   4
335   4
336   4
337   4
338   5
339   5
340   5
341   4
342   4
343   4
344   4
345   4
346   4
347   4
348   4
349   4
350   4
351   4
352   4
353   4
354   4
355   4
356   5
357   4
358   4
359   4
360   4
361   4
362   4
363   4
364   4
365   4
366   5
367   4
368   4
369   4
370   5
371   4
372   4
373   4
374   4
375   4
376   4
377   4
378   4
379   4
380   4
381   4
382   5
383   4
384   4
385   4
386   4
387   4
388   4
389   5
390   4
391   4
392   4
393   4
394   4
395   5
396   4
397   4
398   4
399   4
400   4
401   4
402   4
403   4
404   5
405   5
406   4
407   4
408   4
409   4
410   4
411   4
412   4
413   4
414   5
415   4
416   5
417   4
418   4
419   4
420   4
421   4
422   4
423   5
424   4
425   5
426   4
427   5
428   4
429   4
430   4
431   4
432   4
433   5
434   4
435   4
436   4

In [58]:
newarr = arr3.reshape(436, 1)

In [59]:
print(newarr.ndim)

2

In [60]:
new_arr2=np.append(arr2, newarr, axis=1)

In [61]:
print(type(new_arr2))

<class 'numpy.ndarray'>

In [62]:
print(new_arr2)

[[  0 385 171 318 409   4]
 [  1 379 421 410 353   4]
 [  2 162 380  13 394   4]
 ...
 [433  73  38 427 265   4]
 [434 202 236  36 213   4]
 [435  39 239 329  95   4]]

In [63]:
print(new_arr2[0])

[  0 385 171 318 409   4]

In [64]:
print(type(Y_train))

<class 'pandas.core.series.Series'>

In [65]:
arr2

array([[  0, 385, 171, 318, 409],
       [  1, 379, 421, 410, 353],
       [  2, 162, 380,  13, 394],
       ...,
       [433,  73,  38, 427, 265],
       [434, 202, 236,  36, 213],
       [435,  39, 239, 329,  95]], dtype=int64)

In [66]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

385 171 318 409 4

In [67]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [68]:
print(new_dist)

{574: 1, 557: 2, 56: 2, 42: 1, 296: 2, 342: 2, 611: 2, 263: 1, 269: 1, 412: 2, 131: 3, 41: 1, 33: 1, 181: 2, 396: 1, 217: 3, 260: 1, 229: 2, 566: 2, 356: 2, 429: 2, 521: 3, 232: 2, 168: 1, 534: 2, 454: 2, 501: 2, 261: 3, 608: 2, 477: 2, 502: 2, 384: 1, 325: 1, 500: 1, 443: 3, 49: 1, 315: 1, 526: 2, 545: 1, 92: 1, 75: 1, 390: 1, 337: 2, 11: 1, 491: 2, 253: 3, 484: 2, 45: 1, 198: 1, 459: 2, 112: 1, 283: 3, 517: 1, 376: 2, 178: 2, 610: 2, 80: 1, 224: 1, 343: 3, 304: 2, 234: 2, 584: 2, 493: 2, 414: 1, 190: 1, 268: 1, 338: 2, 498: 2, 516: 2, 210: 1, 483: 2, 122: 1, 475: 1, 419: 1, 142: 1, 271: 1, 320: 1, 499: 3, 88: 1, 416: 2, 286: 2, 592: 2, 114: 1, 386: 2, 600: 1, 138: 1, 305: 2, 249: 1, 352: 2, 398: 1, 202: 2, 374: 1, 126: 2, 273: 1, 90: 1, 98: 1, 125: 1, 53: 3, 385: 1, 203: 2, 421: 2, 625: 3, 357: 2, 413: 1, 193: 1, 464: 2, 494: 2, 278: 2, 442: 2, 322: 1, 522: 1, 274: 1, 423: 1, 134: 1, 139: 1, 363: 2, 510: 1, 247: 3, 580: 2, 448: 1, 254: 1, 596: 2, 358: 2, 279: 2, 290: 1, 485: 2, 373: 3, 175: 1, 199: 1, 393: 1, 282: 2, 599: 3, 238: 2, 294: 1, 17: 1, 452: 2, 347: 2, 623: 2, 605: 2, 588: 2, 46: 1, 147: 1, 96: 1, 239: 1, 14: 1, 520: 1, 144: 1, 21: 1, 601: 2, 346: 2, 341: 2, 123: 1, 456: 2, 191: 2, 359: 2, 267: 1, 58: 1, 264: 1, 64: 1, 372: 2, 166: 3, 62: 1, 81: 2, 216: 2, 200: 1, 61: 3, 109: 1, 568: 2, 4: 1, 23: 1, 476: 2, 549: 1, 47: 1, 330: 2, 525: 1, 538: 2, 74: 1, 450: 1, 336: 2, 474: 1, 128: 1, 388: 1, 426: 2, 251: 2, 16: 1, 437: 2, 603: 2, 382: 3, 15: 1, 209: 3, 620: 2, 235: 3, 101: 2, 533: 2, 515: 1, 272: 1, 577: 2, 508: 1, 213: 1, 504: 2, 145: 1, 360: 2, 289: 1, 52: 2, 85: 1, 66: 1, 329: 2, 69: 1, 50: 1, 113: 1, 389: 1, 192: 1, 60: 1, 310: 1, 44: 1, 409: 3, 564: 2, 152: 2, 19: 1, 250: 1, 434: 2, 609: 2, 467: 2, 174: 1, 541: 2, 366: 2, 171: 1, 616: 2, 40: 1, 82: 3, 331: 2, 95: 1, 26: 2, 140: 1, 326: 2, 507: 2, 319: 1, 457: 2, 36: 1, 218: 1, 334: 2, 38: 1, 300: 1, 369: 1, 165: 1, 256: 2, 265: 1, 170: 1, 221: 2, 576: 2, 353: 2, 176: 2, 159: 1, 560: 2, 463: 2, 187: 3, 255: 1, 328: 2, 120: 1, 473: 2, 280: 2, 222: 1, 550: 1, 391: 3, 231: 2, 519: 1, 355: 2, 604: 2, 410: 1, 624: 2, 309: 2, 214: 1, 327: 2, 83: 1, 195: 1, 340: 1, 411: 2, 9: 1, 183: 3, 220: 1, 350: 1, 354: 2, 141: 1, 585: 2, 301: 2, 67: 1, 572: 2, 225: 1, 106: 2, 563: 2, 43: 1, 155: 1, 303: 2, 613: 2, 530: 2, 535: 3, 453: 2, 579: 2, 281: 2, 606: 2, 79: 3, 364: 2, 403: 2, 586: 2, 30: 1, 417: 3, 299: 1, 65: 1, 313: 3, 593: 2, 163: 1, 287: 3, 285: 1, 307: 2, 602: 2, 77: 2, 482: 2, 137: 1, 575: 1, 230: 2, 86: 2, 89: 1, 146: 1, 400: 1, 37: 1, 614: 2, 186: 2, 226: 2, 461: 2, 94: 1, 565: 3, 302: 2, 317: 2, 151: 2, 185: 1, 12: 1, 612: 2, 157: 3, 257: 1, 28: 1, 618: 2, 276: 2, 486: 2, 418: 1, 156: 2, 78: 2, 551: 2, 617: 2, 182: 2, 362: 2, 492: 2, 440: 1, 35: 1, 556: 2, 422: 1, 242: 2, 111: 2, 397: 1, 164: 1, 536: 2, 415: 1, 308: 2, 559: 2, 472: 2, 158: 1, 379: 3, 39: 1, 446: 2, 244: 1, 387: 1, 518: 1, 554: 2, 228: 2, 161: 2, 201: 2, 527: 2, 537: 2, 462: 2, 119: 1, 532: 2, 51: 2, 439: 3, 371: 2, 497: 2, 219: 1, 569: 1, 204: 2, 102: 2, 470: 1, 425: 1, 478: 2, 99: 1, 503: 2, 10: 1, 31: 3, 298: 1, 32: 1, 8: 1, 571: 2, 489: 2, 5: 1, 509: 1, 514: 1, 105: 3, 91: 3, 20: 1, 436: 2, 84: 1, 401: 2, 444: 1, 582: 2, 555: 2, 311: 2, 365: 3, 540: 1, 127: 3, 162: 1, 496: 2, 487: 2, 215: 1, 13: 1, 558: 2, 2: 1, 619: 2, 348: 1, 377: 2, 339: 3, 543: 1, 167: 1, 490: 2, 395: 1, 587: 2, 370: 1, 544: 1, 314: 1, 93: 1}

In [69]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [70]:
print(new_dist2)

{0: 1, 1: 2, 2: 2, 3: 1, 4: 2, 5: 2, 6: 2, 7: 1, 8: 1, 9: 2, 10: 3, 11: 1, 12: 1, 13: 2, 14: 1, 15: 3, 16: 1, 17: 2, 18: 2, 19: 2, 20: 2, 21: 3, 22: 2, 23: 1, 24: 2, 25: 2, 26: 2, 27: 3, 28: 2, 29: 2, 30: 2, 31: 1, 32: 1, 33: 1, 34: 3, 35: 1, 36: 1, 37: 2, 38: 1, 39: 1, 40: 1, 41: 1, 42: 2, 43: 1, 44: 2, 45: 3, 46: 2, 47: 1, 48: 1, 49: 2, 50: 1, 51: 3, 52: 1, 53: 2, 54: 2, 55: 2, 56: 1, 57: 1, 58: 3, 59: 2, 60: 2, 61: 2, 62: 2, 63: 1, 64: 1, 65: 1, 66: 2, 67: 2, 68: 2, 69: 1, 70: 2, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 3, 78: 1, 79: 2, 80: 2, 81: 2, 82: 1, 83: 2, 84: 1, 85: 1, 86: 2, 87: 1, 88: 2, 89: 1, 90: 2, 91: 1, 92: 2, 93: 1, 94: 1, 95: 1, 96: 1, 97: 3, 98: 1, 99: 2, 100: 2, 101: 3, 102: 2, 103: 1, 104: 1, 105: 2, 106: 2, 107: 2, 108: 2, 109: 1, 110: 1, 111: 1, 112: 1, 113: 1, 114: 1, 115: 2, 116: 1, 117: 3, 118: 2, 119: 1, 120: 1, 121: 2, 122: 2, 123: 2, 124: 1, 125: 2, 126: 3, 127: 1, 128: 1, 129: 1, 130: 2, 131: 3, 132: 2, 133: 1, 134: 1, 135: 2, 136: 2, 137: 2, 138: 2, 139: 2, 140: 1, 141: 1, 142: 1, 143: 1, 144: 1, 145: 1, 146: 1, 147: 1, 148: 2, 149: 2, 150: 2, 151: 1, 152: 2, 153: 2, 154: 2, 155: 1, 156: 1, 157: 1, 158: 1, 159: 2, 160: 3, 161: 1, 162: 2, 163: 2, 164: 1, 165: 3, 166: 1, 167: 2, 168: 1, 169: 1, 170: 2, 171: 1, 172: 1, 173: 2, 174: 1, 175: 2, 176: 1, 177: 1, 178: 2, 179: 1, 180: 1, 181: 1, 182: 2, 183: 2, 184: 1, 185: 2, 186: 2, 187: 3, 188: 1, 189: 3, 190: 2, 191: 3, 192: 2, 193: 2, 194: 1, 195: 1, 196: 2, 197: 1, 198: 1, 199: 2, 200: 1, 201: 2, 202: 1, 203: 2, 204: 1, 205: 1, 206: 2, 207: 1, 208: 1, 209: 1, 210: 1, 211: 1, 212: 1, 213: 1, 214: 1, 215: 3, 216: 2, 217: 2, 218: 1, 219: 1, 220: 2, 221: 2, 222: 2, 223: 1, 224: 2, 225: 2, 226: 1, 227: 2, 228: 1, 229: 3, 230: 2, 231: 1, 232: 2, 233: 1, 234: 2, 235: 2, 236: 1, 237: 2, 238: 1, 239: 1, 240: 2, 241: 1, 242: 1, 243: 1, 244: 1, 245: 2, 246: 1, 247: 1, 248: 2, 249: 2, 250: 2, 251: 2, 252: 1, 253: 2, 254: 2, 255: 3, 256: 1, 257: 2, 258: 1, 259: 2, 260: 2, 261: 1, 262: 1, 263: 3, 264: 2, 265: 1, 266: 2, 267: 2, 268: 1, 269: 2, 270: 2, 271: 1, 272: 2, 273: 1, 274: 1, 275: 1, 276: 2, 277: 1, 278: 3, 279: 1, 280: 1, 281: 2, 282: 1, 283: 2, 284: 2, 285: 1, 286: 2, 287: 1, 288: 2, 289: 2, 290: 1, 291: 1, 292: 2, 293: 2, 294: 2, 295: 3, 296: 2, 297: 2, 298: 2, 299: 2, 300: 3, 301: 2, 302: 2, 303: 2, 304: 1, 305: 3, 306: 1, 307: 1, 308: 3, 309: 2, 310: 1, 311: 3, 312: 1, 313: 2, 314: 2, 315: 2, 316: 2, 317: 1, 318: 1, 319: 2, 320: 2, 321: 1, 322: 1, 323: 1, 324: 1, 325: 2, 326: 2, 327: 2, 328: 2, 329: 1, 330: 3, 331: 2, 332: 2, 333: 2, 334: 1, 335: 1, 336: 2, 337: 3, 338: 1, 339: 1, 340: 2, 341: 2, 342: 2, 343: 1, 344: 2, 345: 2, 346: 2, 347: 2, 348: 2, 349: 2, 350: 2, 351: 1, 352: 1, 353: 2, 354: 1, 355: 2, 356: 2, 357: 1, 358: 1, 359: 2, 360: 1, 361: 2, 362: 2, 363: 2, 364: 1, 365: 3, 366: 1, 367: 2, 368: 1, 369: 1, 370: 1, 371: 2, 372: 2, 373: 2, 374: 2, 375: 2, 376: 2, 377: 2, 378: 1, 379: 2, 380: 2, 381: 3, 382: 2, 383: 2, 384: 1, 385: 1, 386: 2, 387: 2, 388: 1, 389: 1, 390: 2, 391: 1, 392: 2, 393: 1, 394: 3, 395: 1, 396: 1, 397: 1, 398: 2, 399: 2, 400: 1, 401: 1, 402: 1, 403: 3, 404: 3, 405: 1, 406: 2, 407: 1, 408: 2, 409: 1, 410: 2, 411: 2, 412: 2, 413: 3, 414: 1, 415: 3, 416: 1, 417: 2, 418: 2, 419: 1, 420: 1, 421: 2, 422: 1, 423: 2, 424: 1, 425: 2, 426: 3, 427: 1, 428: 1, 429: 2, 430: 1, 431: 2, 432: 1, 433: 1, 434: 1, 435: 1}

In [71]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [72]:
print(new_dist3)

{0: 574, 1: 557, 2: 56, 3: 42, 4: 296, 5: 342, 6: 611, 7: 263, 8: 269, 9: 412, 10: 131, 11: 41, 12: 33, 13: 181, 14: 396, 15: 217, 16: 260, 17: 229, 18: 566, 19: 356, 20: 429, 21: 521, 22: 232, 23: 168, 24: 534, 25: 454, 26: 501, 27: 261, 28: 608, 29: 477, 30: 502, 31: 384, 32: 325, 33: 500, 34: 443, 35: 49, 36: 315, 37: 526, 38: 545, 39: 92, 40: 75, 41: 390, 42: 337, 43: 11, 44: 491, 45: 253, 46: 484, 47: 45, 48: 198, 49: 459, 50: 112, 51: 283, 52: 517, 53: 376, 54: 178, 55: 610, 56: 80, 57: 224, 58: 343, 59: 304, 60: 234, 61: 584, 62: 493, 63: 414, 64: 190, 65: 268, 66: 338, 67: 498, 68: 516, 69: 210, 70: 483, 71: 122, 72: 475, 73: 419, 74: 142, 75: 271, 76: 320, 77: 499, 78: 88, 79: 416, 80: 286, 81: 592, 82: 114, 83: 386, 84: 600, 85: 138, 86: 305, 87: 249, 88: 352, 89: 398, 90: 202, 91: 374, 92: 126, 93: 273, 94: 90, 95: 98, 96: 125, 97: 53, 98: 385, 99: 203, 100: 421, 101: 625, 102: 357, 103: 413, 104: 193, 105: 464, 106: 494, 107: 278, 108: 442, 109: 322, 110: 522, 111: 274, 112: 423, 113: 134, 114: 139, 115: 363, 116: 510, 117: 247, 118: 580, 119: 448, 120: 254, 121: 596, 122: 358, 123: 279, 124: 290, 125: 485, 126: 373, 127: 175, 128: 199, 129: 393, 130: 282, 131: 599, 132: 238, 133: 294, 134: 17, 135: 452, 136: 347, 137: 623, 138: 605, 139: 588, 140: 46, 141: 147, 142: 96, 143: 239, 144: 14, 145: 520, 146: 144, 147: 21, 148: 601, 149: 346, 150: 341, 151: 123, 152: 456, 153: 191, 154: 359, 155: 267, 156: 58, 157: 264, 158: 64, 159: 372, 160: 166, 161: 62, 162: 81, 163: 216, 164: 200, 165: 61, 166: 109, 167: 568, 168: 4, 169: 23, 170: 476, 171: 549, 172: 47, 173: 330, 174: 525, 175: 538, 176: 74, 177: 450, 178: 336, 179: 474, 180: 128, 181: 388, 182: 426, 183: 251, 184: 16, 185: 437, 186: 603, 187: 382, 188: 15, 189: 209, 190: 620, 191: 235, 192: 101, 193: 533, 194: 515, 195: 272, 196: 577, 197: 508, 198: 213, 199: 504, 200: 145, 201: 360, 202: 289, 203: 52, 204: 85, 205: 66, 206: 329, 207: 69, 208: 50, 209: 113, 210: 389, 211: 192, 212: 60, 213: 310, 214: 44, 215: 409, 216: 564, 217: 152, 218: 19, 219: 250, 220: 434, 221: 609, 222: 467, 223: 174, 224: 541, 225: 366, 226: 171, 227: 616, 228: 40, 229: 82, 230: 331, 231: 95, 232: 26, 233: 140, 234: 326, 235: 507, 236: 319, 237: 457, 238: 36, 239: 218, 240: 334, 241: 38, 242: 300, 243: 369, 244: 165, 245: 256, 246: 265, 247: 170, 248: 221, 249: 576, 250: 353, 251: 176, 252: 159, 253: 560, 254: 463, 255: 187, 256: 255, 257: 328, 258: 120, 259: 473, 260: 280, 261: 222, 262: 550, 263: 391, 264: 231, 265: 519, 266: 355, 267: 604, 268: 410, 269: 624, 270: 309, 271: 214, 272: 327, 273: 83, 274: 195, 275: 340, 276: 411, 277: 9, 278: 183, 279: 220, 280: 350, 281: 354, 282: 141, 283: 585, 284: 301, 285: 67, 286: 572, 287: 225, 288: 106, 289: 563, 290: 43, 291: 155, 292: 303, 293: 613, 294: 530, 295: 535, 296: 453, 297: 579, 298: 281, 299: 606, 300: 79, 301: 364, 302: 403, 303: 586, 304: 30, 305: 417, 306: 299, 307: 65, 308: 313, 309: 593, 310: 163, 311: 287, 312: 285, 313: 307, 314: 602, 315: 77, 316: 482, 317: 137, 318: 575, 319: 230, 320: 86, 321: 89, 322: 146, 323: 400, 324: 37, 325: 614, 326: 186, 327: 226, 328: 461, 329: 94, 330: 565, 331: 302, 332: 317, 333: 151, 334: 185, 335: 12, 336: 612, 337: 157, 338: 257, 339: 28, 340: 618, 341: 276, 342: 486, 343: 418, 344: 156, 345: 78, 346: 551, 347: 617, 348: 182, 349: 362, 350: 492, 351: 440, 352: 35, 353: 556, 354: 422, 355: 242, 356: 111, 357: 397, 358: 164, 359: 536, 360: 415, 361: 308, 362: 559, 363: 472, 364: 158, 365: 379, 366: 39, 367: 446, 368: 244, 369: 387, 370: 518, 371: 554, 372: 228, 373: 161, 374: 201, 375: 527, 376: 537, 377: 462, 378: 119, 379: 532, 380: 51, 381: 439, 382: 371, 383: 497, 384: 219, 385: 569, 386: 204, 387: 102, 388: 470, 389: 425, 390: 478, 391: 99, 392: 503, 393: 10, 394: 31, 395: 298, 396: 32, 397: 8, 398: 571, 399: 489, 400: 5, 401: 509, 402: 514, 403: 105, 404: 91, 405: 20, 406: 436, 407: 84, 408: 401, 409: 444, 410: 582, 411: 555, 412: 311, 413: 365, 414: 540, 415: 127, 416: 162, 417: 496, 418: 487, 419: 215, 420: 13, 421: 558, 422: 2, 423: 619, 424: 348, 425: 377, 426: 339, 427: 543, 428: 167, 429: 490, 430: 395, 431: 587, 432: 370, 433: 544, 434: 314, 435: 93}

In [73]:
#print(new_dist[204])

In [74]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
        print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

0   574   5   0   0   4
1   557   0   5   0   4
2   56   0   4   1   4
3   42   5   0   0   4
4   296   2   3   0   5
5   342   0   5   0   4
6   611   0   5   0   4
7   263   5   0   0   4
8   269   5   0   0   4
9   412   0   4   1   4
10   131   0   2   3   5
11   41   5   0   0   4
12   33   5   0   0   4
13   181   0   5   0   4
14   396   5   0   0   4
15   217   0   2   3   5
16   260   5   0   0   4
17   229   0   5   0   4
18   566   0   5   0   4
19   356   0   5   0   4
20   429   0   5   0   4
21   521   0   3   2   6
22   232   0   5   0   4
23   168   5   0   0   4
24   534   0   4   1   4
25   454   0   5   0   4
26   501   0   5   0   4
27   261   0   2   3   5
28   608   0   5   0   4
29   477   0   5   0   4
30   502   0   5   0   4
31   384   5   0   0   4
32   325   5   0   0   4
33   500   5   0   0   5
34   443   0   1   4   5
35   49   5   0   0   4
36   315   5   0   0   4
37   526   0   5   0   4
38   545   5   0   0   4
39   92   5   0   0   4
40   75   5   0   0   4
41   390   5   0   0   4
42   337   0   5   0   4
43   11   5   0   0   4
44   491   0   5   0   4
45   253   0   1   4   5
46   484   0   5   0   4
47   45   5   0   0   4
48   198   5   0   0   4
49   459   0   5   0   4
50   112   4   1   0   5
51   283   0   2   3   5
52   517   5   0   0   4
53   376   0   5   0   4
54   178   0   4   1   4
55   610   0   5   0   4
56   80   5   0   0   5
57   224   5   0   0   4
58   343   0   1   4   5
59   304   0   5   0   4
60   234   1   4   0   4
61   584   0   5   0   4
62   493   0   5   0   4
63   414   5   0   0   4
64   190   5   0   0   4
65   268   5   0   0   4
66   338   0   5   0   4
67   498   0   5   0   4
68   516   1   3   1   5
69   210   5   0   0   4
70   483   0   5   0   4
71   122   5   0   0   5
72   475   5   0   0   4
73   419   5   0   0   4
74   142   5   0   0   4
75   271   5   0   0   4
76   320   5   0   0   4
77   499   0   3   2   5
78   88   5   0   0   4
79   416   0   5   0   4
80   286   0   5   0   4
81   592   0   5   0   4
82   114   5   0   0   4
83   386   0   5   0   5
84   600   5   0   0   4
85   138   5   0   0   4
86   305   0   5   0   4
87   249   5   0   0   4
88   352   0   5   0   4
89   398   5   0   0   4
90   202   0   5   0   4
91   374   5   0   0   4
92   126   0   3   2   4
93   273   5   0   0   4
94   90   5   0   0   4
95   98   5   0   0   4
96   125   5   0   0   4
97   53   0   3   2   5
98   385   5   0   0   4
99   203   0   5   0   4
100   421   1   4   0   4
101   625   0   2   3   5
102   357   0   5   0   4
103   413   4   1   0   4
104   193   5   0   0   4
105   464   0   5   0   4
106   494   0   5   0   4
107   278   0   4   1   4
108   442   0   5   0   4
109   322   4   1   0   5
110   522   5   0   0   4
111   274   5   0   0   4
112   423   5   0   0   4
113   134   5   0   0   4
114   139   5   0   0   4
115   363   0   5   0   4
116   510   5   0   0   4
117   247   0   2   3   5
118   580   0   5   0   4
119   448   5   0   0   5
120   254   4   1   0   5
121   596   0   5   0   5
122   358   0   5   0   4
123   279   1   4   0   4
124   290   5   0   0   4
125   485   0   5   0   4
126   373   0   1   4   5
127   175   5   0   0   4
128   199   5   0   0   4
129   393   5   0   0   4
130   282   0   4   1   4
131   599   0   2   3   5
132   238   0   5   0   5
133   294   5   0   0   4
134   17   5   0   0   4
135   452   0   5   0   4
136   347   0   5   0   4
137   623   0   5   0   4
138   605   0   5   0   4
139   588   0   5   0   4
140   46   5   0   0   4
141   147   5   0   0   4
142   96   4   1   0   5
143   239   5   0   0   4
144   14   5   0   0   4
145   520   5   0   0   4
146   144   5   0   0   4
147   21   5   0   0   4
148   601   0   5   0   4
149   346   0   5   0   4
150   341   0   5   0   4
151   123   5   0   0   4
152   456   0   5   0   4
153   191   0   4   1   4
154   359   0   5   0   4
155   267   5   0   0   4
156   58   5   0   0   4
157   264   5   0   0   4
158   64   5   0   0   4
159   372   0   4   1   4
160   166   0   3   2   6
161   62   5   0   0   4
162   81   0   4   1   4
163   216   0   4   1   4
164   200   5   0   0   4
165   61   0   2   3   5
166   109   4   1   0   4
167   568   1   4   0   4
168   4   5   0   0   4
169   23   5   0   0   5
170   476   0   5   0   4
171   549   5   0   0   4
172   47   5   0   0   4
173   330   0   5   0   4
174   525   5   0   0   4
175   538   0   5   0   4
176   74   5   0   0   4
177   450   5   0   0   4
178   336   0   5   0   4
179   474   5   0   0   5
180   128   5   0   0   5
181   388   5   0   0   4
182   426   0   5   0   4
183   251   0   5   0   4
184   16   5   0   0   4
185   437   0   5   0   4
186   603   0   5   0   4
187   382   0   4   1   6
188   15   5   0   0   4
189   209   0   3   2   5
190   620   0   5   0   5
191   235   0   2   3   5
192   101   0   5   0   4
193   533   0   5   0   4
194   515   5   0   0   4
195   272   5   0   0   4
196   577   0   5   0   4
197   508   3   2   0   5
198   213   5   0   0   4
199   504   0   4   1   5
200   145   5   0   0   4
201   360   0   5   0   4
202   289   5   0   0   4
203   52   0   5   0   4
204   85   5   0   0   4
205   66   4   1   0   4
206   329   0   5   0   4
207   69   5   0   0   4
208   50   5   0   0   4
209   113   5   0   0   4
210   389   5   0   0   4
211   192   5   0   0   4
212   60   5   0   0   4
213   310   5   0   0   4
214   44   5   0   0   4
215   409   0   2   3   5
216   564   0   5   0   4
217   152   0   4   1   5
218   19   5   0   0   4
219   250   5   0   0   4
220   434   0   5   0   4
221   609   0   5   0   4
222   467   0   5   0   4
223   174   5   0   0   4
224   541   0   5   0   4
225   366   0   5   0   4
226   171   5   0   0   4
227   616   0   5   0   4
228   40   5   0   0   4
229   82   0   4   1   6
230   331   0   5   0   4
231   95   5   0   0   4
232   26   0   5   0   4
233   140   5   0   0   4
234   326   0   5   0   4
235   507   0   4   1   4
236   319   5   0   0   4
237   457   0   5   0   4
238   36   5   0   0   4
239   218   5   0   0   4
240   334   0   5   0   4
241   38   5   0   0   4
242   300   5   0   0   4
243   369   5   0   0   4
244   165   5   0   0   4
245   256   0   4   1   4
246   265   5   0   0   4
247   170   5   0   0   4
248   221   1   4   0   4
249   576   0   5   0   4
250   353   0   5   0   4
251   176   0   5   0   4
252   159   5   0   0   4
253   560   0   5   0   4
254   463   0   5   0   4
255   187   0   2   3   5
256   255   4   1   0   4
257   328   0   5   0   4
258   120   5   0   0   4
259   473   0   5   0   4
260   280   2   3   0   4
261   222   4   1   0   5
262   550   5   0   0   4
263   391   0   3   2   5
264   231   0   5   0   4
265   519   5   0   0   4
266   355   0   5   0   4
267   604   0   5   0   4
268   410   5   0   0   4
269   624   0   5   0   4
270   309   0   5   0   4
271   214   5   0   0   4
272   327   0   5   0   4
273   83   5   0   0   4
274   195   5   0   0   4
275   340   5   0   0   4
276   411   0   5   0   4
277   9   5   0   0   4
278   183   0   1   4   5
279   220   5   0   0   4
280   350   5   0   0   4
281   354   0   5   0   4
282   141   5   0   0   4
283   585   0   5   0   4
284   301   0   5   0   4
285   67   5   0   0   4
286   572   0   5   0   5
287   225   5   0   0   4
288   106   0   5   0   4
289   563   0   5   0   4
290   43   5   0   0   4
291   155   5   0   0   5
292   303   0   5   0   4
293   613   0   5   0   4
294   530   0   4   1   5
295   535   0   3   2   5
296   453   0   5   0   4
297   579   0   5   0   4
298   281   0   5   0   4
299   606   0   5   0   4
300   79   0   2   3   5
301   364   0   5   0   4
302   403   0   5   0   5
303   586   0   5   0   4
304   30   5   0   0   4
305   417   0   2   3   5
306   299   5   0   0   4
307   65   5   0   0   4
308   313   0   0   5   5
309   593   0   5   0   4
310   163   5   0   0   4
311   287   0   1   4   5
312   285   5   0   0   4
313   307   0   5   0   4
314   602   0   5   0   4
315   77   0   5   0   4
316   482   0   5   0   4
317   137   5   0   0   4
318   575   5   0   0   4
319   230   0   4   1   4
320   86   0   5   0   4
321   89   5   0   0   4
322   146   5   0   0   4
323   400   5   0   0   4
324   37   5   0   0   4
325   614   0   5   0   4
326   186   0   5   0   4
327   226   0   5   0   4
328   461   0   5   0   4
329   94   5   0   0   4
330   565   0   2   3   5
331   302   0   5   0   4
332   317   1   4   0   4
333   151   0   5   0   4
334   185   5   0   0   4
335   12   5   0   0   4
336   612   0   5   0   4
337   157   0   2   3   5
338   257   3   2   0   5
339   28   5   0   0   5
340   618   0   5   0   4
341   276   0   5   0   4
342   486   0   5   0   4
343   418   5   0   0   4
344   156   0   5   0   4
345   78   0   5   0   4
346   551   0   5   0   4
347   617   0   5   0   4
348   182   0   4   1   4
349   362   0   5   0   4
350   492   0   5   0   4
351   440   5   0   0   4
352   35   5   0   0   4
353   556   0   5   0   4
354   422   5   0   0   4
355   242   0   4   1   5
356   111   0   5   0   4
357   397   5   0   0   4
358   164   5   0   0   4
359   536   0   5   0   4
360   415   5   0   0   4
361   308   0   4   1   4
362   559   0   5   0   4
363   472   0   5   0   4
364   158   5   0   0   4
365   379   0   2   3   5
366   39   5   0   0   4
367   446   0   5   0   4
368   244   5   0   0   4
369   387   4   1   0   5
370   518   5   0   0   4
371   554   0   5   0   4
372   228   0   5   0   4
373   161   0   5   0   4
374   201   0   5   0   4
375   527   0   5   0   4
376   537   0   5   0   4
377   462   0   5   0   4
378   119   5   0   0   4
379   532   0   5   0   4
380   51   0   5   0   4
381   439   0   1   4   5
382   371   0   5   0   4
383   497   0   5   0   4
384   219   5   0   0   4
385   569   5   0   0   4
386   204   0   5   0   4
387   102   0   5   0   4
388   470   5   0   0   5
389   425   5   0   0   4
390   478   0   5   0   4
391   99   5   0   0   4
392   503   0   5   0   4
393   10   5   0   0   4
394   31   0   2   3   5
395   298   5   0   0   4
396   32   5   0   0   4
397   8   5   0   0   4
398   571   0   5   0   4
399   489   0   5   0   4
400   5   5   0   0   4
401   509   5   0   0   4
402   514   5   0   0   4
403   105   0   2   3   5
404   91   0   2   3   5
405   20   5   0   0   4
406   436   0   5   0   4
407   84   5   0   0   4
408   401   0   5   0   4
409   444   5   0   0   4
410   582   0   5   0   4
411   555   0   5   0   4
412   311   0   5   0   4
413   365   0   2   3   5
414   540   5   0   0   4
415   127   0   2   3   5
416   162   5   0   0   4
417   496   0   5   0   4
418   487   0   5   0   4
419   215   5   0   0   4
420   13   5   0   0   4
421   558   0   5   0   4
422   2   5   0   0   5
423   619   0   5   0   4
424   348   5   0   0   5
425   377   0   4   1   4
426   339   0   1   4   5
427   543   5   0   0   4
428   167   5   0   0   4
429   490   0   5   0   4
430   395   5   0   0   4
431   587   0   5   0   4

432   370   5   0   0   5
433   544   5   0   0   4
434   314   5   0   0   4
435   93   5   0   0   4

In [75]:
#neigh_count=[]
#s=0
#for i, v in new_dist.items():
#    c1=0
#    c2=0
 #   c3=0
  #  if int(v) == 1:
   #     c1=c1+1
    #elif int(v) == 2:
     #   c2=c2+1
    #else:
     #   c3=c3+1
    #for x in range(1,5):
        #print(x)
     #   y=new_dist[new_arr2[s][x]]
      #  print(y)
    #s=s+1
        
            
    
#print(i," ",c1," ",c2," ",c3)