In [1]:
import numpy as np 
import pandas as pd 
import math
import random

In [2]:
data=pd.read_csv("new-thyroid.csv")

In [3]:
data.columns=["id","Class","Oxin","Onine","Hormone","Tsh","Resin"]

In [4]:
data.set_index("id", inplace=True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214 entries, 2 to 215
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Class    214 non-null    int64
 1   Oxin     214 non-null    int64
 2   Onine    214 non-null    float64
 3   Hormone  214 non-null    float64
 4   Tsh      214 non-null    float64
 5   Resin    214 non-null    float64
dtypes: float64(4), int64(2)
memory usage: 11.7 KB

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
data

     Class  Oxin  Onine  Hormone  Tsh  Resin
id
2        1   113    9.9      3.1  2.0    5.9
3        1   127   12.9      2.4  1.4    0.6
4        1   109    5.3      1.6  1.4    1.5
5        1   105    7.3      1.5  1.5   -0.1
6        1   105    6.1      2.1  1.4    7.0
..     ...   ...    ...      ...  ...    ...
211      3   118    6.5      1.3  1.7   11.5
212      3   139    4.2      0.7  4.3    6.3
213      3   103    5.1      1.4  1.2    5.0
214      3    97    4.7      1.1  2.1   12.6
215      3   102    5.3      1.4  1.3    6.7

[214 rows x 6 columns]

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [9]:
train_file_x=X_train.to_csv("xxx.csv")

In [10]:
test_file_x=X_test.to_csv("xx_test.csv")

In [11]:
train_file_y=Y_train.to_csv("yyy.csv")

In [12]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(149, 6) (65, 6) (149,) (65,)

In [14]:
X_train

     Class  Oxin  Onine  Hormone  Tsh  Resin
id
129      1   130   10.0      1.6  0.9    4.6
86       1   107   13.0      1.5  2.8    1.7
10       1   107   13.0      1.1  0.9    3.1
14       1   112    8.1      1.9  3.7    2.0
15       1   122    9.7      1.6  0.9    2.2
..     ...   ...    ...      ...  ...    ...
93       1   112    9.5      2.0  1.2    0.7
111      1   116   16.1      0.9  1.3    1.5
83       1   103    8.5      1.8  1.9    1.1
21       1   101    7.8      1.2  1.0    1.7
181      2    88   16.5      4.9  0.8    0.1

[149 rows x 6 columns]

In [15]:
Y_train

id
129    1
86     1
10     1
14     1
15     1
      ..
93     1
111    1
83     1
21     1
181    2
Name: Class, Length: 149, dtype: int64

In [16]:
gb=X_train.groupby("Class")

In [17]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
     Class  Oxin  Onine  Hormone  Tsh  Resin
id
129      1   130   10.0      1.6  0.9    4.6
86       1   107   13.0      1.5  2.8    1.7
10       1   107   13.0      1.1  0.9    3.1
14       1   112    8.1      1.9  3.7    2.0
15       1   122    9.7      1.6  0.9    2.2
..     ...   ...    ...      ...  ...    ...
22       1   103   10.1      1.3  0.7    0.1
93       1   112    9.5      2.0  1.2    0.7
111      1   116   16.1      0.9  1.3    1.5
83       1   103    8.5      1.8  1.9    1.1
21       1   101    7.8      1.2  1.0    1.7

[109 rows x 6 columns]
2
     Class  Oxin  Onine  Hormone  Tsh  Resin
id
183      2   106   13.4      3.0  1.1    0.0
185      2    92   11.1      2.0  0.7   -0.2
158      2   110   20.3      3.7  0.6    0.2
163      2    88   12.9      2.7  0.1    0.2
184      2    79   19.0      5.5  0.9    0.3
161      2    89   14.3      4.1  0.5    0.2
168      2    89   21.8      7.1  0.7   -0.1
157      2   134   16.4      4.8  0.6    0.1
182      2    97   15.1      1.8  1.2   -0.2
178      2   110   15.2      1.9  0.7   -0.2
153      2   113   17.2      1.8  1.0    0.0
151      2   139   16.4      3.8  1.1   -0.2
174      2    98   16.7      4.3  1.7    0.2
154      2    65   25.3      5.8  1.3    0.2
172      2    84   21.5      2.7  1.1   -0.6
166      2    99   13.0      3.6  0.7   -0.1
165      2    89   20.1      7.3  1.1   -0.2
173      2    84   18.5      4.4  1.1   -0.3
156      2    65   18.2     10.0  1.3    0.1
180      2   105   12.0      3.3  1.1    0.0
152      2   111   16.0      2.1  0.9   -0.1
181      2    88   16.5      4.9  0.8    0.1
3
     Class  Oxin  Onine  Hormone   Tsh  Resin
id
199      3   121    4.7      1.8  11.2   53.0
187      3   120    6.8      2.1  10.4   38.6
186      3   125    2.3      0.9  16.5    9.5
211      3   118    6.5      1.3   1.7   11.5
206      3   125    3.7      1.1   8.5   25.9
197      3   115    6.3      1.2   4.7   14.4
210      3   119    5.1      1.1   7.0   40.8
205      3   120    3.4      1.8   7.5   21.5
189      3   120    3.0      2.5   1.2    4.5
190      3   119    3.8      1.1  23.0    5.7
207      3   123    1.9      0.3  22.8   22.2
193      3   118    3.6      1.5  11.6   48.8
203      3   113    5.1      0.7   5.8   19.6
213      3   103    5.1      1.4   1.2    5.0
208      3   112    2.6      0.7  41.0   19.0
191      3   141    5.6      1.8   9.2   14.4
195      3   119    0.8      0.7  56.4   21.6
215      3   102    5.3      1.4   1.3    6.7

In [18]:
gb.get_group(1)

     Class  Oxin  Onine  Hormone  Tsh  Resin
id
129      1   130   10.0      1.6  0.9    4.6
86       1   107   13.0      1.5  2.8    1.7
10       1   107   13.0      1.1  0.9    3.1
14       1   112    8.1      1.9  3.7    2.0
15       1   122    9.7      1.6  0.9    2.2
..     ...   ...    ...      ...  ...    ...
22       1   103   10.1      1.3  0.7    0.1
93       1   112    9.5      2.0  1.2    0.7
111      1   116   16.1      0.9  1.3    1.5
83       1   103    8.5      1.8  1.9    1.1
21       1   101    7.8      1.2  1.0    1.7

[109 rows x 6 columns]

In [19]:
class_samples=gb.get_group(1).sample(n=15)
#    print(class_samples)

In [20]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>

In [21]:
mean_sum=class_samples["Oxin"].mean() + class_samples["Onine"].mean() + class_samples["Hormone"].mean() + class_samples["Tsh"].mean() + class_samples["Resin"].mean()

In [22]:
column_length=len(X_train.columns) -1

In [23]:
similar_val_1=mean_sum/column_length
print(similar_val_1)

24.985333333333337

In [24]:
class_2_samples=gb.get_group(2).sample(n=15)
#    print(class_2_samples)

In [25]:
mean_sum_2=class_2_samples["Oxin"].mean() + class_2_samples["Onine"].mean() + class_2_samples["Hormone"].mean() + class_2_samples["Tsh"].mean() + class_2_samples["Resin"].mean()

In [26]:
similar_val_2=mean_sum_2/column_length
print(similar_val_2)

23.522666666666666

In [27]:
class_3_samples=gb.get_group(3).sample(n=15)
#    print(class_3_samples)

In [28]:
mean_sum_3=class_3_samples["Oxin"].mean() + class_3_samples["Onine"].mean() + class_3_samples["Hormone"].mean() + class_3_samples["Tsh"].mean() + class_3_samples["Resin"].mean()

In [29]:
similar_val_3=mean_sum_3/column_length
print(similar_val_3)

32.501333333333335

In [30]:
sim_23=similar_val_3 - similar_val_2
sim_23=sim_23/10
sim_23=1 - sim_23
sim_12=similar_val_1 - similar_val_2
sim_12=sim_12/10
sim_12=1 - sim_12
sim_13=similar_val_3 - similar_val_1
sim_13=sim_13/10
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_12)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.10213333333333308
Similarity between 2 and 1:  0.8537333333333329
Similarity between 1 and 3:  0.24840000000000018

In [31]:
gb.size()

Class
1    109
2     22
3     18
dtype: int64

In [32]:
m=math.ceil((103+24)/2)

In [33]:
print(m)

64

In [34]:
len(gb)

3

In [35]:
 from sklearn.neighbors import KNeighborsClassifier

In [36]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [37]:
#neigh.fit(X_train, Y_train)
neigh.fit(X_train, X_train.Class)

KNeighborsClassifier()

In [38]:
result=neigh.kneighbors(X_train, return_distance=True)

In [39]:
print(type(result))

<class 'tuple'>

In [40]:
print(result)

(array([[ 0.        ,  1.57162336,  2.66833281,  4.14969878,  4.17971291],
       [ 0.        ,  1.97989899,  2.39374184,  2.60768096,  2.64952826],
       [ 0.        ,  1.5       ,  2.39374184,  2.96479342,  3.06757233],
       [ 0.        ,  2.87402157,  2.95127091,  3.14801525,  3.25269119],
       [ 0.        ,  1.56524758,  2.22261108,  2.39582971,  3.53128872],
       [ 0.        ,  1.3       ,  1.91833261,  2.02731349,  2.20227155],
       [ 0.        ,  1.73493516,  2.10475652,  2.21359436,  2.51396102],
       [ 0.        ,  5.30094331, 13.08166656, 14.6116392 , 27.55340269],
       [ 0.        ,  2.37065392,  2.54165301,  2.64952826,  2.66082694],
       [ 0.        ,  1.396424  ,  1.40712473,  1.47648231,  1.77482393],
       [ 0.        ,  4.6141088 , 10.95810203, 14.16015537, 14.6116392 ],
       [ 0.        ,  1.74642492,  2.80891438,  2.83372546,  3.04959014],
       [ 0.        ,  2.2737634 ,  2.48596058,  2.87402157,  3.10644491],
       [ 0.        ,  1.61864141,  1.98494332,  2.37065392,  2.81780056],
       [ 0.        ,  1.92613603,  2.00499377,  2.21585198,  2.36008474],
       [ 0.        ,  1.72336879,  2.07364414,  2.48596058,  2.88097206],
       [ 0.        ,  9.74576831, 14.33527119, 15.87513779, 16.14744562],
       [ 0.        ,  3.93827373,  4.04227659,  4.5       ,  4.88364618],
       [ 0.        ,  2.07846097,  2.12602916,  2.1977261 ,  2.3       ],
       [ 0.        ,  4.71487009,  4.73497624,  5.42402065,  7.75499839],
       [ 0.        ,  1.22474487,  1.33416641,  1.85741756,  2.19544984],
       [ 0.        ,  2.01990099,  2.1023796 ,  2.26495033,  2.79284801],
       [ 0.        ,  2.01990099,  2.24944438,  2.47184142,  2.97153159],
       [ 0.        ,  2.13072758,  2.58069758,  2.64952826,  2.78567766],
       [ 0.        ,  2.04450483,  2.39582971,  3.01827765,  3.02489669],
       [ 0.        ,  3.43511281,  5.14392846,  5.89745708,  7.76208735],
       [ 0.        ,  2.11423745,  2.52586619,  3.24653662,  3.34813381],
       [ 0.        ,  1.8627936 ,  2.7513633 ,  2.88790582,  3.06757233],
       [ 0.        ,  1.44913767,  2.65141472,  3.06267857,  3.18904374],
       [ 0.        ,  0.94339811,  1.04403065,  1.87082869,  2.10475652],
       [ 0.        ,  6.77790528, 13.8960426 , 14.16015537, 15.03529182],
       [ 0.        ,  1.23693169,  1.60623784,  1.63401346,  1.98997487],
       [ 0.        ,  1.33041347,  2.48997992,  2.86879766,  3.17647603],
       [ 0.        ,  1.28452326,  3.5       ,  4.02367991,  4.14728827],
       [ 0.        ,  2.01990099,  3.48998567,  3.65102725,  3.80131556],
       [ 0.        ,  1.76068169,  1.96214169,  2.04450483,  2.31732605],
       [ 0.        ,  1.23693169,  1.63401346,  1.81659021,  1.83030052],
       [ 0.        ,  0.94339811,  1.25698051,  2.13072758,  2.23383079],
       [ 0.        ,  1.86547581,  1.98494332,  2.64952826,  2.77488739],
       [ 0.        ,  2.25388553,  4.27784993,  4.5       ,  5.63471383],
       [ 0.        ,  1.1       ,  2.04205779,  2.16333077,  2.29128785],
       [ 0.        ,  5.18266341,  6.31981012,  9.36269192, 10.2342562 ],
       [ 0.        ,  1.56524758,  1.64620776,  2.94108823,  3.02489669],
       [ 0.        ,  2.25388553,  2.56515107,  4.88364618,  6.58331224],
       [ 0.        ,  1.18743421,  1.91833261,  1.97737199,  2.10475652],
       [ 0.        ,  1.76068169,  5.82923666,  6.58634952,  6.69776082],
       [ 0.        ,  5.14392846,  5.240229  ,  5.82580467,  9.06311205],
       [ 0.        ,  5.13225097,  7.33348485,  7.91075218,  8.30060239],
       [ 0.        ,  4.6141088 ,  9.41116358, 13.08166656, 16.19320845],
       [ 0.        ,  1.28452326,  3.27261363,  3.44963766,  3.96232255],
       [ 0.        ,  6.77790528,  7.72010363,  9.59270556, 11.26676529],
       [ 0.        ,  1.64012195,  1.85741756,  2.03715488,  2.37907545],
       [ 0.        ,  3.19687347,  3.45108679,  5.01896404,  5.05865595],
       [ 0.        ,  1.04403065,  1.25698051,  1.83030052,  1.98997487],
       [ 0.        ,  1.37840488,  1.52643375,  2.04205779,  2.09284495],
       [ 0.        ,  2.15174348,  2.54950976,  2.86530976,  3.07733651],
       [ 0.        ,  1.43178211,  2.39582971,  3.38969025,  3.57770876],
       [ 0.        ,  1.33416641,  1.64012195,  1.89472953,  2.13072758],
       [ 0.        ,  2.00748599,  3.13528308,  3.22800248,  3.57071421],
       [ 0.        ,  2.3515952 ,  2.36220236,  2.47588368,  3.07896086],
       [ 0.        ,  1.9       ,  2.36220236,  2.39582971,  2.62106848],
       [ 0.        ,  1.81383571,  2.11896201,  2.38956063,  2.77488739],
       [ 0.        ,  4.75709996,  5.05667875,  5.45710546,  5.6833089 ],
       [ 0.        ,  0.9539392 ,  1.53297097,  1.64316767,  1.95703858],
       [ 0.        ,  1.31529464,  3.46410162,  3.62491379,  4.07676342],
       [ 0.        ,  1.64316767,  1.8627936 ,  1.94679223,  2.03715488],
       [ 0.        ,  3.18590646,  3.7094474 ,  5.51905789,  6.05805249],
       [ 0.        ,  2.3558438 ,  3.62491379,  3.78945906,  4.73497624],
       [ 0.        ,  1.52643375,  1.60623784,  1.63401346,  2.03224014],
       [ 0.        ,  2.81602557,  2.87576077,  2.94108823,  3.26036808],
       [ 0.        ,  1.57162336,  2.91376046,  3.51140997,  4.1677332 ],
       [ 0.        ,  1.63401346,  1.81659021,  2.12602916,  2.1977261 ],
       [ 0.        ,  1.46628783,  2.34520788,  2.41246762,  2.63248932],
       [ 0.        ,  1.91049732,  2.12602916,  2.3       ,  2.39791576],
       [ 0.        ,  1.83847763,  2.13072758,  2.28035085,  2.34946802],
       [ 0.        ,  0.64807407,  1.20415946,  2.19544984,  2.21585198],
       [ 0.        ,  3.66333182,  3.97114593,  4.49221549,  4.93963561],
       [ 0.        ,  1.73493516,  1.89472953,  2.02731349,  2.29128785],
       [ 0.        ,  1.37840488,  1.61864141,  1.86547581,  2.32163735],
       [ 0.        ,  1.9       ,  2.3515952 ,  2.47790234,  2.88790582],
       [ 0.        ,  1.22474487,  1.46287388,  2.03715488,  2.08326667],
       [ 0.        ,  9.74576831, 17.10380075, 20.80480714, 21.40817601],
       [ 0.        ,  3.43511281,  5.240229  ,  7.05832841,  9.13728625],
       [ 0.        ,  5.13225097,  9.33809402, 11.66876172, 12.08594225],
       [ 0.        ,  1.64620776,  1.81383571,  2.04450483,  2.22261108],
       [ 0.        ,  2.66833281,  2.91376046,  3.5       ,  3.6796739 ],
       [ 0.        ,  1.72336879,  1.74642492,  3.12569992,  3.22800248],
       [ 0.        ,  1.77482393,  2.26495033,  2.3130067 ,  2.85657137],
       [ 0.        ,  3.19687347,  4.03360881,  6.21691242,  7.0107061 ],
       [ 0.        ,  1.87082869,  2.01990099,  3.18590646,  3.21091887],
       [ 0.        ,  1.47648231,  1.53297097,  1.74355958,  1.94422221],
       [ 0.        ,  3.07408523,  3.18590646,  3.54541958,  3.93827373],
       [ 0.        ,  1.96977156,  2.29128785,  2.41246762,  2.4657656 ],
       [ 0.        ,  0.91651514,  1.46287388,  2.11896201,  2.19544984],
       [ 0.        ,  3.44963766,  3.47850543,  3.52987252,  3.53128872],
       [ 0.        ,  3.51140997,  4.25205833,  4.85798312,  6.96706538],
       [ 0.        , 14.33527119, 15.03529182, 15.75055555, 17.10380075],
       [ 0.        ,  0.91651514,  2.08326667,  2.38537209,  2.46170673],
       [ 0.        ,  8.24984848, 15.36066405, 19.64001018, 20.23585926],
       [ 0.        ,  1.40356688,  1.88148877,  2.06155281,  2.20227155],
       [ 0.        ,  2.59807621,  2.73678644,  2.77488739,  3.14801525],
       [ 0.        ,  5.30094331,  9.41116358, 10.95810203, 24.14932711],
       [ 0.        ,  3.07408523,  3.66333182,  4.05832478,  4.36806593],
       [ 0.        ,  1.37840488,  1.94422221,  2.03224014,  2.41039416],
       [ 0.        ,  3.46121366,  6.31981012,  6.69776082,  6.81322244],
       [ 0.        ,  1.3       ,  1.88148877,  2.10475652,  2.10475652],
       [ 0.        ,  2.47790234,  3.45108679,  3.70540146,  3.95979797],
       [ 0.        ,  5.82580467,  7.72010363,  9.63016095, 10.47568614],
       [ 0.        ,  0.64807407,  1.27671453,  2.00499377,  2.08566536],
       [ 0.        ,  2.11423745,  2.15174348,  2.16564078,  2.54950976],
       [ 0.        ,  1.83847763,  2.10475652,  2.12602916,  2.37907545],
       [ 0.        ,  1.396424  ,  1.74642492,  1.94422221,  1.98746069],
       [ 0.        ,  1.98494332,  2.79284801,  3.67831483,  3.73496988],
       [ 0.        ,  1.5       ,  1.97989899,  2.83372546,  2.85657137],
       [ 0.        , 17.20929981, 21.52045539, 23.48382422, 29.31944747],
       [ 0.        ,  1.87082869,  2.1023796 ,  2.83901391,  2.84253408],
       [ 0.        ,  1.1       ,  2.26936114,  2.29128785,  2.44540385],
       [ 0.        ,  1.18743421,  1.88148877,  2.16564078,  2.51793566],
       [ 0.        ,  1.76068169,  4.4609416 ,  5.9983331 ,  6.6633325 ],
       [ 0.        ,  1.74642492,  2.07364414,  2.46981781,  2.7513633 ],
       [ 0.        ,  2.15174348,  2.15174348,  2.52586619,  3.57071421],
       [ 0.        ,  3.46121366,  4.52769257,  5.18266341,  5.9983331 ],
       [ 0.        ,  3.54541958,  3.7094474 ,  4.04227659,  5.63471383],
       [ 0.        ,  8.24984848, 14.73397435, 19.81539805, 20.63274097],
       [ 0.        ,  1.42126704,  2.04450483,  2.07846097,  2.08566536],
       [ 0.        ,  1.46628783,  1.96214169,  2.10475652,  2.19544984],
       [ 0.        ,  1.74642492,  2.12367606,  2.40416306,  2.86006993],
       [ 0.        ,  2.00748599,  2.04205779,  2.6       ,  3.10644491],
       [ 0.        ,  2.06155281,  2.08566536,  2.2737634 ,  2.36008474],
       [ 0.        ,  1.91049732,  2.28035085,  2.58069758,  2.84604989],
       [ 0.        ,  1.33041347,  2.28691933,  2.52388589,  2.63438797],
       [ 0.        ,  1.43178211,  2.62106848,  2.88790582,  3.65650106],
       [ 0.        ,  1.20415946,  1.27671453,  1.42126704,  1.76068169],
       [ 0.        ,  3.27261363,  4.14728827,  4.30929229,  4.34856298],
       [ 0.        , 17.58777985, 17.68700088, 17.93599732, 18.52295873],
       [ 0.        , 17.20929981, 33.86281146, 37.11509127, 42.15103795],
       [ 0.        ,  3.06757233,  3.27719392,  3.7255872 ,  3.9179076 ],
       [ 0.        ,  1.37840488,  1.88148877,  1.97737199,  2.57487864],
       [ 0.        ,  3.6796739 ,  4.02367991,  4.9979996 ,  5.36749476],
       [ 0.        ,  1.40356688,  2.2181073 ,  2.46981781,  2.65518361],
       [ 0.        ,  1.31529464,  2.3558438 ,  4.41021541,  4.71487009],
       [ 0.        ,  1.98494332,  3.77226722,  4.08166633,  4.27784993],
       [ 0.        ,  3.17647603,  3.18590646,  3.37194306,  3.67831483],
       [ 0.        ,  1.94422221,  2.29128785,  2.5019992 ,  2.52784493],
       [ 0.        ,  1.44913767,  2.29128785,  2.51396102,  2.52388589],
       [ 0.        ,  3.78945906,  4.9       ,  5.18266341,  5.25927752],
       [ 0.        ,  1.74642492,  1.94422221,  1.96977156,  2.        ],
       [ 0.        ,  0.9539392 ,  1.40712473,  1.74355958,  1.94679223],
       [ 0.        ,  2.56515107,  4.27784993,  4.4609416 ,  4.52769257]]), array([[  0,  70,  85,  49,  33],
       [  1, 113,   2,  74,  23],
       [  2, 113,   1,  53, 110],
       [  3,  12, 128, 144,  77],
       [  4,  42,  84,  24,  94],
       [  5, 105,  44,  77,  99],
       [  6,  77, 105,   5, 144],
       [  7, 101,  48,  10,  30],
       [  8,  13,  78,  38, 137],
       [  9, 111, 147,  90,  87],
       [ 10,  48, 101,  30,   7],
       [ 11, 126,  53, 113,  29],
       [ 12, 128,  15,   3,   6],
       [ 13,  78,  38,   8, 137],
       [ 14, 132, 108, 124, 128],
       [ 15,  86, 119,  12,  73],
       [ 16,  81,  96,  50, 133],
       [ 17,  91, 122,  39,  43],
       [ 18, 124, 110,  71,  73],
       [ 19, 140,  67,  64, 113],
       [ 20,  80,  57,  51,  93],
       [ 21,  89, 115,  87, 112],
       [ 22,  34, 132,  14, 108],
       [ 23,  74, 129,   1, 110],
       [ 24,  84,   4,  61,  42],
       [ 25,  82,  46,  69,  26],
       [ 26, 109, 120, 117,  55],
       [ 27,  65,  63,  90, 136],
       [ 28, 144, 130, 129,  77],
       [ 29,  37,  53,  36,  31],
       [ 30,  50, 107,  10,  96],
       [ 31,  36,  68,  71,  53],
       [ 32, 130,  57,  13,  77],
       [ 33,  49,  85, 138, 133],
       [ 34,  22, 132,  75, 108],
       [ 35, 132, 125, 124,  75],
       [ 36,  31,  68,  71,  53],
       [ 37,  29,  53,  31,  36],
       [ 38,  78,  13,   8, 137],
       [ 39,  43, 148,  17, 122],
       [ 40, 116, 127,  68,  92],
       [ 41, 121, 104, 148, 118],
       [ 42,   4,  84, 109,  24],
       [ 43,  39, 148,  17, 121],
       [ 44, 117,   5, 137, 105],
       [ 45, 118, 148, 121, 104],
       [ 46,  25,  82, 107,  34],
       [ 47,  83,  95,  85, 138],
       [ 48,  10, 101,   7,  30],
       [ 49,  33, 133,  94,  85],
       [ 50,  30, 107,  46,  82],
       [ 51,  57,  20,  80,  77],
       [ 52,  88, 106,  79, 131],
       [ 53,  29,  37,  36,  31],
       [ 54, 103,  68,  31,  36],
       [ 55, 120, 109, 117, 105],
       [ 56, 131,  60,  79,  59],
       [ 57,  20,  51,  77,  80],
       [ 58, 127, 119,  86, 115],
       [ 59,  79,  60, 111,   9],
       [ 60,  79,  59,  56, 131],
       [ 61,  84,  93,  80, 100],
       [ 62,  26, 120,  55, 109],
       [ 63, 147,  90,  65,   9],
       [ 64, 140,  23,  67, 113],
       [ 65,  63,  27, 147,  90],
       [ 66,  91, 122, 102,  17],
       [ 67, 140,  64, 145,  19],
       [ 68,  54,  31,  36, 103],
       [ 69,  78,  38, 137, 117],
       [ 70,   0,  85,  95,  49],
       [ 71,  31,  36,  73,  68],
       [ 72, 125,  35, 110,  75],
       [ 73, 129,  71,  18, 110],
       [ 74, 110,  23, 129,  53],
       [ 75, 108, 132, 125, 124],
       [ 76, 102,  27, 136,  65],
       [ 77,   6,  57,   5, 144],
       [ 78, 137,  13,  38,  20],
       [ 79,  60,  59, 106, 131],
       [ 80,  20,  93,  51,  97],
       [ 81,  16,  96,  46,   3],
       [ 82,  25,  46,  69,   8],
       [ 83,  47,  95,  85,  70],
       [ 84,  42,  61,  24,   4],
       [ 85,   0,  70,  33, 138],
       [ 86,  15, 119,  12,  58],
       [ 87,   9,  21,  90, 111],
       [ 88,  52, 106,  79, 131],
       [ 89, 115,  21, 142,  87],
       [ 90,   9,  63, 147, 146],
       [ 91, 102,  66, 122,  17],
       [ 92, 146,  40, 147,   9],
       [ 93,  97,  80,  61,  20],
       [ 94,  49,  26,  42,   4],
       [ 95,  70,   0,  85, 138],
       [ 96,  16,  30,  50,  81],
       [ 97,  93,  80,  78,  20],
       [ 98, 123,  41, 104, 121],
       [ 99, 139, 105, 128,   5],
       [100,  93,  97,  61,  80],
       [101,   7,  48,  10,  30],
       [102,  91,  76,  56, 136],
       [103,  54,  36,  68, 110],
       [104, 121,  41,  45, 148],
       [105,   5,  99,   6,  44],
       [106,  79,  52,  59, 131],
       [107,  46,  50,  82,  25],
       [108,  75, 132,  14, 124],
       [109,  26, 120, 117,  55],
       [110,  74, 125,  18,  35],
       [111,   9, 146, 143, 147],
       [112, 141,  21, 142,  65],
       [113,   2,   1,  11,  53],
       [114, 135,  96,  81,  16],
       [115,  89,  21, 103,  54],
       [116,  40,  31,  68,  71],
       [117,  44, 137, 109,  78],
       [118,  45, 148, 121,  43],
       [119,  86,  15,  71,  18],
       [120,  55, 109,  26,   4],
       [121, 104, 148,  41, 118],
       [122,  91,  66,  17,  39],
       [123,  98,  41, 121, 104],
       [124, 132,  35,  18, 108],
       [125,  72,  35, 110,  75],
       [126,  11,  29,  53,  37],
       [127,  58,  40,  92,  68],
       [128,  99, 108,  12,  14],
       [129,  73,  74,  23, 110],
       [130,  32,  57, 144,  77],
       [131,  56,  60,  79,  59],
       [132,  75, 108, 124,  35],
       [133,  49,  33,   0,  94],
       [134,   0,  95, 133,  70],
       [135, 114,  96,  81,  16],
       [136,  27,  65,  63, 147],
       [137,  78, 117,  44,  97],
       [138,  85,  33,  49,  70],
       [139,  99,  44, 128, 105],
       [140,  64,  67,  23,  19],
       [141, 112, 142,  21,  27],
       [142,  21,  89, 115, 112],
       [143, 111, 146,  37,  29],
       [144,  28,  77,   6, 130],
       [145,  67, 100,  20,  80],
       [146, 111,  90,  92,   9],
       [147,  63,   9,  90,  65],
       [148,  43,  39, 118, 121]], dtype=int64))

In [41]:
arr1=result[0]

In [42]:
print(type(arr1))

<class 'numpy.ndarray'>

In [43]:
print(arr1.ndim)

2

In [44]:
arr2=result[1]

In [45]:
print(type(arr2))

<class 'numpy.ndarray'>

In [46]:
print(arr1.ndim)

2

In [47]:
print(arr2)

[[  0  70  85  49  33]
 [  1 113   2  74  23]
 [  2 113   1  53 110]
 [  3  12 128 144  77]
 [  4  42  84  24  94]
 [  5 105  44  77  99]
 [  6  77 105   5 144]
 [  7 101  48  10  30]
 [  8  13  78  38 137]
 [  9 111 147  90  87]
 [ 10  48 101  30   7]
 [ 11 126  53 113  29]
 [ 12 128  15   3   6]
 [ 13  78  38   8 137]
 [ 14 132 108 124 128]
 [ 15  86 119  12  73]
 [ 16  81  96  50 133]
 [ 17  91 122  39  43]
 [ 18 124 110  71  73]
 [ 19 140  67  64 113]
 [ 20  80  57  51  93]
 [ 21  89 115  87 112]
 [ 22  34 132  14 108]
 [ 23  74 129   1 110]
 [ 24  84   4  61  42]
 [ 25  82  46  69  26]
 [ 26 109 120 117  55]
 [ 27  65  63  90 136]
 [ 28 144 130 129  77]
 [ 29  37  53  36  31]
 [ 30  50 107  10  96]
 [ 31  36  68  71  53]
 [ 32 130  57  13  77]
 [ 33  49  85 138 133]
 [ 34  22 132  75 108]
 [ 35 132 125 124  75]
 [ 36  31  68  71  53]
 [ 37  29  53  31  36]
 [ 38  78  13   8 137]
 [ 39  43 148  17 122]
 [ 40 116 127  68  92]
 [ 41 121 104 148 118]
 [ 42   4  84 109  24]
 [ 43  39 148  17 121]
 [ 44 117   5 137 105]
 [ 45 118 148 121 104]
 [ 46  25  82 107  34]
 [ 47  83  95  85 138]
 [ 48  10 101   7  30]
 [ 49  33 133  94  85]
 [ 50  30 107  46  82]
 [ 51  57  20  80  77]
 [ 52  88 106  79 131]
 [ 53  29  37  36  31]
 [ 54 103  68  31  36]
 [ 55 120 109 117 105]
 [ 56 131  60  79  59]
 [ 57  20  51  77  80]
 [ 58 127 119  86 115]
 [ 59  79  60 111   9]
 [ 60  79  59  56 131]
 [ 61  84  93  80 100]
 [ 62  26 120  55 109]
 [ 63 147  90  65   9]
 [ 64 140  23  67 113]
 [ 65  63  27 147  90]
 [ 66  91 122 102  17]
 [ 67 140  64 145  19]
 [ 68  54  31  36 103]
 [ 69  78  38 137 117]
 [ 70   0  85  95  49]
 [ 71  31  36  73  68]
 [ 72 125  35 110  75]
 [ 73 129  71  18 110]
 [ 74 110  23 129  53]
 [ 75 108 132 125 124]
 [ 76 102  27 136  65]
 [ 77   6  57   5 144]
 [ 78 137  13  38  20]
 [ 79  60  59 106 131]
 [ 80  20  93  51  97]
 [ 81  16  96  46   3]
 [ 82  25  46  69   8]
 [ 83  47  95  85  70]
 [ 84  42  61  24   4]
 [ 85   0  70  33 138]
 [ 86  15 119  12  58]
 [ 87   9  21  90 111]
 [ 88  52 106  79 131]
 [ 89 115  21 142  87]
 [ 90   9  63 147 146]
 [ 91 102  66 122  17]
 [ 92 146  40 147   9]
 [ 93  97  80  61  20]
 [ 94  49  26  42   4]
 [ 95  70   0  85 138]
 [ 96  16  30  50  81]
 [ 97  93  80  78  20]
 [ 98 123  41 104 121]
 [ 99 139 105 128   5]
 [100  93  97  61  80]
 [101   7  48  10  30]
 [102  91  76  56 136]
 [103  54  36  68 110]
 [104 121  41  45 148]
 [105   5  99   6  44]
 [106  79  52  59 131]
 [107  46  50  82  25]
 [108  75 132  14 124]
 [109  26 120 117  55]
 [110  74 125  18  35]
 [111   9 146 143 147]
 [112 141  21 142  65]
 [113   2   1  11  53]
 [114 135  96  81  16]
 [115  89  21 103  54]
 [116  40  31  68  71]
 [117  44 137 109  78]
 [118  45 148 121  43]
 [119  86  15  71  18]
 [120  55 109  26   4]
 [121 104 148  41 118]
 [122  91  66  17  39]
 [123  98  41 121 104]
 [124 132  35  18 108]
 [125  72  35 110  75]
 [126  11  29  53  37]
 [127  58  40  92  68]
 [128  99 108  12  14]
 [129  73  74  23 110]
 [130  32  57 144  77]
 [131  56  60  79  59]
 [132  75 108 124  35]
 [133  49  33   0  94]
 [134   0  95 133  70]
 [135 114  96  81  16]
 [136  27  65  63 147]
 [137  78 117  44  97]
 [138  85  33  49  70]
 [139  99  44 128 105]
 [140  64  67  23  19]
 [141 112 142  21  27]
 [142  21  89 115 112]
 [143 111 146  37  29]
 [144  28  77   6 130]
 [145  67 100  20  80]
 [146 111  90  92   9]
 [147  63   9  90  65]
 [148  43  39 118 121]]

In [48]:
print(arr1)

[[ 0.          1.57162336  2.66833281  4.14969878  4.17971291]
 [ 0.          1.97989899  2.39374184  2.60768096  2.64952826]
 [ 0.          1.5         2.39374184  2.96479342  3.06757233]
 [ 0.          2.87402157  2.95127091  3.14801525  3.25269119]
 [ 0.          1.56524758  2.22261108  2.39582971  3.53128872]
 [ 0.          1.3         1.91833261  2.02731349  2.20227155]
 [ 0.          1.73493516  2.10475652  2.21359436  2.51396102]
 [ 0.          5.30094331 13.08166656 14.6116392  27.55340269]
 [ 0.          2.37065392  2.54165301  2.64952826  2.66082694]
 [ 0.          1.396424    1.40712473  1.47648231  1.77482393]
 [ 0.          4.6141088  10.95810203 14.16015537 14.6116392 ]
 [ 0.          1.74642492  2.80891438  2.83372546  3.04959014]
 [ 0.          2.2737634   2.48596058  2.87402157  3.10644491]
 [ 0.          1.61864141  1.98494332  2.37065392  2.81780056]
 [ 0.          1.92613603  2.00499377  2.21585198  2.36008474]
 [ 0.          1.72336879  2.07364414  2.48596058  2.88097206]
 [ 0.          9.74576831 14.33527119 15.87513779 16.14744562]
 [ 0.          3.93827373  4.04227659  4.5         4.88364618]
 [ 0.          2.07846097  2.12602916  2.1977261   2.3       ]
 [ 0.          4.71487009  4.73497624  5.42402065  7.75499839]
 [ 0.          1.22474487  1.33416641  1.85741756  2.19544984]
 [ 0.          2.01990099  2.1023796   2.26495033  2.79284801]
 [ 0.          2.01990099  2.24944438  2.47184142  2.97153159]
 [ 0.          2.13072758  2.58069758  2.64952826  2.78567766]
 [ 0.          2.04450483  2.39582971  3.01827765  3.02489669]
 [ 0.          3.43511281  5.14392846  5.89745708  7.76208735]
 [ 0.          2.11423745  2.52586619  3.24653662  3.34813381]
 [ 0.          1.8627936   2.7513633   2.88790582  3.06757233]
 [ 0.          1.44913767  2.65141472  3.06267857  3.18904374]
 [ 0.          0.94339811  1.04403065  1.87082869  2.10475652]
 [ 0.          6.77790528 13.8960426  14.16015537 15.03529182]
 [ 0.          1.23693169  1.60623784  1.63401346  1.98997487]
 [ 0.          1.33041347  2.48997992  2.86879766  3.17647603]
 [ 0.          1.28452326  3.5         4.02367991  4.14728827]
 [ 0.          2.01990099  3.48998567  3.65102725  3.80131556]
 [ 0.          1.76068169  1.96214169  2.04450483  2.31732605]
 [ 0.          1.23693169  1.63401346  1.81659021  1.83030052]
 [ 0.          0.94339811  1.25698051  2.13072758  2.23383079]
 [ 0.          1.86547581  1.98494332  2.64952826  2.77488739]
 [ 0.          2.25388553  4.27784993  4.5         5.63471383]
 [ 0.          1.1         2.04205779  2.16333077  2.29128785]
 [ 0.          5.18266341  6.31981012  9.36269192 10.2342562 ]
 [ 0.          1.56524758  1.64620776  2.94108823  3.02489669]
 [ 0.          2.25388553  2.56515107  4.88364618  6.58331224]
 [ 0.          1.18743421  1.91833261  1.97737199  2.10475652]
 [ 0.          1.76068169  5.82923666  6.58634952  6.69776082]
 [ 0.          5.14392846  5.240229    5.82580467  9.06311205]
 [ 0.          5.13225097  7.33348485  7.91075218  8.30060239]
 [ 0.          4.6141088   9.41116358 13.08166656 16.19320845]
 [ 0.          1.28452326  3.27261363  3.44963766  3.96232255]
 [ 0.          6.77790528  7.72010363  9.59270556 11.26676529]
 [ 0.          1.64012195  1.85741756  2.03715488  2.37907545]
 [ 0.          3.19687347  3.45108679  5.01896404  5.05865595]
 [ 0.          1.04403065  1.25698051  1.83030052  1.98997487]
 [ 0.          1.37840488  1.52643375  2.04205779  2.09284495]
 [ 0.          2.15174348  2.54950976  2.86530976  3.07733651]
 [ 0.          1.43178211  2.39582971  3.38969025  3.57770876]
 [ 0.          1.33416641  1.64012195  1.89472953  2.13072758]
 [ 0.          2.00748599  3.13528308  3.22800248  3.57071421]
 [ 0.          2.3515952   2.36220236  2.47588368  3.07896086]
 [ 0.          1.9         2.36220236  2.39582971  2.62106848]
 [ 0.          1.81383571  2.11896201  2.38956063  2.77488739]
 [ 0.          4.75709996  5.05667875  5.45710546  5.6833089 ]
 [ 0.          0.9539392   1.53297097  1.64316767  1.95703858]
 [ 0.          1.31529464  3.46410162  3.62491379  4.07676342]
 [ 0.          1.64316767  1.8627936   1.94679223  2.03715488]
 [ 0.          3.18590646  3.7094474   5.51905789  6.05805249]
 [ 0.          2.3558438   3.62491379  3.78945906  4.73497624]
 [ 0.          1.52643375  1.60623784  1.63401346  2.03224014]
 [ 0.          2.81602557  2.87576077  2.94108823  3.26036808]
 [ 0.          1.57162336  2.91376046  3.51140997  4.1677332 ]
 [ 0.          1.63401346  1.81659021  2.12602916  2.1977261 ]
 [ 0.          1.46628783  2.34520788  2.41246762  2.63248932]
 [ 0.          1.91049732  2.12602916  2.3         2.39791576]
 [ 0.          1.83847763  2.13072758  2.28035085  2.34946802]
 [ 0.          0.64807407  1.20415946  2.19544984  2.21585198]
 [ 0.          3.66333182  3.97114593  4.49221549  4.93963561]
 [ 0.          1.73493516  1.89472953  2.02731349  2.29128785]
 [ 0.          1.37840488  1.61864141  1.86547581  2.32163735]
 [ 0.          1.9         2.3515952   2.47790234  2.88790582]
 [ 0.          1.22474487  1.46287388  2.03715488  2.08326667]
 [ 0.          9.74576831 17.10380075 20.80480714 21.40817601]
 [ 0.          3.43511281  5.240229    7.05832841  9.13728625]
 [ 0.          5.13225097  9.33809402 11.66876172 12.08594225]
 [ 0.          1.64620776  1.81383571  2.04450483  2.22261108]
 [ 0.          2.66833281  2.91376046  3.5         3.6796739 ]
 [ 0.          1.72336879  1.74642492  3.12569992  3.22800248]
 [ 0.          1.77482393  2.26495033  2.3130067   2.85657137]
 [ 0.          3.19687347  4.03360881  6.21691242  7.0107061 ]
 [ 0.          1.87082869  2.01990099  3.18590646  3.21091887]
 [ 0.          1.47648231  1.53297097  1.74355958  1.94422221]
 [ 0.          3.07408523  3.18590646  3.54541958  3.93827373]
 [ 0.          1.96977156  2.29128785  2.41246762  2.4657656 ]
 [ 0.          0.91651514  1.46287388  2.11896201  2.19544984]
 [ 0.          3.44963766  3.47850543  3.52987252  3.53128872]
 [ 0.          3.51140997  4.25205833  4.85798312  6.96706538]
 [ 0.         14.33527119 15.03529182 15.75055555 17.10380075]
 [ 0.          0.91651514  2.08326667  2.38537209  2.46170673]
 [ 0.          8.24984848 15.36066405 19.64001018 20.23585926]
 [ 0.          1.40356688  1.88148877  2.06155281  2.20227155]
 [ 0.          2.59807621  2.73678644  2.77488739  3.14801525]
 [ 0.          5.30094331  9.41116358 10.95810203 24.14932711]
 [ 0.          3.07408523  3.66333182  4.05832478  4.36806593]
 [ 0.          1.37840488  1.94422221  2.03224014  2.41039416]
 [ 0.          3.46121366  6.31981012  6.69776082  6.81322244]
 [ 0.          1.3         1.88148877  2.10475652  2.10475652]
 [ 0.          2.47790234  3.45108679  3.70540146  3.95979797]
 [ 0.          5.82580467  7.72010363  9.63016095 10.47568614]
 [ 0.          0.64807407  1.27671453  2.00499377  2.08566536]
 [ 0.          2.11423745  2.15174348  2.16564078  2.54950976]
 [ 0.          1.83847763  2.10475652  2.12602916  2.37907545]
 [ 0.          1.396424    1.74642492  1.94422221  1.98746069]
 [ 0.          1.98494332  2.79284801  3.67831483  3.73496988]
 [ 0.          1.5         1.97989899  2.83372546  2.85657137]
 [ 0.         17.20929981 21.52045539 23.48382422 29.31944747]
 [ 0.          1.87082869  2.1023796   2.83901391  2.84253408]
 [ 0.          1.1         2.26936114  2.29128785  2.44540385]
 [ 0.          1.18743421  1.88148877  2.16564078  2.51793566]
 [ 0.          1.76068169  4.4609416   5.9983331   6.6633325 ]
 [ 0.          1.74642492  2.07364414  2.46981781  2.7513633 ]
 [ 0.          2.15174348  2.15174348  2.52586619  3.57071421]
 [ 0.          3.46121366  4.52769257  5.18266341  5.9983331 ]
 [ 0.          3.54541958  3.7094474   4.04227659  5.63471383]
 [ 0.          8.24984848 14.73397435 19.81539805 20.63274097]
 [ 0.          1.42126704  2.04450483  2.07846097  2.08566536]
 [ 0.          1.46628783  1.96214169  2.10475652  2.19544984]
 [ 0.          1.74642492  2.12367606  2.40416306  2.86006993]
 [ 0.          2.00748599  2.04205779  2.6         3.10644491]
 [ 0.          2.06155281  2.08566536  2.2737634   2.36008474]
 [ 0.          1.91049732  2.28035085  2.58069758  2.84604989]
 [ 0.          1.33041347  2.28691933  2.52388589  2.63438797]
 [ 0.          1.43178211  2.62106848  2.88790582  3.65650106]
 [ 0.          1.20415946  1.27671453  1.42126704  1.76068169]
 [ 0.          3.27261363  4.14728827  4.30929229  4.34856298]
 [ 0.         17.58777985 17.68700088 17.93599732 18.52295873]
 [ 0.         17.20929981 33.86281146 37.11509127 42.15103795]
 [ 0.          3.06757233  3.27719392  3.7255872   3.9179076 ]
 [ 0.          1.37840488  1.88148877  1.97737199  2.57487864]
 [ 0.          3.6796739   4.02367991  4.9979996   5.36749476]
 [ 0.          1.40356688  2.2181073   2.46981781  2.65518361]
 [ 0.          1.31529464  2.3558438   4.41021541  4.71487009]
 [ 0.          1.98494332  3.77226722  4.08166633  4.27784993]
 [ 0.          3.17647603  3.18590646  3.37194306  3.67831483]
 [ 0.          1.94422221  2.29128785  2.5019992   2.52784493]
 [ 0.          1.44913767  2.29128785  2.51396102  2.52388589]
 [ 0.          3.78945906  4.9         5.18266341  5.25927752]
 [ 0.          1.74642492  1.94422221  1.96977156  2.        ]
 [ 0.          0.9539392   1.40712473  1.74355958  1.94679223]
 [ 0.          2.56515107  4.27784993  4.4609416   4.52769257]]

In [49]:
#print(arr1)

In [50]:
print(arr1.size)

745

In [51]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0.         1.57162336 2.66833281 4.14969878 4.17971291]   12
[0.         1.97989899 2.39374184 2.60768096 2.64952826]   9
[0.         1.5        2.39374184 2.96479342 3.06757233]   9
[0.         2.87402157 2.95127091 3.14801525 3.25269119]   12
[0.         1.56524758 2.22261108 2.39582971 3.53128872]   9
[0.         1.3        1.91833261 2.02731349 2.20227155]   7
[0.         1.73493516 2.10475652 2.21359436 2.51396102]   8
[ 0.          5.30094331 13.08166656 14.6116392  27.55340269]   60
[0.         2.37065392 2.54165301 2.64952826 2.66082694]   10
[0.         1.396424   1.40712473 1.47648231 1.77482393]   6
[ 0.          4.6141088  10.95810203 14.16015537 14.6116392 ]   44
[0.         1.74642492 2.80891438 2.83372546 3.04959014]   10
[0.         2.2737634  2.48596058 2.87402157 3.10644491]   10
[0.         1.61864141 1.98494332 2.37065392 2.81780056]   8
[0.         1.92613603 2.00499377 2.21585198 2.36008474]   8
[0.         1.72336879 2.07364414 2.48596058 2.88097206]   9
[ 0.          9.74576831 14.33527119 15.87513779 16.14744562]   56
[0.         3.93827373 4.04227659 4.5        4.88364618]   17
[0.         2.07846097 2.12602916 2.1977261  2.3       ]   8
[0.         4.71487009 4.73497624 5.42402065 7.75499839]   22
[0.         1.22474487 1.33416641 1.85741756 2.19544984]   6
[0.         2.01990099 2.1023796  2.26495033 2.79284801]   9
[0.         2.01990099 2.24944438 2.47184142 2.97153159]   9
[0.         2.13072758 2.58069758 2.64952826 2.78567766]   10
[0.         2.04450483 2.39582971 3.01827765 3.02489669]   10
[0.         3.43511281 5.14392846 5.89745708 7.76208735]   22
[0.         2.11423745 2.52586619 3.24653662 3.34813381]   11
[0.         1.8627936  2.7513633  2.88790582 3.06757233]   10
[0.         1.44913767 2.65141472 3.06267857 3.18904374]   10
[0.         0.94339811 1.04403065 1.87082869 2.10475652]   5
[ 0.          6.77790528 13.8960426  14.16015537 15.03529182]   49
[0.         1.23693169 1.60623784 1.63401346 1.98997487]   6
[0.         1.33041347 2.48997992 2.86879766 3.17647603]   9
[0.         1.28452326 3.5        4.02367991 4.14728827]   12
[0.         2.01990099 3.48998567 3.65102725 3.80131556]   12
[0.         1.76068169 1.96214169 2.04450483 2.31732605]   8
[0.         1.23693169 1.63401346 1.81659021 1.83030052]   6
[0.         0.94339811 1.25698051 2.13072758 2.23383079]   6
[0.         1.86547581 1.98494332 2.64952826 2.77488739]   9
[0.         2.25388553 4.27784993 4.5        5.63471383]   16
[0.         1.1        2.04205779 2.16333077 2.29128785]   7
[ 0.          5.18266341  6.31981012  9.36269192 10.2342562 ]   31
[0.         1.56524758 1.64620776 2.94108823 3.02489669]   9
[0.         2.25388553 2.56515107 4.88364618 6.58331224]   16
[0.         1.18743421 1.91833261 1.97737199 2.10475652]   7
[0.         1.76068169 5.82923666 6.58634952 6.69776082]   20
[0.         5.14392846 5.240229   5.82580467 9.06311205]   25
[0.         5.13225097 7.33348485 7.91075218 8.30060239]   28
[ 0.          4.6141088   9.41116358 13.08166656 16.19320845]   43
[0.         1.28452326 3.27261363 3.44963766 3.96232255]   11
[ 0.          6.77790528  7.72010363  9.59270556 11.26676529]   35
[0.         1.64012195 1.85741756 2.03715488 2.37907545]   7
[0.         3.19687347 3.45108679 5.01896404 5.05865595]   16
[0.         1.04403065 1.25698051 1.83030052 1.98997487]   6
[0.         1.37840488 1.52643375 2.04205779 2.09284495]   7
[0.         2.15174348 2.54950976 2.86530976 3.07733651]   10
[0.         1.43178211 2.39582971 3.38969025 3.57770876]   10
[0.         1.33416641 1.64012195 1.89472953 2.13072758]   6
[0.         2.00748599 3.13528308 3.22800248 3.57071421]   11
[0.         2.3515952  2.36220236 2.47588368 3.07896086]   10
[0.         1.9        2.36220236 2.39582971 2.62106848]   9
[0.         1.81383571 2.11896201 2.38956063 2.77488739]   9
[0.         4.75709996 5.05667875 5.45710546 5.6833089 ]   20
[0.         0.9539392  1.53297097 1.64316767 1.95703858]   6
[0.         1.31529464 3.46410162 3.62491379 4.07676342]   12
[0.         1.64316767 1.8627936  1.94679223 2.03715488]   7
[0.         3.18590646 3.7094474  5.51905789 6.05805249]   18
[0.         2.3558438  3.62491379 3.78945906 4.73497624]   14
[0.         1.52643375 1.60623784 1.63401346 2.03224014]   6
[0.         2.81602557 2.87576077 2.94108823 3.26036808]   11
[0.         1.57162336 2.91376046 3.51140997 4.1677332 ]   12
[0.         1.63401346 1.81659021 2.12602916 2.1977261 ]   7
[0.         1.46628783 2.34520788 2.41246762 2.63248932]   8
[0.         1.91049732 2.12602916 2.3        2.39791576]   8
[0.         1.83847763 2.13072758 2.28035085 2.34946802]   8
[0.         0.64807407 1.20415946 2.19544984 2.21585198]   6
[0.         3.66333182 3.97114593 4.49221549 4.93963561]   17
[0.         1.73493516 1.89472953 2.02731349 2.29128785]   7
[0.         1.37840488 1.61864141 1.86547581 2.32163735]   7
[0.         1.9        2.3515952  2.47790234 2.88790582]   9
[0.         1.22474487 1.46287388 2.03715488 2.08326667]   6
[ 0.          9.74576831 17.10380075 20.80480714 21.40817601]   69
[0.         3.43511281 5.240229   7.05832841 9.13728625]   24
[ 0.          5.13225097  9.33809402 11.66876172 12.08594225]   38
[0.         1.64620776 1.81383571 2.04450483 2.22261108]   7
[0.         2.66833281 2.91376046 3.5        3.6796739 ]   12
[0.         1.72336879 1.74642492 3.12569992 3.22800248]   9
[0.         1.77482393 2.26495033 2.3130067  2.85657137]   9
[0.         3.19687347 4.03360881 6.21691242 7.0107061 ]   20
[0.         1.87082869 2.01990099 3.18590646 3.21091887]   10
[0.         1.47648231 1.53297097 1.74355958 1.94422221]   6
[0.         3.07408523 3.18590646 3.54541958 3.93827373]   13
[0.         1.96977156 2.29128785 2.41246762 2.4657656 ]   9
[0.         0.91651514 1.46287388 2.11896201 2.19544984]   6
[0.         3.44963766 3.47850543 3.52987252 3.53128872]   13
[0.         3.51140997 4.25205833 4.85798312 6.96706538]   19
[ 0.         14.33527119 15.03529182 15.75055555 17.10380075]   62
[0.         0.91651514 2.08326667 2.38537209 2.46170673]   7
[ 0.          8.24984848 15.36066405 19.64001018 20.23585926]   63
[0.         1.40356688 1.88148877 2.06155281 2.20227155]   7
[0.         2.59807621 2.73678644 2.77488739 3.14801525]   11
[ 0.          5.30094331  9.41116358 10.95810203 24.14932711]   49
[0.         3.07408523 3.66333182 4.05832478 4.36806593]   15
[0.         1.37840488 1.94422221 2.03224014 2.41039416]   7
[0.         3.46121366 6.31981012 6.69776082 6.81322244]   23
[0.         1.3        1.88148877 2.10475652 2.10475652]   7
[0.         2.47790234 3.45108679 3.70540146 3.95979797]   13
[ 0.          5.82580467  7.72010363  9.63016095 10.47568614]   33
[0.         0.64807407 1.27671453 2.00499377 2.08566536]   6
[0.         2.11423745 2.15174348 2.16564078 2.54950976]   8
[0.         1.83847763 2.10475652 2.12602916 2.37907545]   8
[0.         1.396424   1.74642492 1.94422221 1.98746069]   7
[0.         1.98494332 2.79284801 3.67831483 3.73496988]   12
[0.         1.5        1.97989899 2.83372546 2.85657137]   9
[ 0.         17.20929981 21.52045539 23.48382422 29.31944747]   91
[0.         1.87082869 2.1023796  2.83901391 2.84253408]   9
[0.         1.1        2.26936114 2.29128785 2.44540385]   8
[0.         1.18743421 1.88148877 2.16564078 2.51793566]   7
[0.         1.76068169 4.4609416  5.9983331  6.6633325 ]   18
[0.         1.74642492 2.07364414 2.46981781 2.7513633 ]   9
[0.         2.15174348 2.15174348 2.52586619 3.57071421]   10
[0.         3.46121366 4.52769257 5.18266341 5.9983331 ]   19
[0.         3.54541958 3.7094474  4.04227659 5.63471383]   16
[ 0.          8.24984848 14.73397435 19.81539805 20.63274097]   63
[0.         1.42126704 2.04450483 2.07846097 2.08566536]   7
[0.         1.46628783 1.96214169 2.10475652 2.19544984]   7
[0.         1.74642492 2.12367606 2.40416306 2.86006993]   9
[0.         2.00748599 2.04205779 2.6        3.10644491]   9
[0.         2.06155281 2.08566536 2.2737634  2.36008474]   8
[0.         1.91049732 2.28035085 2.58069758 2.84604989]   9
[0.         1.33041347 2.28691933 2.52388589 2.63438797]   8
[0.         1.43178211 2.62106848 2.88790582 3.65650106]   10
[0.         1.20415946 1.27671453 1.42126704 1.76068169]   5
[0.         3.27261363 4.14728827 4.30929229 4.34856298]   16
[ 0.         17.58777985 17.68700088 17.93599732 18.52295873]   71
[ 0.         17.20929981 33.86281146 37.11509127 42.15103795]   130
[0.         3.06757233 3.27719392 3.7255872  3.9179076 ]   13
[0.         1.37840488 1.88148877 1.97737199 2.57487864]   7
[0.         3.6796739  4.02367991 4.9979996  5.36749476]   18
[0.         1.40356688 2.2181073  2.46981781 2.65518361]   8
[0.         1.31529464 2.3558438  4.41021541 4.71487009]   12
[0.         1.98494332 3.77226722 4.08166633 4.27784993]   14
[0.         3.17647603 3.18590646 3.37194306 3.67831483]   13
[0.         1.94422221 2.29128785 2.5019992  2.52784493]   9
[0.         1.44913767 2.29128785 2.51396102 2.52388589]   8
[0.         3.78945906 4.9        5.18266341 5.25927752]   19
[0.         1.74642492 1.94422221 1.96977156 2.        ]   7
[0.         0.9539392  1.40712473 1.74355958 1.94679223]   6
[0.         2.56515107 4.27784993 4.4609416  4.52769257]   15

In [52]:
print(len(addVal))

149

In [53]:
print(addVal)

[12, 9, 9, 12, 9, 7, 8, 60, 10, 6, 44, 10, 10, 8, 8, 9, 56, 17, 8, 22, 6, 9, 9, 10, 10, 22, 11, 10, 10, 5, 49, 6, 9, 12, 12, 8, 6, 6, 9, 16, 7, 31, 9, 16, 7, 20, 25, 28, 43, 11, 35, 7, 16, 6, 7, 10, 10, 6, 11, 10, 9, 9, 20, 6, 12, 7, 18, 14, 6, 11, 12, 7, 8, 8, 8, 6, 17, 7, 7, 9, 6, 69, 24, 38, 7, 12, 9, 9, 20, 10, 6, 13, 9, 6, 13, 19, 62, 7, 63, 7, 11, 49, 15, 7, 23, 7, 13, 33, 6, 8, 8, 7, 12, 9, 91, 9, 8, 7, 18, 9, 10, 19, 16, 63, 7, 7, 9, 9, 8, 9, 8, 10, 5, 16, 71, 130, 13, 7, 18, 8, 12, 14, 13, 9, 8, 19, 7, 6, 15]

In [54]:
arr3=np.array(addVal)

In [55]:
print(type(arr3))

<class 'numpy.ndarray'>

In [56]:
print(arr3.size)

149

In [57]:
print(arr3)

[ 12   9   9  12   9   7   8  60  10   6  44  10  10   8   8   9  56  17
   8  22   6   9   9  10  10  22  11  10  10   5  49   6   9  12  12   8
   6   6   9  16   7  31   9  16   7  20  25  28  43  11  35   7  16   6
   7  10  10   6  11  10   9   9  20   6  12   7  18  14   6  11  12   7
   8   8   8   6  17   7   7   9   6  69  24  38   7  12   9   9  20  10
   6  13   9   6  13  19  62   7  63   7  11  49  15   7  23   7  13  33
   6   8   8   7  12   9  91   9   8   7  18   9  10  19  16  63   7   7
   9   9   8   9   8  10   5  16  71 130  13   7  18   8  12  14  13   9
   8  19   7   6  15]

In [58]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   12
2   9
3   9
4   12
5   9
6   7
7   8
8   60
9   10
10   6
11   44
12   10
13   10
14   8
15   8
16   9
17   56
18   17
19   8
20   22
21   6
22   9
23   9
24   10
25   10
26   22
27   11
28   10
29   10
30   5
31   49
32   6
33   9
34   12
35   12
36   8
37   6
38   6
39   9
40   16
41   7
42   31
43   9
44   16
45   7
46   20
47   25
48   28
49   43
50   11
51   35
52   7
53   16
54   6
55   7
56   10
57   10
58   6
59   11
60   10
61   9
62   9
63   20
64   6
65   12
66   7
67   18
68   14
69   6
70   11
71   12
72   7
73   8
74   8
75   8
76   6
77   17
78   7
79   7
80   9
81   6
82   69
83   24
84   38
85   7
86   12
87   9
88   9
89   20
90   10
91   6
92   13
93   9
94   6
95   13
96   19
97   62
98   7
99   63
100   7
101   11
102   49
103   15
104   7
105   23
106   7
107   13
108   33
109   6
110   8
111   8
112   7
113   12
114   9
115   91
116   9
117   8
118   7
119   18
120   9
121   10
122   19
123   16
124   63
125   7
126   7
127   9
128   9
129   8
130   9
131   8
132   10
133   5
134   16
135   71
136   130
137   13
138   7
139   18
140   8
141   12
142   14
143   13
144   9
145   8
146   19
147   7
148   6
149   15

In [59]:
newarr = arr3.reshape(149, 1)

In [60]:
print(newarr.ndim)

2

In [61]:
new_arr2=np.append(arr2, newarr, axis=1)

In [62]:
print(type(new_arr2))

<class 'numpy.ndarray'>

In [63]:
print(new_arr2)

[[  0  70  85  49  33  12]
 [  1 113   2  74  23   9]
 [  2 113   1  53 110   9]
 [  3  12 128 144  77  12]
 [  4  42  84  24  94   9]
 [  5 105  44  77  99   7]
 [  6  77 105   5 144   8]
 [  7 101  48  10  30  60]
 [  8  13  78  38 137  10]
 [  9 111 147  90  87   6]
 [ 10  48 101  30   7  44]
 [ 11 126  53 113  29  10]
 [ 12 128  15   3   6  10]
 [ 13  78  38   8 137   8]
 [ 14 132 108 124 128   8]
 [ 15  86 119  12  73   9]
 [ 16  81  96  50 133  56]
 [ 17  91 122  39  43  17]
 [ 18 124 110  71  73   8]
 [ 19 140  67  64 113  22]
 [ 20  80  57  51  93   6]
 [ 21  89 115  87 112   9]
 [ 22  34 132  14 108   9]
 [ 23  74 129   1 110  10]
 [ 24  84   4  61  42  10]
 [ 25  82  46  69  26  22]
 [ 26 109 120 117  55  11]
 [ 27  65  63  90 136  10]
 [ 28 144 130 129  77  10]
 [ 29  37  53  36  31   5]
 [ 30  50 107  10  96  49]
 [ 31  36  68  71  53   6]
 [ 32 130  57  13  77   9]
 [ 33  49  85 138 133  12]
 [ 34  22 132  75 108  12]
 [ 35 132 125 124  75   8]
 [ 36  31  68  71  53   6]
 [ 37  29  53  31  36   6]
 [ 38  78  13   8 137   9]
 [ 39  43 148  17 122  16]
 [ 40 116 127  68  92   7]
 [ 41 121 104 148 118  31]
 [ 42   4  84 109  24   9]
 [ 43  39 148  17 121  16]
 [ 44 117   5 137 105   7]
 [ 45 118 148 121 104  20]
 [ 46  25  82 107  34  25]
 [ 47  83  95  85 138  28]
 [ 48  10 101   7  30  43]
 [ 49  33 133  94  85  11]
 [ 50  30 107  46  82  35]
 [ 51  57  20  80  77   7]
 [ 52  88 106  79 131  16]
 [ 53  29  37  36  31   6]
 [ 54 103  68  31  36   7]
 [ 55 120 109 117 105  10]
 [ 56 131  60  79  59  10]
 [ 57  20  51  77  80   6]
 [ 58 127 119  86 115  11]
 [ 59  79  60 111   9  10]
 [ 60  79  59  56 131   9]
 [ 61  84  93  80 100   9]
 [ 62  26 120  55 109  20]
 [ 63 147  90  65   9   6]
 [ 64 140  23  67 113  12]
 [ 65  63  27 147  90   7]
 [ 66  91 122 102  17  18]
 [ 67 140  64 145  19  14]
 [ 68  54  31  36 103   6]
 [ 69  78  38 137 117  11]
 [ 70   0  85  95  49  12]
 [ 71  31  36  73  68   7]
 [ 72 125  35 110  75   8]
 [ 73 129  71  18 110   8]
 [ 74 110  23 129  53   8]
 [ 75 108 132 125 124   6]
 [ 76 102  27 136  65  17]
 [ 77   6  57   5 144   7]
 [ 78 137  13  38  20   7]
 [ 79  60  59 106 131   9]
 [ 80  20  93  51  97   6]
 [ 81  16  96  46   3  69]
 [ 82  25  46  69   8  24]
 [ 83  47  95  85  70  38]
 [ 84  42  61  24   4   7]
 [ 85   0  70  33 138  12]
 [ 86  15 119  12  58   9]
 [ 87   9  21  90 111   9]
 [ 88  52 106  79 131  20]
 [ 89 115  21 142  87  10]
 [ 90   9  63 147 146   6]
 [ 91 102  66 122  17  13]
 [ 92 146  40 147   9   9]
 [ 93  97  80  61  20   6]
 [ 94  49  26  42   4  13]
 [ 95  70   0  85 138  19]
 [ 96  16  30  50  81  62]
 [ 97  93  80  78  20   7]
 [ 98 123  41 104 121  63]
 [ 99 139 105 128   5   7]
 [100  93  97  61  80  11]
 [101   7  48  10  30  49]
 [102  91  76  56 136  15]
 [103  54  36  68 110   7]
 [104 121  41  45 148  23]
 [105   5  99   6  44   7]
 [106  79  52  59 131  13]
 [107  46  50  82  25  33]
 [108  75 132  14 124   6]
 [109  26 120 117  55   8]
 [110  74 125  18  35   8]
 [111   9 146 143 147   7]
 [112 141  21 142  65  12]
 [113   2   1  11  53   9]
 [114 135  96  81  16  91]
 [115  89  21 103  54   9]
 [116  40  31  68  71   8]
 [117  44 137 109  78   7]
 [118  45 148 121  43  18]
 [119  86  15  71  18   9]
 [120  55 109  26   4  10]
 [121 104 148  41 118  19]
 [122  91  66  17  39  16]
 [123  98  41 121 104  63]
 [124 132  35  18 108   7]
 [125  72  35 110  75   7]
 [126  11  29  53  37   9]
 [127  58  40  92  68   9]
 [128  99 108  12  14   8]
 [129  73  74  23 110   9]
 [130  32  57 144  77   8]
 [131  56  60  79  59  10]
 [132  75 108 124  35   5]
 [133  49  33   0  94  16]
 [134   0  95 133  70  71]
 [135 114  96  81  16 130]
 [136  27  65  63 147  13]
 [137  78 117  44  97   7]
 [138  85  33  49  70  18]
 [139  99  44 128 105   8]
 [140  64  67  23  19  12]
 [141 112 142  21  27  14]
 [142  21  89 115 112  13]
 [143 111 146  37  29   9]
 [144  28  77   6 130   8]
 [145  67 100  20  80  19]
 [146 111  90  92   9   7]
 [147  63   9  90  65   6]
 [148  43  39 118 121  15]]

In [64]:
print(new_arr2[0])

[ 0 70 85 49 33 12]

In [65]:
print(type(Y_train))

<class 'pandas.core.series.Series'>

In [66]:
arr2

array([[  0,  70,  85,  49,  33],
       [  1, 113,   2,  74,  23],
       [  2, 113,   1,  53, 110],
       [  3,  12, 128, 144,  77],
       [  4,  42,  84,  24,  94],
       [  5, 105,  44,  77,  99],
       [  6,  77, 105,   5, 144],
       [  7, 101,  48,  10,  30],
       [  8,  13,  78,  38, 137],
       [  9, 111, 147,  90,  87],
       [ 10,  48, 101,  30,   7],
       [ 11, 126,  53, 113,  29],
       [ 12, 128,  15,   3,   6],
       [ 13,  78,  38,   8, 137],
       [ 14, 132, 108, 124, 128],
       [ 15,  86, 119,  12,  73],
       [ 16,  81,  96,  50, 133],
       [ 17,  91, 122,  39,  43],
       [ 18, 124, 110,  71,  73],
       [ 19, 140,  67,  64, 113],
       [ 20,  80,  57,  51,  93],
       [ 21,  89, 115,  87, 112],
       [ 22,  34, 132,  14, 108],
       [ 23,  74, 129,   1, 110],
       [ 24,  84,   4,  61,  42],
       [ 25,  82,  46,  69,  26],
       [ 26, 109, 120, 117,  55],
       [ 27,  65,  63,  90, 136],
       [ 28, 144, 130, 129,  77],
       [ 29,  37,  53,  36,  31],
       [ 30,  50, 107,  10,  96],
       [ 31,  36,  68,  71,  53],
       [ 32, 130,  57,  13,  77],
       [ 33,  49,  85, 138, 133],
       [ 34,  22, 132,  75, 108],
       [ 35, 132, 125, 124,  75],
       [ 36,  31,  68,  71,  53],
       [ 37,  29,  53,  31,  36],
       [ 38,  78,  13,   8, 137],
       [ 39,  43, 148,  17, 122],
       [ 40, 116, 127,  68,  92],
       [ 41, 121, 104, 148, 118],
       [ 42,   4,  84, 109,  24],
       [ 43,  39, 148,  17, 121],
       [ 44, 117,   5, 137, 105],
       [ 45, 118, 148, 121, 104],
       [ 46,  25,  82, 107,  34],
       [ 47,  83,  95,  85, 138],
       [ 48,  10, 101,   7,  30],
       [ 49,  33, 133,  94,  85],
       [ 50,  30, 107,  46,  82],
       [ 51,  57,  20,  80,  77],
       [ 52,  88, 106,  79, 131],
       [ 53,  29,  37,  36,  31],
       [ 54, 103,  68,  31,  36],
       [ 55, 120, 109, 117, 105],
       [ 56, 131,  60,  79,  59],
       [ 57,  20,  51,  77,  80],
       [ 58, 127, 119,  86, 115],
       [ 59,  79,  60, 111,   9],
       [ 60,  79,  59,  56, 131],
       [ 61,  84,  93,  80, 100],
       [ 62,  26, 120,  55, 109],
       [ 63, 147,  90,  65,   9],
       [ 64, 140,  23,  67, 113],
       [ 65,  63,  27, 147,  90],
       [ 66,  91, 122, 102,  17],
       [ 67, 140,  64, 145,  19],
       [ 68,  54,  31,  36, 103],
       [ 69,  78,  38, 137, 117],
       [ 70,   0,  85,  95,  49],
       [ 71,  31,  36,  73,  68],
       [ 72, 125,  35, 110,  75],
       [ 73, 129,  71,  18, 110],
       [ 74, 110,  23, 129,  53],
       [ 75, 108, 132, 125, 124],
       [ 76, 102,  27, 136,  65],
       [ 77,   6,  57,   5, 144],
       [ 78, 137,  13,  38,  20],
       [ 79,  60,  59, 106, 131],
       [ 80,  20,  93,  51,  97],
       [ 81,  16,  96,  46,   3],
       [ 82,  25,  46,  69,   8],
       [ 83,  47,  95,  85,  70],
       [ 84,  42,  61,  24,   4],
       [ 85,   0,  70,  33, 138],
       [ 86,  15, 119,  12,  58],
       [ 87,   9,  21,  90, 111],
       [ 88,  52, 106,  79, 131],
       [ 89, 115,  21, 142,  87],
       [ 90,   9,  63, 147, 146],
       [ 91, 102,  66, 122,  17],
       [ 92, 146,  40, 147,   9],
       [ 93,  97,  80,  61,  20],
       [ 94,  49,  26,  42,   4],
       [ 95,  70,   0,  85, 138],
       [ 96,  16,  30,  50,  81],
       [ 97,  93,  80,  78,  20],
       [ 98, 123,  41, 104, 121],
       [ 99, 139, 105, 128,   5],
       [100,  93,  97,  61,  80],
       [101,   7,  48,  10,  30],
       [102,  91,  76,  56, 136],
       [103,  54,  36,  68, 110],
       [104, 121,  41,  45, 148],
       [105,   5,  99,   6,  44],
       [106,  79,  52,  59, 131],
       [107,  46,  50,  82,  25],
       [108,  75, 132,  14, 124],
       [109,  26, 120, 117,  55],
       [110,  74, 125,  18,  35],
       [111,   9, 146, 143, 147],
       [112, 141,  21, 142,  65],
       [113,   2,   1,  11,  53],
       [114, 135,  96,  81,  16],
       [115,  89,  21, 103,  54],
       [116,  40,  31,  68,  71],
       [117,  44, 137, 109,  78],
       [118,  45, 148, 121,  43],
       [119,  86,  15,  71,  18],
       [120,  55, 109,  26,   4],
       [121, 104, 148,  41, 118],
       [122,  91,  66,  17,  39],
       [123,  98,  41, 121, 104],
       [124, 132,  35,  18, 108],
       [125,  72,  35, 110,  75],
       [126,  11,  29,  53,  37],
       [127,  58,  40,  92,  68],
       [128,  99, 108,  12,  14],
       [129,  73,  74,  23, 110],
       [130,  32,  57, 144,  77],
       [131,  56,  60,  79,  59],
       [132,  75, 108, 124,  35],
       [133,  49,  33,   0,  94],
       [134,   0,  95, 133,  70],
       [135, 114,  96,  81,  16],
       [136,  27,  65,  63, 147],
       [137,  78, 117,  44,  97],
       [138,  85,  33,  49,  70],
       [139,  99,  44, 128, 105],
       [140,  64,  67,  23,  19],
       [141, 112, 142,  21,  27],
       [142,  21,  89, 115, 112],
       [143, 111, 146,  37,  29],
       [144,  28,  77,   6, 130],
       [145,  67, 100,  20,  80],
       [146, 111,  90,  92,   9],
       [147,  63,   9,  90,  65],
       [148,  43,  39, 118, 121]], dtype=int64)

In [67]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

70 85 49 33 12

In [68]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [69]:
print(new_dist)

{129: 1, 86: 1, 10: 1, 14: 1, 15: 1, 53: 1, 106: 1, 199: 3, 8: 1, 127: 1, 187: 3, 183: 2, 92: 1, 128: 1, 114: 1, 131: 1, 186: 3, 185: 2, 101: 1, 158: 2, 32: 1, 70: 1, 33: 1, 95: 1, 25: 1, 211: 3, 99: 1, 26: 1, 134: 1, 29: 1, 206: 3, 38: 1, 103: 1, 146: 1, 120: 1, 47: 1, 27: 1, 107: 1, 109: 1, 163: 2, 5: 1, 184: 2, 41: 1, 161: 2, 137: 1, 168: 2, 197: 3, 157: 2, 210: 3, 74: 1, 205: 3, 28: 1, 182: 2, 59: 1, 126: 1, 135: 1, 84: 1, 63: 1, 11: 1, 40: 1, 49: 1, 87: 1, 189: 3, 78: 1, 178: 2, 125: 1, 82: 1, 153: 2, 116: 1, 65: 1, 39: 1, 46: 1, 12: 1, 113: 1, 100: 1, 124: 1, 94: 1, 96: 1, 64: 1, 51: 1, 36: 1, 190: 3, 50: 1, 151: 2, 58: 1, 43: 1, 4: 1, 61: 1, 174: 2, 104: 1, 24: 1, 57: 1, 121: 1, 112: 1, 45: 1, 73: 1, 207: 3, 67: 1, 154: 2, 18: 1, 77: 1, 193: 3, 71: 1, 55: 1, 172: 2, 20: 1, 166: 2, 203: 3, 119: 1, 54: 1, 79: 1, 110: 1, 213: 3, 108: 1, 208: 3, 66: 1, 89: 1, 123: 1, 165: 2, 139: 1, 48: 1, 173: 2, 34: 1, 156: 2, 16: 1, 7: 1, 180: 2, 141: 1, 118: 1, 23: 1, 69: 1, 122: 1, 60: 1, 138: 1, 191: 3, 195: 3, 142: 1, 13: 1, 3: 1, 147: 1, 152: 2, 215: 3, 6: 1, 22: 1, 93: 1, 111: 1, 83: 1, 21: 1, 181: 2}

In [70]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [71]:
print(new_dist2)

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 3, 8: 1, 9: 1, 10: 3, 11: 2, 12: 1, 13: 1, 14: 1, 15: 1, 16: 3, 17: 2, 18: 1, 19: 2, 20: 1, 21: 1, 22: 1, 23: 1, 24: 1, 25: 3, 26: 1, 27: 1, 28: 1, 29: 1, 30: 3, 31: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1, 37: 1, 38: 1, 39: 2, 40: 1, 41: 2, 42: 1, 43: 2, 44: 1, 45: 2, 46: 3, 47: 2, 48: 3, 49: 1, 50: 3, 51: 1, 52: 2, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 59: 1, 60: 1, 61: 1, 62: 3, 63: 1, 64: 2, 65: 1, 66: 1, 67: 2, 68: 1, 69: 1, 70: 1, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 1, 78: 1, 79: 1, 80: 1, 81: 3, 82: 1, 83: 2, 84: 1, 85: 1, 86: 1, 87: 1, 88: 2, 89: 1, 90: 1, 91: 1, 92: 1, 93: 1, 94: 1, 95: 1, 96: 3, 97: 1, 98: 2, 99: 1, 100: 1, 101: 3, 102: 1, 103: 1, 104: 2, 105: 1, 106: 2, 107: 3, 108: 1, 109: 1, 110: 1, 111: 1, 112: 3, 113: 1, 114: 3, 115: 1, 116: 1, 117: 1, 118: 2, 119: 1, 120: 1, 121: 2, 122: 1, 123: 2, 124: 1, 125: 1, 126: 2, 127: 1, 128: 1, 129: 1, 130: 1, 131: 1, 132: 1, 133: 1, 134: 3, 135: 3, 136: 1, 137: 1, 138: 1, 139: 1, 140: 2, 141: 3, 142: 1, 143: 1, 144: 1, 145: 1, 146: 1, 147: 1, 148: 2}

In [72]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [73]:
print(new_dist3)

{0: 129, 1: 86, 2: 10, 3: 14, 4: 15, 5: 53, 6: 106, 7: 199, 8: 8, 9: 127, 10: 187, 11: 183, 12: 92, 13: 128, 14: 114, 15: 131, 16: 186, 17: 185, 18: 101, 19: 158, 20: 32, 21: 70, 22: 33, 23: 95, 24: 25, 25: 211, 26: 99, 27: 26, 28: 134, 29: 29, 30: 206, 31: 38, 32: 103, 33: 146, 34: 120, 35: 47, 36: 27, 37: 107, 38: 109, 39: 163, 40: 5, 41: 184, 42: 41, 43: 161, 44: 137, 45: 168, 46: 197, 47: 157, 48: 210, 49: 74, 50: 205, 51: 28, 52: 182, 53: 59, 54: 126, 55: 135, 56: 84, 57: 63, 58: 11, 59: 40, 60: 49, 61: 87, 62: 189, 63: 78, 64: 178, 65: 125, 66: 82, 67: 153, 68: 116, 69: 65, 70: 39, 71: 46, 72: 12, 73: 113, 74: 100, 75: 124, 76: 94, 77: 96, 78: 64, 79: 51, 80: 36, 81: 190, 82: 50, 83: 151, 84: 58, 85: 43, 86: 4, 87: 61, 88: 174, 89: 104, 90: 24, 91: 57, 92: 121, 93: 112, 94: 45, 95: 73, 96: 207, 97: 67, 98: 154, 99: 18, 100: 77, 101: 193, 102: 71, 103: 55, 104: 172, 105: 20, 106: 166, 107: 203, 108: 119, 109: 54, 110: 79, 111: 110, 112: 213, 113: 108, 114: 208, 115: 66, 116: 89, 117: 123, 118: 165, 119: 139, 120: 48, 121: 173, 122: 34, 123: 156, 124: 16, 125: 7, 126: 180, 127: 141, 128: 118, 129: 23, 130: 69, 131: 122, 132: 60, 133: 138, 134: 191, 135: 195, 136: 142, 137: 13, 138: 3, 139: 147, 140: 152, 141: 215, 142: 6, 143: 22, 144: 93, 145: 111, 146: 83, 147: 21, 148: 181}

In [74]:
#print(new_dist[204])

<!-- Populating a dictionary  -->

In [75]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        class_example=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
            if int(v) == 1:
                safe_level=(1 * c1 + sim_12 * c2 + sim_13 * c3)/5
                class_example=1
                safe_level=round(safe_level,2)
            elif int(v) == 2:
                safe_level=(sim_12 * c1 + 1 * c2 + sim_23 * c3)/5
                class_example=2
                safe_level=round(safe_level,2)
            else:
                safe_level=(sim_13 * c1 + sim_23 * c2 + 1 * c3)/5
                class_example=3
                safe_level=round(safe_level,2)
        neigh_count.append([i,new_dist3[i],class_example,c1,c2,c3,safe_level,new_arr2[i][5]])
        #print(i," ",new_dist3[i]," ",class_example," ",c1," ",c2," ",c3," ",safe_level," ",new_arr2[i][5])
        #print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

In [76]:
#print(neigh_count)

In [77]:
# iterating a dictionary

In [78]:
# for s in range(149):
#     print(neigh_count[s])

In [79]:
# Converting a dictionary to a dataframe

In [80]:
new_main_df = pd.DataFrame(neigh_count,columns=['s_no','real_index','Class','c_one','c_two','c_three','safe_level','distance'])

In [81]:
#print(new_main_df)

In [82]:
new_main_df.set_index("s_no", inplace=True)

In [83]:
print(new_main_df)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no
0            129      1      5      0        0        1.00        12
1             86      1      5      0        0        1.00         9
2             10      1      5      0        0        1.00         9
3             14      1      5      0        0        1.00        12
4             15      1      5      0        0        1.00         9
...          ...    ...    ...    ...      ...         ...       ...
144           93      1      5      0        0        1.00         8
145          111      1      4      1        0        0.97        19
146           83      1      5      0        0        1.00         7
147           21      1      5      0        0        1.00         6
148          181      2      0      5        0        1.00        15

[149 rows x 7 columns]

In [84]:
# iterating through a dataframe, the following methods can be used .iterrows() 
# and itertuples() but itertuples is preferred because it keeps the data types and more

In [85]:
# for index, row in new_main_df.iterrows():
#     print(index, row['real_index'], row['class'], row['c_one'], row['c_two'], row['c_three'], row['safe_level'], row['distance'] )

In [86]:
for i, row in enumerate(new_main_df.itertuples(), 0):
    print(i, row.real_index)

0 129
1 86
2 10
3 14
4 15
5 53
6 106
7 199
8 8
9 127
10 187
11 183
12 92
13 128
14 114
15 131
16 186
17 185
18 101
19 158
20 32
21 70
22 33
23 95
24 25
25 211
26 99
27 26
28 134
29 29
30 206
31 38
32 103
33 146
34 120
35 47
36 27
37 107
38 109
39 163
40 5
41 184
42 41
43 161
44 137
45 168
46 197
47 157
48 210
49 74
50 205
51 28
52 182
53 59
54 126
55 135
56 84
57 63
58 11
59 40
60 49
61 87
62 189
63 78
64 178
65 125
66 82
67 153
68 116
69 65
70 39
71 46
72 12
73 113
74 100
75 124
76 94
77 96
78 64
79 51
80 36
81 190
82 50
83 151
84 58
85 43
86 4
87 61
88 174
89 104
90 24
91 57
92 121
93 112
94 45
95 73
96 207
97 67
98 154
99 18
100 77
101 193
102 71
103 55
104 172
105 20
106 166
107 203
108 119
109 54
110 79
111 110
112 213
113 108
114 208
115 66
116 89
117 123
118 165
119 139
120 48
121 173
122 34
123 156
124 16
125 7
126 180
127 141
128 118
129 23
130 69
131 122
132 60
133 138
134 191
135 195
136 142
137 13
138 3
139 147
140 152
141 215
142 6
143 22
144 93
145 111
146 83
147 21
148 181

In [87]:
# for row in new_main_df.itertuples():
#     print(getattr(row, 'real_index'), getattr(row, 'c_one'))

In [88]:
new_gb=new_main_df.groupby("Class")

In [89]:
new_1=new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [90]:
#new_1

In [91]:
#new_2=new_gb.get_group(2)

In [92]:
#new_3=new_gb.get_group(3)

In [93]:
gb_1=gb.get_group(1)

In [94]:
gb_2=gb.get_group(2)

In [95]:
gb_3=gb.get_group(3)

In [96]:
#new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [97]:
new_2=new_gb.get_group(2).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [98]:
new_2.drop(new_2[new_2['c_two'] < 4].index, inplace=True)

In [99]:
#new_2

In [100]:
#b=len(new_2.index)

In [101]:
#print(b)

In [102]:
#s=m-b

In [103]:
#print(s)

In [104]:
minor_c_2=new_2.sample(n=m, replace='True')
print(minor_c_2)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no
41           184      2      0      5        0        1.00        31
45           168      2      0      5        0        1.00        20
19           158      2      1      4        0        0.97        22
148          181      2      0      5        0        1.00        15
140          152      2      1      4        0        0.97        12
...          ...    ...    ...    ...      ...         ...       ...
104          172      2      0      5        0        1.00        23
45           168      2      0      5        0        1.00        20
140          152      2      1      4        0        0.97        12
121          173      2      0      5        0        1.00        19
121          173      2      0      5        0        1.00        19

[64 rows x 7 columns]

In [105]:
new_3=new_gb.get_group(3).sort_values(['safe_level', 'distance'], ascending=[False, True])

In [106]:
new_3.drop(new_3[new_3['c_three'] < 4].index, inplace=True)

In [107]:
minor_c_3=new_3.sample(n=m, replace='True')
print(minor_c_3)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no
96           207      3      0      0        5        1.00        62
48           210      3      0      0        5        1.00        43
30           206      3      0      0        5        1.00        49
16           186      3      1      0        4        0.85        56
135          195      3      0      0        5        1.00       130
...          ...    ...    ...    ...      ...         ...       ...
16           186      3      1      0        4        0.85        56
81           190      3      1      0        4        0.85        69
107          203      3      1      0        4        0.85        33
81           190      3      1      0        4        0.85        69
7            199      3      0      0        5        1.00        60

[64 rows x 7 columns]

In [108]:
new_gb

In [109]:
gb

In [110]:
#new_1

In [111]:
new_1.drop(new_1[new_1['c_one'] < 5].index, inplace=True)

In [112]:
#new_1

In [113]:
#for i, row in enumerate(new_1.itertuples(index=True), 0):
    #print(i, row.Index, row.real_index, row.Class, row.c_one, row.c_two, row.c_three, row.safe_level, row.distance)

In [114]:
#r=len(new_1.index)-m

In [115]:
#print(r)

In [116]:
major_c_1=new_1.sample(n=m)
print(major_c_1)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no
35            47      1      5      0        0         1.0         8
138            3      1      5      0        0         1.0        18
70            39      1      5      0        0         1.0        12
72            12      1      5      0        0         1.0         8
57            63      1      5      0        0         1.0         6
...          ...    ...    ...    ...      ...         ...       ...
29            29      1      5      0        0         1.0         5
99            18      1      5      0        0         1.0         7
2             10      1      5      0        0         1.0         9
93           112      1      5      0        0         1.0         6
139          147      1      5      0        0         1.0         8

[64 rows x 7 columns]

In [117]:
for i, row in enumerate(major_c_1.itertuples(index=True), 0):
    print(i, row.real_index)

0 47
1 3
2 39
3 12
4 63
5 127
6 134
7 32
8 5
9 64
10 74
11 36
12 96
13 25
14 107
15 87
16 49
17 124
18 71
19 53
20 60
21 142
22 77
23 120
24 129
25 45
26 83
27 15
28 33
29 131
30 89
31 116
32 26
33 48
34 55
35 54
36 99
37 95
38 24
39 122
40 13
41 73
42 141
43 146
44 123
45 59
46 8
47 84
48 135
49 94
50 113
51 40
52 27
53 22
54 69
55 86
56 61
57 38
58 118
59 29
60 18
61 10
62 112
63 147

In [118]:
#how to generate a random list from an interval
#num_list = random.sample(range(0, len(new_1.index)), r)
#print(num_list)

In [119]:
maj_c_filtered=[]
for i, row in enumerate(major_c_1.itertuples(index=True), 0):
    a=gb_1.at[row.real_index, 'Class']
    b=gb_1.at[row.real_index, 'Oxin']
    c=gb_1.at[row.real_index, 'Onine']
    d=gb_1.at[row.real_index, 'Hormone']
    e=gb_1.at[row.real_index, 'Tsh']
    f=gb_1.at[row.real_index, 'Resin']
    maj_c_filtered.append([a,b,c,d,e,f])

In [120]:
print(maj_c_filtered)

[[1, 109, 10.0, 1.3, 1.8, 4.3], [1, 127, 12.9, 2.4, 1.4, 0.6], [1, 130, 9.5, 1.7, 0.4, 3.2], [1, 110, 11.3, 2.3, 0.9, 3.3], [1, 115, 10.4, 1.8, 1.6, 2.0], [1, 102, 8.4, 1.5, 0.8, 2.4], [1, 112, 10.6, 1.6, 0.9, -0.1], [1, 116, 11.1, 2.0, 1.2, 2.3], [1, 105, 7.3, 1.5, 1.5, -0.1], [1, 116, 10.0, 1.7, 1.5, 4.3], [1, 126, 9.4, 2.3, 1.0, 4.0], [1, 117, 11.0, 1.4, 1.5, 2.1], [1, 114, 9.1, 2.6, 1.5, 1.5], [1, 121, 10.1, 1.7, 1.3, 0.1], [1, 105, 11.1, 1.1, 0.8, 1.2], [1, 119, 11.4, 2.3, 2.2, 1.6], [1, 100, 9.5, 2.5, 1.3, -0.2], [1, 111, 9.1, 1.7, 1.2, 4.1], [1, 96, 9.4, 1.5, 1.0, 3.1], [1, 115, 8.1, 1.7, 0.6, 2.2], [1, 110, 8.7, 1.9, 1.6, 4.4], [1, 98, 5.7, 0.4, 1.3, 2.8], [1, 119, 12.9, 1.5, 1.3, 3.6], [1, 111, 8.5, 1.6, 1.2, 7.7], [1, 130, 10.0, 1.6, 0.9, 4.6], [1, 123, 8.1, 2.3, 1.0, 5.1], [1, 103, 8.5, 1.8, 1.9, 1.1], [1, 122, 9.7, 1.6, 0.9, 2.2], [1, 110, 7.8, 1.9, 2.1, 6.4], [1, 110, 6.3, 1.0, 0.8, 1.0], [1, 105, 8.1, 2.0, 1.9, -0.5], [1, 105, 8.7, 1.5, 1.1, 1.5], [1, 100, 6.1, 2.4, 1.8, 3.8], [1, 120, 6.8, 1.9, 1.3, 1.9], [1, 106, 9.4, 1.7, 0.9, 3.1], [1, 119, 8.0, 2.0, 0.6, 3.2], [1, 120, 7.1, 1.2, 1.5, 4.3], [1, 109, 12.4, 2.3, 1.7, 0.8], [1, 102, 7.6, 1.8, 2.0, 2.5], [1, 98, 10.4, 1.6, 2.3, -0.7], [1, 116, 9.2, 2.7, 1.0, 4.2], [1, 133, 9.7, 2.9, 0.8, 1.9], [1, 105, 5.7, 1.0, 0.9, 0.9], [1, 126, 10.4, 1.7, 1.2, 3.5], [1, 117, 7.8, 2.0, 1.0, 3.9], [1, 106, 11.3, 1.8, 0.9, 1.0], [1, 114, 9.9, 2.4, 1.5, 5.7], [1, 98, 9.1, 1.4, 1.9, -0.3], [1, 118, 6.5, 1.2, 1.2, 1.7], [1, 98, 8.6, 1.6, 1.6, 6.0], [1, 109, 8.9, 1.7, 1.0, 0.9], [1, 100, 10.5, 2.4, 0.9, 1.9], [1, 106, 9.6, 2.4, 1.0, 1.3], [1, 103, 10.1, 1.3, 0.7, 0.1], [1, 113, 11.1, 1.7, 0.8, 2.3], [1, 107, 13.0, 1.5, 2.8, 1.7], [1, 103, 8.1, 1.4, 0.5, 3.8], [1, 106, 9.4, 1.5, 0.8, 0.5], [1, 112, 6.8, 1.7, 1.4, 3.3], [1, 105, 11.1, 2.0, 1.0, 1.0], [1, 114, 6.7, 1.5, 1.0, 3.5], [1, 107, 13.0, 1.1, 0.9, 3.1], [1, 118, 10.6, 1.8, 1.4, 3.0], [1, 114, 7.5, 1.1, 1.6, 4.4]]

In [121]:
for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    print(i, row.real_index)

0 184
1 168
2 158
3 181
4 152
5 154
6 163
7 154
8 168
9 173
10 184
11 165
12 168
13 156
14 158
15 181
16 152
17 161
18 163
19 173
20 173
21 165
22 152
23 172
24 165
25 158
26 158
27 163
28 168
29 165
30 173
31 168
32 161
33 154
34 181
35 173
36 152
37 165
38 154
39 181
40 153
41 161
42 156
43 153
44 154
45 173
46 163
47 156
48 154
49 158
50 161
51 158
52 158
53 163
54 168
55 152
56 172
57 181
58 152
59 172
60 168
61 152
62 173
63 173

In [122]:
min_c_2_filtered=[]
for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    a=gb_2.at[row.real_index, 'Class']
    b=gb_2.at[row.real_index, 'Oxin']
    c=gb_2.at[row.real_index, 'Onine']
    d=gb_2.at[row.real_index, 'Hormone']
    e=gb_2.at[row.real_index, 'Tsh']
    f=gb_2.at[row.real_index, 'Resin']
    min_c_2_filtered.append([a,b,c,d,e,f])

In [123]:
print(min_c_2_filtered)

[[2, 79, 19.0, 5.5, 0.9, 0.3], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 79, 19.0, 5.5, 0.9, 0.3], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 65, 18.2, 10.0, 1.3, 0.1], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 89, 14.3, 4.1, 0.5, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 84, 21.5, 2.7, 1.1, -0.6], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 89, 14.3, 4.1, 0.5, 0.2], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 113, 17.2, 1.8, 1.0, 0.0], [2, 89, 14.3, 4.1, 0.5, 0.2], [2, 65, 18.2, 10.0, 1.3, 0.1], [2, 113, 17.2, 1.8, 1.0, 0.0], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 65, 18.2, 10.0, 1.3, 0.1], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 89, 14.3, 4.1, 0.5, 0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 84, 21.5, 2.7, 1.1, -0.6], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 84, 21.5, 2.7, 1.1, -0.6], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 84, 18.5, 4.4, 1.1, -0.3]]

In [124]:
for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    print(i, row.real_index)

0 207
1 210
2 206
3 186
4 195
5 193
6 187
7 206
8 210
9 210
10 206
11 187
12 195
13 210
14 210
15 193
16 190
17 193
18 206
19 186
20 193
21 193
22 205
23 210
24 205
25 187
26 206
27 195
28 207
29 203
30 207
31 193
32 186
33 206
34 206
35 190
36 206
37 199
38 187
39 203
40 203
41 187
42 187
43 186
44 195
45 207
46 208
47 195
48 190
49 187
50 186
51 195
52 206
53 186
54 208
55 208
56 210
57 205
58 190
59 186
60 190
61 203
62 190
63 199

In [125]:
min_c_3_filtered=[]
for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    a=gb_3.at[row.real_index, 'Class']
    b=gb_3.at[row.real_index, 'Oxin']
    c=gb_3.at[row.real_index, 'Onine']
    d=gb_3.at[row.real_index, 'Hormone']
    e=gb_3.at[row.real_index, 'Tsh']
    f=gb_3.at[row.real_index, 'Resin']
    min_c_3_filtered.append([a,b,c,d,e,f])

In [126]:
print(min_c_3_filtered)

[[3, 123, 1.9, 0.3, 22.8, 22.2], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 120, 3.4, 1.8, 7.5, 21.5], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 120, 3.4, 1.8, 7.5, 21.5], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 123, 1.9, 0.3, 22.8, 22.2], [3, 113, 5.1, 0.7, 5.8, 19.6], [3, 123, 1.9, 0.3, 22.8, 22.2], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 121, 4.7, 1.8, 11.2, 53.0], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 113, 5.1, 0.7, 5.8, 19.6], [3, 113, 5.1, 0.7, 5.8, 19.6], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 123, 1.9, 0.3, 22.8, 22.2], [3, 112, 2.6, 0.7, 41.0, 19.0], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 112, 2.6, 0.7, 41.0, 19.0], [3, 112, 2.6, 0.7, 41.0, 19.0], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 120, 3.4, 1.8, 7.5, 21.5], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 113, 5.1, 0.7, 5.8, 19.6], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 121, 4.7, 1.8, 11.2, 53.0]]

In [127]:
new_min_c_3_filtered = pd.DataFrame(min_c_3_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [128]:
print(new_min_c_3_filtered)

    Class  Oxin  Onine  Hormone   Tsh  Resin
0       3   123    1.9      0.3  22.8   22.2
1       3   119    5.1      1.1   7.0   40.8
2       3   125    3.7      1.1   8.5   25.9
3       3   125    2.3      0.9  16.5    9.5
4       3   119    0.8      0.7  56.4   21.6
..    ...   ...    ...      ...   ...    ...
59      3   125    2.3      0.9  16.5    9.5
60      3   119    3.8      1.1  23.0    5.7
61      3   113    5.1      0.7   5.8   19.6
62      3   119    3.8      1.1  23.0    5.7
63      3   121    4.7      1.8  11.2   53.0

[64 rows x 6 columns]

In [129]:
new_min_c_2_filtered = pd.DataFrame(min_c_2_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [130]:
print(new_min_c_2_filtered)

    Class  Oxin  Onine  Hormone  Tsh  Resin
0       2    79   19.0      5.5  0.9    0.3
1       2    89   21.8      7.1  0.7   -0.1
2       2   110   20.3      3.7  0.6    0.2
3       2    88   16.5      4.9  0.8    0.1
4       2   111   16.0      2.1  0.9   -0.1
..    ...   ...    ...      ...  ...    ...
59      2    84   21.5      2.7  1.1   -0.6
60      2    89   21.8      7.1  0.7   -0.1
61      2   111   16.0      2.1  0.9   -0.1
62      2    84   18.5      4.4  1.1   -0.3
63      2    84   18.5      4.4  1.1   -0.3

[64 rows x 6 columns]

In [131]:
new_maj_c_filtered = pd.DataFrame(maj_c_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [132]:
print(new_maj_c_filtered)

    Class  Oxin  Onine  Hormone  Tsh  Resin
0       1   109   10.0      1.3  1.8    4.3
1       1   127   12.9      2.4  1.4    0.6
2       1   130    9.5      1.7  0.4    3.2
3       1   110   11.3      2.3  0.9    3.3
4       1   115   10.4      1.8  1.6    2.0
..    ...   ...    ...      ...  ...    ...
59      1   105   11.1      2.0  1.0    1.0
60      1   114    6.7      1.5  1.0    3.5
61      1   107   13.0      1.1  0.9    3.1
62      1   118   10.6      1.8  1.4    3.0
63      1   114    7.5      1.1  1.6    4.4

[64 rows x 6 columns]

In [133]:
result = new_maj_c_filtered.append([new_min_c_2_filtered, new_min_c_3_filtered], ignore_index='True')

In [134]:
print(result)

     Class  Oxin  Onine  Hormone   Tsh  Resin
0        1   109   10.0      1.3   1.8    4.3
1        1   127   12.9      2.4   1.4    0.6
2        1   130    9.5      1.7   0.4    3.2
3        1   110   11.3      2.3   0.9    3.3
4        1   115   10.4      1.8   1.6    2.0
..     ...   ...    ...      ...   ...    ...
187      3   125    2.3      0.9  16.5    9.5
188      3   119    3.8      1.1  23.0    5.7
189      3   113    5.1      0.7   5.8   19.6
190      3   119    3.8      1.1  23.0    5.7
191      3   121    4.7      1.8  11.2   53.0

[192 rows x 6 columns]

In [135]:
result.to_csv("balanced_new_thyroid.csv")

In [136]:
result.sample(frac=1).reset_index(drop=True)

     Class  Oxin  Onine  Hormone  Tsh  Resin
0        2    88   16.5      4.9  0.8    0.1
1        1   110   11.3      2.3  0.9    3.3
2        2   110   20.3      3.7  0.6    0.2
3        1   106    9.6      2.4  1.0    1.3
4        2    84   18.5      4.4  1.1   -0.3
..     ...   ...    ...      ...  ...    ...
187      2    65   18.2     10.0  1.3    0.1
188      2    89   21.8      7.1  0.7   -0.1
189      3   113    5.1      0.7  5.8   19.6
190      1   116   11.1      2.0  1.2    2.3
191      2    84   18.5      4.4  1.1   -0.3

[192 rows x 6 columns]

In [137]:
result.to_csv("balanced_new_thyroid_rand.csv")

In [138]:
from sklearn import svm

In [139]:
model=svm.SVC(C = 1)

In [140]:
model.fit(X_train, Y_train)

SVC(C=1)

In [141]:
Y_pred=model.predict(X_test)

In [142]:
print(Y_pred)

[3 3 2 1 1 1 1 1 3 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1]

In [143]:
from sklearn import metrics
Y_pred=model.predict(X_train)
print("Accuracy: ", metrics.accuracy_score(Y_train, Y_pred))

Accuracy:  0.7986577181208053